import { randomUUID, randomBytes } from "node:crypto";
import { Store, hash } from "../infrastructure/database.ts";
import { requireUser, type User } from "./auth.ts";
import { check } from "../domain/errors.ts";
import { object, payload, version, text, email, ids, isoDate, optionalText,identifier } from "../domain/validation.ts";
function model(row: Record<string, unknown>): Record<string, unknown> { return { id: row.id, version: row.version, payload: typeof row.payload === "string" ? JSON.parse(row.payload) as unknown : row.payload, updatedAt: row.updated_at }; }
function studentPayload(value:unknown):unknown {if(Array.isArray(value))return value.map(studentPayload);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(object(value)).filter(([key])=>!['teacherNotes','answerKey'].includes(key)).map(([key,item])=>[key,studentPayload(item)]));return value;}
export class CollaborationService {
  readonly store: Store;
  constructor(store: Store) { this.store = store; }
  shelf(user: User | null): Record<string, unknown> { const account = requireUser(user); const row = this.store.get("SELECT * FROM shelves WHERE user_id=?", account.id); return row ? model(row) : { version: 0, payload: { bookmarks: [], notes: {} } }; }
  putShelf(user: User | null, value: unknown, requestId: string): Record<string, unknown> {
    const account = requireUser(user); const input = object(value); const expected = version(input.version); const data = payload(input.payload); const bookmarks = ids(data.bookmarks); const notes = object(data.notes);
    const safeId = /^(?!(?:__proto__|constructor|prototype)$)[a-zA-Z0-9_-]{1,80}$/;
    check(bookmarks.every((id) => safeId.test(id)) && Object.entries(notes).length <= 500 && Object.values(notes).every((item) => typeof item === "string" && item.length <= 4000), 400, "INVALID_INPUT", "개인 메모 형식을 확인해 주세요.");
    for (const key of Object.keys(notes)) check(safeId.test(key), 400, "INVALID_INPUT", "메모 식별자를 확인해 주세요.");
    this.store.transaction(() => {
      const current = this.store.get("SELECT version FROM shelves WHERE user_id=?", account.id);
      check(Number(current?.version ?? 0) === expected, 409, "VERSION_CONFLICT", "다른 기기에서 수정되었습니다. 최신 자료를 다시 불러와 주세요.");
      this.store.run("INSERT INTO shelves VALUES (?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET version=excluded.version,payload=excluded.payload,updated_at=excluded.updated_at", account.id, expected + 1, JSON.stringify({ bookmarks, notes }), new Date().toISOString()); this.store.audit(account.id, "shelf.update", account.id, requestId);
    }); return this.shelf(account);
  }
  workspaces(user: User | null): { items: Record<string, unknown>[] } { const account = requireUser(user); return { items: this.store.all("SELECT * FROM workspaces WHERE user_id=? ORDER BY updated_at DESC", account.id).map(model) }; }
  workspace(user: User | null, id: string): Record<string, unknown> { const account = requireUser(user); const row = this.store.get("SELECT * FROM workspaces WHERE id=? AND user_id=?", id, account.id); check(row, 404, "RESOURCE_NOT_FOUND", "연구 공간을 찾을 수 없습니다."); return model(row); }
  saveWorkspace(user: User | null, id: string | null, value: unknown, requestId: string): Record<string, unknown> {
    const account = requireUser(user); const input = object(value); const data = payload(input.payload); const now = new Date().toISOString(); const workspaceId = id || randomUUID();
    this.store.transaction(() => {
      if (id) { const row = this.store.get("SELECT version FROM workspaces WHERE id=? AND user_id=?", id, account.id); check(row, 404, "RESOURCE_NOT_FOUND", "연구 공간을 찾을 수 없습니다."); const expected = version(input.version); check(row.version === expected, 409, "VERSION_CONFLICT", "연구 공간이 다른 곳에서 수정되었습니다."); this.store.run("UPDATE workspaces SET version=version+1,payload=?,updated_at=? WHERE id=?", JSON.stringify(data), now, id); }
      else this.store.run("INSERT INTO workspaces VALUES (?,?,?,?,?)", workspaceId, account.id, 1, JSON.stringify(data), now);
      this.store.audit(account.id, id ? "workspace.update" : "workspace.create", workspaceId, requestId);
    }); return this.workspace(account, workspaceId);
  }
  deleteWorkspace(user: User | null, id: string, requestId: string): void { const account = requireUser(user); this.workspace(account, id); this.store.run("DELETE FROM workspaces WHERE id=? AND user_id=?", id, account.id); this.store.audit(account.id, "workspace.delete", id, requestId); }
  member(user: User | null, id: string, edit = false, owner = false): User {
    const account = requireUser(user); const row = this.store.get("SELECT role FROM space_members WHERE space_id=? AND user_id=?", id, account.id);
    check(row, 404, "RESOURCE_NOT_FOUND", "공동 공간을 찾을 수 없습니다.");
    check(!owner || row.role === "owner", 403, "FORBIDDEN", "소유자 권한이 필요합니다."); check(!edit || row.role !== "viewer", 403, "FORBIDDEN", "편집 권한이 필요합니다."); return account;
  }
  spaces(user: User | null): { items: Record<string, unknown>[] } {
    const account = requireUser(user); return { items: this.store.all("SELECT s.*,m.role FROM spaces s JOIN space_members m ON m.space_id=s.id WHERE m.user_id=? ORDER BY s.updated_at DESC", account.id).map((row) => ({ ...model(row),...row.kind==='study'&&row.role==='viewer'?{payload:studentPayload(model(row).payload)}:{}, kind: row.kind, title: row.title, description: row.description, role: row.role })) };
  }
  space(user: User | null, id: string): Record<string, unknown> {
    const account = this.member(user, id); const row = this.store.get("SELECT s.*,m.role FROM spaces s JOIN space_members m ON m.space_id=s.id WHERE s.id=? AND m.user_id=?", id, account.id); check(row, 404, "RESOURCE_NOT_FOUND", "공간을 찾을 수 없습니다.");
    const tasks = this.store.all("SELECT t.*,d.version,d.teacher_notes,d.answer_key,d.reading_metadata,d.updated_at FROM tasks t LEFT JOIN task_details d ON d.task_id=t.id WHERE space_id=? ORDER BY created_at", id).map((task) => ({ id: task.id,version:Number(task.version||1),createdAt:task.created_at,updatedAt:task.updated_at||task.created_at, title: task.title, instructions: task.instructions, recordIds: JSON.parse(String(task.record_ids)) as unknown, dueAt: task.due_at,readingMetadata:JSON.parse(String(task.reading_metadata||'[]')) as unknown,...row.role!=='viewer'?{teacherNotes:String(task.teacher_notes||''),answerKey:String(task.answer_key||'')}:{}}));
    const submissions = this.store.all(`SELECT sub.*,d.task_version,d.created_at,d.feedback_version,d.feedback_submission_version,d.feedback_at FROM submissions sub JOIN tasks t ON t.id=sub.task_id LEFT JOIN submission_details d ON d.submission_id=sub.id WHERE t.space_id=?${row.role === "viewer" ? " AND sub.user_id=?" : ""}`, ...row.role === "viewer" ? [id, account.id] : [id]).map((sub) => ({ ...model(sub), taskId: sub.task_id, userId: sub.user_id, feedback: sub.feedback,submissionVersion:sub.version,taskVersion:Number(sub.task_version||1),createdAt:sub.created_at||sub.updated_at,feedbackVersion:Number(sub.feedback_version||0),feedbackSubmissionVersion:sub.feedback_submission_version??null,feedbackAt:sub.feedback_at??null }));
    const members = this.store.all("SELECT u.id AS userId,u.name,u.email,m.role FROM space_members m JOIN users u ON u.id=m.user_id WHERE m.space_id=?", id).map((member) => row.role === "viewer" && member.userId !== account.id ? { userId: member.userId, name: member.name, role: member.role } : member);
    return { ...model(row),...row.kind==='study'&&row.role==='viewer'?{payload:studentPayload(model(row).payload)}:{}, ownerId: row.owner_id, kind: row.kind, title: row.title, description: row.description, role: row.role, members, tasks, submissions };
  }
  createSpace(user: User | null, value: unknown, requestId: string): Record<string, unknown> {
    const account = requireUser(user); const input = object(value); check(input.kind === "study" || input.kind === "research", 400, "INVALID_INPUT", "공간 유형을 확인해 주세요."); const id = randomUUID();
    this.store.transaction(() => { this.store.run("INSERT INTO spaces VALUES (?,?,?,?,?,?,?,?)", id, account.id, String(input.kind), text(input.title, "제목", 200), optionalText(input.description, "설명", 2000), 1, JSON.stringify(input.payload === undefined ? {} : payload(input.payload)), new Date().toISOString()); this.store.run("INSERT INTO space_members VALUES (?,?,?)", id, account.id, "owner"); this.store.audit(account.id, "space.create", id, requestId); }); return this.space(account, id);
  }
  putSpace(user: User | null, id: string, value: unknown, requestId: string): Record<string, unknown> {
    const account = this.member(user, id, true); const input = object(value); const data = payload(input.payload); const expected = version(input.version);
    this.store.transaction(() => { check(this.store.run("UPDATE spaces SET payload=?,version=version+1,updated_at=? WHERE id=? AND version=?", JSON.stringify(data), new Date().toISOString(), id, expected) === 1, 409, "VERSION_CONFLICT", "공동 공간의 최신 자료를 다시 불러와 주세요."); this.store.audit(account.id, "space.update", id, requestId); }); return this.space(account, id);
  }
  addMember(user: User | null, id: string, value: unknown, requestId: string): Record<string, unknown> {
    const account = this.member(user, id, true, true); const input = object(value); check(input.role === "editor" || input.role === "viewer", 400, "INVALID_INPUT", "구성원 역할을 확인해 주세요."); const target = this.store.get("SELECT id FROM users WHERE email=? AND deactivated=0", email(input.email)); check(target, 404, "RESOURCE_NOT_FOUND", "가입한 계정을 찾을 수 없습니다.");
    check(target.id !== account.id, 409, "OWNER_PROTECTED", "소유자 역할은 별도 이전 절차를 사용해 주세요.");
    this.store.run("INSERT INTO space_members VALUES (?,?,?) ON CONFLICT(space_id,user_id) DO UPDATE SET role=excluded.role", id, String(target.id), input.role); this.store.audit(account.id, "space.member_update", id, requestId); return this.space(account, id);
  }
  removeMember(user: User | null, id: string, userId: string, requestId: string): void { const account = this.member(user, id, true, true); check(account.id !== userId, 409, "OWNER_PROTECTED", "소유자는 먼저 소유권을 이전해야 합니다."); this.store.run("DELETE FROM space_members WHERE space_id=? AND user_id=?", id, userId); this.store.audit(account.id, "space.member_remove", id, requestId); }
  transfer(user: User | null, id: string, value: unknown, requestId: string): Record<string, unknown> { const account = this.member(user, id, true, true); const input = object(value); const target = this.store.get("SELECT u.id FROM users u JOIN space_members m ON m.user_id=u.id WHERE m.space_id=? AND u.email=? AND u.deactivated=0", id, email(input.email)); check(target && target.id !== account.id, 400, "INVALID_INPUT", "기존 구성원을 새 소유자로 지정해 주세요."); this.store.transaction(() => { this.store.run("UPDATE space_members SET role='editor' WHERE space_id=? AND user_id=?", id, account.id); this.store.run("UPDATE space_members SET role='owner' WHERE space_id=? AND user_id=?", id, String(target.id)); this.store.run("UPDATE spaces SET owner_id=? WHERE id=?", String(target.id), id); this.store.audit(account.id, "space.owner_transfer", id, requestId); }); return this.space(account, id); }
  invite(user: User | null, id: string, value: unknown, requestId: string): Record<string, unknown> {
    const account = this.member(user, id, true, true); const input = object(value); check(input.role === "viewer" || input.role === "editor", 400, "INVALID_INPUT", "초대 역할을 확인해 주세요."); const maxUses = version(input.maxUses); check(maxUses >= 1 && maxUses <= 100, 400, "INVALID_INPUT", "초대 사용 횟수는 1~100입니다."); const expiresAt = isoDate(input.expiresAt); check(Date.parse(expiresAt) > Date.now() && Date.parse(expiresAt) <= Date.now() + 30 * 86400000, 400, "INVALID_INPUT", "초대 기한은 30일 이내여야 합니다."); const code = randomBytes(24).toString("base64url");
    this.store.run("INSERT INTO invitations VALUES (?,?,?,?,?,?)", hash(code), id, input.role, maxUses, 0, expiresAt); this.store.audit(account.id, "space.invite", id, requestId); return { joinCode: code, expiresAt, maxUses };
  }
  join(user: User | null, value: unknown, requestId: string): Record<string, unknown> { const account = requireUser(user); const input = object(value); const token = text(input.code, "초대 코드", 100); let id = ""; this.store.transaction(() => { const invitation = this.store.get("SELECT * FROM invitations WHERE token_hash=? AND expires_at>? AND uses<max_uses", hash(token), new Date().toISOString()); check(invitation, 404, "INVITATION_UNAVAILABLE", "초대 코드가 유효하지 않습니다."); id = String(invitation.space_id); if (!this.store.get("SELECT role FROM space_members WHERE space_id=? AND user_id=?", id, account.id)) { this.store.run("INSERT INTO space_members VALUES (?,?,?)", id, account.id, String(invitation.role)); this.store.run("UPDATE invitations SET uses=uses+1 WHERE token_hash=?", hash(token)); } this.store.audit(account.id, "space.join", id, requestId); }); return this.space(account, id); }
  task(user: User | null, id: string, value: unknown, requestId: string,existingId?:string): Record<string, unknown> {
    const account=this.member(user,id,true),input=object(value),taskId=existingId||randomUUID(),recordIds=ids(input.recordIds),now=new Date().toISOString();
    const reading=input.readingMetadata ?? [];check(Array.isArray(reading)&&reading.length<=100,400,'INVALID_INPUT','읽기 자료 범위를 확인해 주세요.');const metadata=reading.map((entry)=>{const item=object(entry);check(Number.isInteger(item.minutes)&&Number(item.minutes)>=1&&Number(item.minutes)<=1440,400,'INVALID_INPUT','예상 읽기 시간을 확인해 주세요.');const recordId=identifier(item.recordId);check(recordIds.includes(recordId),400,'SOURCE_MISMATCH','과제 기록과 읽기 자료가 일치해야 합니다.');return {recordId,minutes:Number(item.minutes),sourceKind:text(item.sourceKind,'출처 종류',100),limitations:optionalText(item.limitations,'자료 한계',2000)};});
    const title=text(input.title,'과제 제목',200),instructions=text(input.instructions,'과제 안내',10000),teacherNotes=optionalText(input.teacherNotes,'교사용 메모',10000),answerKey=optionalText(input.answerKey,'교사용 답안',10000),dueAt=input.dueAt?isoDate(input.dueAt):null;
    this.store.transaction(()=>{let revision=1;if(existingId){const row=this.store.get('SELECT t.id,d.version FROM tasks t LEFT JOIN task_details d ON d.task_id=t.id WHERE t.id=? AND t.space_id=?',taskId,id);check(row,404,'RESOURCE_NOT_FOUND','과제를 찾을 수 없습니다.');check(Number(row.version||1)===version(input.version),409,'VERSION_CONFLICT','과제 계획이 변경되었습니다.');revision=Number(row.version||1)+1;this.store.run('UPDATE tasks SET title=?,instructions=?,record_ids=?,due_at=? WHERE id=?',title,instructions,JSON.stringify(recordIds),dueAt,taskId);}else this.store.run('INSERT INTO tasks VALUES (?,?,?,?,?,?,?)',taskId,id,title,instructions,JSON.stringify(recordIds),dueAt,now);this.store.run('INSERT INTO task_details VALUES (?,?,?,?,?,?) ON CONFLICT(task_id) DO UPDATE SET version=excluded.version,teacher_notes=excluded.teacher_notes,answer_key=excluded.answer_key,reading_metadata=excluded.reading_metadata,updated_at=excluded.updated_at',taskId,revision,teacherNotes,answerKey,JSON.stringify(metadata),now);this.store.audit(account.id,existingId?'space.task_update':'space.task_create',taskId,requestId);});return this.space(account,id);
  }
  submit(user: User | null, id: string, taskId: string, value: unknown, requestId: string): Record<string, unknown> {
    const account = this.member(user, id); check(this.store.get("SELECT id FROM tasks WHERE id=? AND space_id=?", taskId, id), 404, "RESOURCE_NOT_FOUND", "과제를 찾을 수 없습니다."); const input = object(value); const data = payload(input.payload); text(data.answer, "답변", 20000); ids(data.recordIds); if (data.evidenceNotes !== undefined) text(data.evidenceNotes, "근거 메모", 10000, 0); const expected = version(input.version);
    this.store.transaction(() => { const current = this.store.get("SELECT * FROM submissions WHERE task_id=? AND user_id=?", taskId, account.id); check(Number(current?.version ?? 0) === expected, 409, "VERSION_CONFLICT", "제출 자료가 변경되었습니다.");const submissionId=String(current?.id||randomUUID()),now=new Date().toISOString(),taskVersion=Number(this.store.get('SELECT version FROM task_details WHERE task_id=?',taskId)?.version||1); if (current) this.store.run("UPDATE submissions SET payload=?,version=version+1,feedback='',feedback_by=NULL,updated_at=? WHERE id=?", JSON.stringify(data), now,submissionId); else this.store.run("INSERT INTO submissions (id,task_id,user_id,version,payload,updated_at) VALUES (?,?,?,?,?,?)",submissionId, taskId, account.id, 1, JSON.stringify(data),now);this.store.run('INSERT INTO submission_details(submission_id,task_version,created_at) VALUES (?,?,?) ON CONFLICT(submission_id) DO UPDATE SET task_version=excluded.task_version,feedback_submission_version=NULL,feedback_at=NULL',submissionId,taskVersion,now);this.store.run('INSERT INTO submission_history VALUES (?,?,?,?,?)',submissionId,expected+1,taskVersion,JSON.stringify(data),now); this.store.audit(account.id, "space.submission", taskId, requestId); }); return this.space(account, id);
  }
  feedback(user: User | null, id: string, submissionId: string, value: unknown, requestId: string): Record<string, unknown> { const account = this.member(user, id, true); const input = object(value); const expected = version(input.version); this.store.transaction(() => { const row = this.store.get("SELECT sub.id,sub.version FROM submissions sub JOIN tasks t ON t.id=sub.task_id WHERE sub.id=? AND t.space_id=?", submissionId, id); check(row, 404, "RESOURCE_NOT_FOUND", "제출 자료를 찾을 수 없습니다."); check(row.version === expected, 409, "VERSION_CONFLICT", "답안이 변경되었습니다. 최신 제출 자료를 확인해 주세요.");const note=text(input.feedback,'피드백',10000),now=new Date().toISOString(),feedbackVersion=Number(this.store.get('SELECT feedback_version FROM submission_details WHERE submission_id=?',submissionId)?.feedback_version||0)+1;this.store.run('INSERT INTO submission_details VALUES (?,?,?, ?,?,?) ON CONFLICT(submission_id) DO UPDATE SET feedback_version=excluded.feedback_version,feedback_submission_version=excluded.feedback_submission_version,feedback_at=excluded.feedback_at',submissionId,1,now,feedbackVersion,expected,now);this.store.run('INSERT INTO feedback_history VALUES (?,?,?,?,?,?,?)',randomUUID(),submissionId,expected,feedbackVersion,note,account.id,now); this.store.run("UPDATE submissions SET feedback=?,feedback_by=?,updated_at=? WHERE id=?",note, account.id,now, submissionId); this.store.audit(account.id, "space.feedback", submissionId, requestId); }); return this.space(account, id); }
  submissionHistory(user:User|null,id:string,submissionId:string):Record<string,unknown>{const account=this.member(user,id),membership=this.store.get('SELECT role FROM space_members WHERE space_id=? AND user_id=?',id,account.id),submission=this.store.get('SELECT s.user_id FROM submissions s JOIN tasks t ON t.id=s.task_id WHERE s.id=? AND t.space_id=?',submissionId,id);check(submission&&(membership?.role!=='viewer'||submission.user_id===account.id),404,'RESOURCE_NOT_FOUND','제출 이력을 찾을 수 없습니다.');return {revisions:this.store.all('SELECT version,task_version AS taskVersion,payload,created_at AS createdAt FROM submission_history WHERE submission_id=? ORDER BY version DESC LIMIT 500',submissionId).map(row=>({...row,payload:JSON.parse(String(row.payload)) as unknown})),feedback:this.store.all('SELECT submission_version AS submissionVersion,feedback_version AS feedbackVersion,feedback,created_at AS createdAt FROM feedback_history WHERE submission_id=? ORDER BY feedback_version DESC LIMIT 500',submissionId)};}
}
