import { randomUUID } from "node:crypto";
import type { Adapters, PaymentEvent } from "../adapters/contracts.ts";
import type { ApiConfig } from "../config.ts";
import { Store } from "../infrastructure/database.ts";
import { requireUser, type User } from "./auth.ts";
import { requirePermission } from "../domain/permissions.ts";
import { object, identifier, version, text } from "../domain/validation.ts";
import { check, AppError } from "../domain/errors.ts";
export class CommerceService {
  readonly store: Store; readonly adapters: Adapters; readonly config: ApiConfig;
  constructor(store: Store, adapters: Adapters, config: ApiConfig) { this.store = store; this.adapters = adapters; this.config = config; }
  products(): Record<string, unknown> { return { enabled: this.adapters.payments.enabled, items: this.config.products }; }
  orders(user: User | null): Record<string, unknown> { const account = requireUser(user); return { items: this.store.all("SELECT id,product_id AS productId,amount_minor AS amountMinor,currency,status,refunded_minor AS refundedMinor,checkout_url AS checkoutUrl,created_at AS createdAt FROM orders WHERE user_id=? ORDER BY created_at DESC LIMIT 100", account.id) }; }
  order(user: User | null, id: string): Record<string, unknown> { const account = requireUser(user); const row = this.store.get("SELECT id,product_id AS productId,amount_minor AS amountMinor,currency,status,refunded_minor AS refundedMinor,checkout_url AS checkoutUrl,created_at AS createdAt FROM orders WHERE id=? AND user_id=?", id, account.id); check(row, 404, "RESOURCE_NOT_FOUND", "주문을 찾을 수 없습니다."); return { ...row, refundRequests: this.store.all("SELECT id AS requestId,amount_minor AS amountMinor,status FROM refund_requests WHERE order_id=?", id) }; }
  async checkout(user: User | null, value: unknown, requestId: string): Promise<Record<string, unknown>> {
    const account = requireUser(user); check(this.adapters.payments.enabled, 503, "PAYMENT_DISABLED", "결제 서비스가 아직 활성화되지 않았습니다."); const input = object(value); const product = this.config.products.find((item) => item.id === identifier(input.productId)); check(product, 404, "RESOURCE_NOT_FOUND", "판매 상품을 찾을 수 없습니다."); const key = identifier(input.idempotencyKey); let order = this.store.get("SELECT * FROM orders WHERE user_id=? AND idempotency_key=?", account.id, key);
    if (order) { check(order.product_id === product.id, 409, "IDEMPOTENCY_CONFLICT", "요청 확인값이 다른 주문에 사용되었습니다."); if (order.checkout_url) return { orderId: order.id, url: order.checkout_url, checkoutUrl: order.checkout_url, status: order.status }; check(order.status === "pending" || order.status === "unknown", 409, "ORDER_TERMINAL", "이 주문으로 새 결제를 만들 수 없습니다."); }
    else { const id = randomUUID(); const now = new Date().toISOString(); this.store.run("INSERT INTO orders (id,user_id,product_id,amount_minor,currency,status,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)", id, account.id, product.id, product.amountMinor, product.currency, "pending", key, now, now); order = this.store.get("SELECT * FROM orders WHERE id=?", id); }
    check(order, 500, "STORAGE_FAILURE", "주문을 저장하지 못했습니다."); const orderId = String(order.id);
    try { const checkout = await this.adapters.payments.createCheckout({ orderId, userId: account.id, product, successUrl: `${this.config.publicUrl}/account/?payment=return`, cancelUrl: `${this.config.publicUrl}/account/?payment=cancelled` }); this.store.run("UPDATE orders SET session_id=?,checkout_url=?,status='checkout-ready',updated_at=? WHERE id=? AND status IN ('pending','unknown')", checkout.sessionId, checkout.url, new Date().toISOString(), orderId); this.store.audit(account.id, "payment.checkout", orderId, requestId); return { orderId, url: checkout.url, checkoutUrl: checkout.url, status: "checkout-ready" }; }
    catch (error) { this.store.run("UPDATE orders SET status='unknown',updated_at=? WHERE id=? AND status='pending'", new Date().toISOString(), orderId); throw new AppError(502, "PAYMENT_OUTCOME_UNKNOWN", error instanceof AppError ? error.message : "결제 공급자 응답을 확인하지 못했습니다. 같은 주문으로 다시 확인해 주세요."); }
  }
  requestRefund(user: User | null, id: string, value: unknown, requestId: string): Record<string, unknown> {
    const account = requireUser(user); const input = object(value); const amount = version(input.amountMinor); check(amount > 0, 400, "INVALID_INPUT", "환불 금액을 확인해 주세요."); const key = identifier(input.idempotencyKey); const reason = text(input.reason, "환불 사유", 2000);
    return this.store.transaction(() => { const order = this.store.get("SELECT * FROM orders WHERE id=? AND user_id=?", id, account.id); check(order, 404, "RESOURCE_NOT_FOUND", "주문을 찾을 수 없습니다."); const existing = this.store.get("SELECT * FROM refund_requests WHERE id=?", key); if (existing) { check(existing.order_id === id && existing.amount_minor === amount, 409, "IDEMPOTENCY_CONFLICT", "다른 환불 요청에 사용된 확인값입니다."); return { requestId: key, status: existing.status, amountMinor: amount }; } const reserved = Number(this.store.get("SELECT COALESCE(sum(amount_minor),0) AS amount FROM refund_requests WHERE order_id=? AND status IN ('requested','pending','unknown')", id)?.amount); check(["paid", "partially-refunded"].includes(String(order.status)) && amount <= Number(order.amount_minor) - Number(order.refunded_minor) - reserved, 409, "REFUND_LIMIT", "환불 요청 금액이 잔액을 초과했습니다."); this.store.run("INSERT INTO refund_requests VALUES (?,?,?,?,?)", key, id, amount, "requested", null); this.store.run("INSERT INTO refund_notes VALUES (?,?,?,?)", key, reason, "", new Date().toISOString()); this.store.audit(account.id, "payment.refund_requested", id, requestId); return { requestId: key, status: "requested", amountMinor: amount }; });
  }
  refundRequests(user: User | null): Record<string, unknown> { requirePermission(user, "finance:read"); return { items: this.store.all("SELECT r.id AS requestId,r.order_id AS orderId,r.amount_minor AS amountMinor,r.status,n.reason,n.moderation_note AS moderationNote FROM refund_requests r LEFT JOIN refund_notes n ON n.request_id=r.id ORDER BY n.updated_at DESC LIMIT 500") }; }
  rejectRefund(user: User | null, id: string, value: unknown, requestId: string): Record<string, unknown> { const account = requirePermission(user, "finance:manage"); const input = object(value); const row = this.store.get("SELECT * FROM refund_requests WHERE id=?", id); check(row && row.status === "requested", 409, "INVALID_TRANSITION", "검토 대기 환불 요청만 거절할 수 있습니다."); this.store.transaction(() => { this.store.run("UPDATE refund_requests SET status='rejected' WHERE id=?", id); this.store.run("UPDATE refund_notes SET moderation_note=?,updated_at=? WHERE request_id=?", text(input.note, "검토 사유", 2000), new Date().toISOString(), id); this.store.audit(account.id, "payment.refund_rejected", String(row.order_id), requestId); }); return { requestId: id, status: "rejected" }; }
  async webhook(raw: Buffer, signature: string): Promise<Record<string, unknown>> {
    check(this.adapters.payments.enabled, 503, "PAYMENT_DISABLED", "결제 서비스가 비활성 상태입니다."); const event = await this.adapters.payments.verifyWebhook(raw, signature); if (!event) return { accepted: true, ignored: true };
    return this.applyEvent(event);
  }
  applyEvent(event: PaymentEvent): Record<string, unknown> {
    return this.store.transaction(() => {
      if (this.store.get("SELECT event_id FROM payment_events WHERE event_id=?", event.eventId)) return { accepted: true, duplicate: true };
      const order = this.store.get("SELECT * FROM orders WHERE id=?", event.orderId); check(order, 400, "ORDER_MISMATCH", "웹훅 주문을 확인할 수 없습니다.");
      check(order.amount_minor === event.amountMinor && order.currency === event.currency && (order.session_id === null || order.session_id === event.sessionId), 400, "PAYMENT_MISMATCH", "주문 금액·통화·세션이 일치하지 않습니다.");
      const refunded = event.refundedMinor ?? 0; check(Number.isSafeInteger(refunded) && refunded >= 0 && refunded <= event.amountMinor, 400, "REFUND_MISMATCH", "환불 금액을 확인할 수 없습니다.");
      let status = String(order.status); let totalRefunded = Number(order.refunded_minor);
      if (["refunded", "partially-refunded"].includes(event.status)) { totalRefunded = Math.max(totalRefunded, refunded); check(totalRefunded > 0, 400, "REFUND_MISMATCH", "확인된 환불 금액이 필요합니다."); status = totalRefunded === event.amountMinor ? "refunded" : "partially-refunded"; }
      else if (event.status === "paid") { if (!["refunded", "partially-refunded", "refund-pending"].includes(status)) status = "paid"; }
      else if (!["paid", "refunded", "partially-refunded", "refund-pending"].includes(status)) status = event.status;
      this.store.run("UPDATE orders SET status=?,session_id=COALESCE(session_id,?),refunded_minor=?,updated_at=? WHERE id=?", status, event.sessionId, totalRefunded, new Date().toISOString(), event.orderId);
      this.store.run("INSERT INTO payment_events VALUES (?,?,?,?)", event.eventId, event.orderId, event.status, new Date().toISOString()); this.store.audit(null, "payment.webhook", event.orderId, `provider:${event.eventId}`); return { accepted: true, duplicate: false };
    });
  }
  async refund(user: User | null, id: string, value: unknown, requestId: string): Promise<Record<string, unknown>> {
    const account = requirePermission(user, "finance:manage"); check(this.adapters.payments.enabled, 503, "PAYMENT_DISABLED", "결제가 비활성 상태입니다."); const input = object(value); const amount = version(input.amountMinor); check(amount > 0, 400, "INVALID_INPUT", "환불 금액을 확인해 주세요."); const key = identifier(input.idempotencyKey); const order = this.store.get("SELECT * FROM orders WHERE id=?", id); check(order && typeof order.session_id === "string", 404, "RESOURCE_NOT_FOUND", "결제 주문을 찾을 수 없습니다."); const existing = this.store.get("SELECT * FROM refund_requests WHERE id=?", key);
    if (existing) { check(existing.order_id === id && existing.amount_minor === amount, 409, "IDEMPOTENCY_CONFLICT", "같은 환불 요청의 주문·금액이 변경되었습니다."); check(existing.status !== "rejected", 409, "REFUND_REJECTED", "거절한 환불 요청은 실행할 수 없습니다."); if (existing.status === "refunded") return { refundId: existing.provider_id, status: existing.status }; this.store.run("UPDATE refund_requests SET status='pending' WHERE id=? AND status='requested'", key); }
    else this.store.transaction(() => { const pending = Number(this.store.get("SELECT COALESCE(sum(amount_minor),0) AS amount FROM refund_requests WHERE order_id=? AND status IN ('requested','pending','unknown')", id)?.amount); check(["paid", "partially-refunded"].includes(String(order.status)) && amount <= Number(order.amount_minor) - Number(order.refunded_minor) - pending, 409, "REFUND_LIMIT", "환불할 수 있는 잔액을 초과했습니다."); this.store.run("INSERT INTO refund_requests VALUES (?,?,?,?,?)", key, id, amount, "pending", null); });
    try { const result = await this.adapters.payments.refund({ orderId: id, sessionId: order.session_id as string, amountMinor: amount, idempotencyKey: key }); const confirmed = result.status === "refunded" && result.refundedMinor !== undefined; this.store.transaction(() => { this.store.run("UPDATE refund_requests SET status=?,provider_id=? WHERE id=? AND order_id=?", confirmed ? "refunded" : "pending", result.refundId, key, id); if (confirmed) { const current = this.store.get("SELECT * FROM orders WHERE id=?", id); check(Number.isSafeInteger(result.refundedMinor) && Number(result.refundedMinor) >= amount && Number(result.refundedMinor) <= Number(current?.amount_minor), 502, "REFUND_LIMIT", "공급자 환불 누계를 확인하지 못했습니다."); const refunded = Math.max(Number(current?.refunded_minor), Number(result.refundedMinor)); this.store.run("UPDATE orders SET refunded_minor=?,status=?,updated_at=? WHERE id=?", refunded, refunded === Number(current?.amount_minor) ? "refunded" : "partially-refunded", new Date().toISOString(), id); } this.store.audit(account.id, "payment.refund", id, requestId); }); return { ...result, status: confirmed ? "refunded" : "pending" }; }
    catch { this.store.run("UPDATE refund_requests SET status='unknown' WHERE id=? AND order_id=? AND status='pending'", key, id); throw new AppError(502, "REFUND_OUTCOME_UNKNOWN", "환불 공급자 응답을 확인하지 못했습니다. 같은 요청으로 확인해 주세요."); }
  }
}
