import { randomUUID } from "node:crypto";
import type { ArchiveRecord } from "../../../web/lib/archive-types.ts";
import { Store, hash } from "../infrastructure/database.ts";
import { requireRole, type User } from "./auth.ts";
import { object, text, version, optionalText, email, identifier, httpsUrl } from "../domain/validation.ts";
import { check } from "../domain/errors.ts";
import { publicRecord, checkedPublicRecord } from "../domain/archive.ts";
import { enqueue } from "./jobs.ts";
import type { Adapters } from "../adapters/contracts.ts";
import type { ApiConfig } from '../config.ts';
import { preflight } from './operations.ts';
import { recoveryEvent } from './security.ts';
import { requirePermission,permissions } from '../domain/permissions.ts';
type DraftModel = { id: string; recordId: string; version: number; state: string; record: ArchiveRecord; contentHash: string; approvedHash: string | null; updatedAt: string; privateNotes: string };
export class EditorialService {
  readonly store: Store; readonly adapters: Adapters;readonly config?:ApiConfig;
  constructor(store: Store, adapters: Adapters,config?:ApiConfig) { this.store = store; this.adapters = adapters;this.config=config; }
  draft(user: User | null, id: string): DraftModel {
    requirePermission(user,'content:read'); const row = this.store.get("SELECT * FROM drafts WHERE id=?", id); check(row, 404, "RESOURCE_NOT_FOUND", "초안을 찾을 수 없습니다.");
    return { id, recordId: String(row.record_id), version: Number(row.version), state: String(row.state), record: publicRecord(JSON.parse(String(row.payload)) as unknown), contentHash: String(row.content_hash), approvedHash: row.approved_hash === null ? null : String(row.approved_hash), updatedAt: String(row.updated_at), privateNotes: String(this.store.get("SELECT note FROM draft_private_notes WHERE draft_id=?", id)?.note || "") };
  }
  drafts(user: User | null): { items: DraftModel[] } { requirePermission(user, "content:read"); return { items: this.store.all("SELECT id FROM drafts ORDER BY updated_at DESC LIMIT 500").map((row) => this.draft(user, String(row.id))) }; }
  save(user: User | null, id: string | null, value: unknown, requestId: string): DraftModel {
    const account = requirePermission(user,'content:write'); const input = object(value); const raw = object(input.record);
    const now = new Date().toISOString(); const record = publicRecord({ ...raw, review: { status: "needs-review", reviewer: "검수 대기", reviewedAt: now, note: "초안은 공개되지 않습니다.", humanReviewed: false }, updatedAt: now });
    check(Buffer.byteLength(JSON.stringify(record)) <= 262144, 413, "PAYLOAD_TOO_LARGE", "초안 크기가 허용 범위를 초과했습니다."); const contentHash = hash(JSON.stringify(record)); const draftId = id || randomUUID();
    this.store.transaction(() => {
      if (id) { const current = this.store.get("SELECT * FROM drafts WHERE id=?", id); check(current, 404, "RESOURCE_NOT_FOUND", "초안을 찾을 수 없습니다."); check(current.record_id === record.id, 400, "RECORD_ID_IMMUTABLE", "기록 ID는 변경할 수 없습니다."); check(current.version === version(input.version), 409, "VERSION_CONFLICT", "초안의 최신 버전을 다시 불러와 주세요."); this.store.run("UPDATE drafts SET version=version+1,author_id=?,state='draft',payload=?,content_hash=?,approved_hash=NULL,approved_by=NULL,updated_at=? WHERE id=?", account.id, JSON.stringify(record), contentHash, now, id); }
      else { check(!this.store.get("SELECT id FROM drafts WHERE record_id=?", record.id), 409, "DRAFT_EXISTS", "이 기록의 초안이 이미 있습니다."); this.store.run("INSERT INTO drafts VALUES (?,?,?,?,?,?,?,?,?,?)", draftId, record.id, account.id, 1, "draft", JSON.stringify(record), contentHash, null, null, now); }
      if (input.privateNotes !== undefined) this.store.run("INSERT INTO draft_private_notes VALUES (?,?,?) ON CONFLICT(draft_id) DO UPDATE SET note=excluded.note,updated_at=excluded.updated_at", draftId, optionalText(input.privateNotes, "비공개 편집 메모", 10000), now);
      this.remember(draftId, account.id);
      this.store.audit(account.id, id ? "cms.draft_update" : "cms.draft_create", draftId, requestId);
    }); return this.draft(account, draftId);
  }
  transition(user: User | null, id: string, action: string, value: unknown, requestId: string): DraftModel | Record<string, unknown> {
    const account = requirePermission(user, action === 'submit'?'content:write':action==='publish'?'content:publish':'content:review'); const input = object(value); const expected = version(input.version);
    return this.store.transaction(() => {
      const row = this.store.get("SELECT * FROM drafts WHERE id=?", id); check(row, 404, "RESOURCE_NOT_FOUND", "초안을 찾을 수 없습니다."); check(row.version === expected, 409, "VERSION_CONFLICT", "초안 버전이 변경되었습니다.");
      let knowledge:Record<string,unknown>|null=null;if(this.config?.knowledgeFile&&['source-check','approve','publish'].includes(action)){knowledge=preflight(this.store,this.config,id);check(knowledge.ready,409,'KNOWLEDGE_PREFLIGHT_FAILED','지식·출처 연결의 영향 검토가 필요합니다.');if(action==='publish'){const approved=this.store.get('SELECT registry_hash FROM draft_knowledge_checks WHERE draft_id=? AND revision=? AND content_hash=?',id,expected,String(row.content_hash));check(approved?.registry_hash===knowledge.registryHash,409,'KNOWLEDGE_APPROVAL_STALE','승인 이후 지식 레지스트리가 변경되었습니다.');}}
      if (action === "publish") { check(row.state === "approved" && row.approved_hash === row.content_hash && typeof row.approved_by === "string", 409, "APPROVAL_REQUIRED", "현재 버전에 대한 실제 검수 승인이 필요합니다."); const jobId = enqueue(this.store, "publish", `publish:${id}:${String(row.content_hash)}`, { draftId: id, contentHash: row.content_hash }); this.store.audit(account.id, "cms.publish_requested", id, requestId); return { jobId, status: "pending" }; }
      const record = publicRecord(JSON.parse(String(row.payload)) as unknown); let state: string;
      const note = action === "submit" ? "검수 요청" : text(input.note, "검수 사유", 2000);
      if (action === "submit") { check(["draft", "rejected"].includes(String(row.state)), 409, "INVALID_TRANSITION", "이 상태에서 제출할 수 없습니다."); state = "submitted"; }
      else if (action === "source-check") { check(row.state === "submitted", 409, "INVALID_TRANSITION", "제출된 초안만 출처 대조할 수 있습니다."); checkedPublicRecord({ ...record, review: { ...record.review, status: "source-checked" } }); state = "source-checked"; record.review = { status: "source-checked", reviewer: account.name, reviewedAt: new Date().toISOString(), note: "출처를 대조했으며 최종 인적 승인을 기다립니다.", humanReviewed: false }; }
      else if (action === "approve") { check(row.state === "source-checked" && row.author_id !== account.id, 409, "INDEPENDENT_REVIEW_REQUIRED", "작성자와 다른 검수자의 출처 대조 후 승인이 필요합니다."); check(input.contentHash === row.content_hash, 409, "APPROVAL_STALE", "승인 대상 자료가 변경되었습니다."); state = "approved"; record.review = { status: "approved", reviewer: account.name, reviewedAt: new Date().toISOString(), note: "인증된 검수자가 이 기록의 현재 버전을 승인했습니다.", humanReviewed: true }; checkedPublicRecord(record); }
      else if (action === "reject" || action === "withhold") { state = action === "reject" ? "rejected" : "withheld"; record.review = { status: action === "reject" ? "needs-review" : "withheld", reviewer: account.name, reviewedAt: new Date().toISOString(), note: action === "reject" ? "검수에서 수정이 요청되었습니다." : "공개가 보류되었습니다.", humanReviewed: false }; if (action === "withhold") { this.store.run("DELETE FROM public_records WHERE record_id=?", record.id); this.store.run("INSERT INTO publication_withheld VALUES (?,?,?) ON CONFLICT(record_id) DO UPDATE SET withheld_at=excluded.withheld_at,reviewer_id=excluded.reviewer_id", record.id, new Date().toISOString(), account.id);recoveryEvent(this.store,'withhold',record.id,{reviewerId:account.id}); enqueue(this.store, "export", `withhold:${id}:${expected}`, {}); } }
      else { check(false, 400, "INVALID_TRANSITION", "편집 작업을 확인해 주세요."); }
      const contentHash = hash(JSON.stringify(record));
      this.store.run("UPDATE drafts SET version=version+1,state=?,payload=?,content_hash=?,approved_hash=?,approved_by=?,updated_at=? WHERE id=?", state, JSON.stringify(record), contentHash, state === "approved" ? contentHash : null, state === "approved" ? account.id : null, new Date().toISOString(), id);
      if(knowledge&&state==='approved')this.store.run('INSERT INTO draft_knowledge_checks VALUES (?,?,?,?,?) ON CONFLICT(draft_id) DO UPDATE SET revision=excluded.revision,registry_hash=excluded.registry_hash,content_hash=excluded.content_hash,checked_at=excluded.checked_at',id,expected+1,String(knowledge.registryHash),contentHash,new Date().toISOString());
      this.remember(id, account.id);
      this.store.run("INSERT INTO draft_reviews VALUES (?,?,?,?,?,?,?)", randomUUID(), id, account.id, action, String(row.content_hash), note, new Date().toISOString()); this.store.audit(account.id, `cms.${action}`, id, requestId); return this.draft(account, id);
    });
  }
  importStatic(user: User | null, value: unknown, requestId: string): Record<string, unknown> {
    const account = requireRole(user, []); check(account.role === "admin", 403, "FORBIDDEN", "관리자 권한이 필요합니다."); return this.applyStatic(value, account.id, requestId);
  }
  /** Startup-only trusted local file path. No HTTP route exposes this entry point. */
  importTrustedLocalSnapshot(value: unknown, requestId: string): Record<string, unknown> { return this.applyStatic(value, null, requestId); }
  private applyStatic(value: unknown, actorId: string | null, requestId: string): Record<string, unknown> {
    const input = object(value); check(input.version === 1 && Array.isArray(input.records) && input.records.length <= 10000, 400, "INVALID_INPUT", "공개 산출물 형식을 확인해 주세요."); const records = input.records.map(checkedPublicRecord); check(records.every((record) => record.review.status === "source-checked" && !record.review.humanReviewed), 400, "STATIC_APPROVAL_UNTRUSTED", "정적 수입으로 인적 승인 이력을 만들 수 없습니다."); check(new Set(records.map((record) => record.id)).size === records.length, 400, "DUPLICATE_RECORD", "중복 기록 ID가 있습니다.");
    let imported = 0;
    this.store.transaction(() => { for (const record of records) { const contentHash = hash(JSON.stringify(record)); const existing = this.store.get("SELECT origin,content_hash FROM public_records WHERE record_id=?", record.id); if (existing?.origin === "cms" || existing?.content_hash === contentHash || this.store.get("SELECT record_id FROM publication_withheld WHERE record_id=?", record.id)) continue; this.store.run("INSERT INTO public_records VALUES (?,?,?,?,?) ON CONFLICT(record_id) DO UPDATE SET payload=excluded.payload,content_hash=excluded.content_hash,updated_at=excluded.updated_at", record.id, JSON.stringify(record), contentHash, "static", new Date().toISOString()); imported++; } this.store.audit(actorId, actorId ? "cms.static_import" : "system.static_snapshot", null, requestId); }); return { imported, skipped: records.length - imported };
  }
  remember(id: string, actorId: string): void { const row = this.store.get("SELECT * FROM drafts WHERE id=?", id); check(row, 500, "STORAGE_FAILURE", "초안 이력을 확인하지 못했습니다."); this.store.run("INSERT OR IGNORE INTO draft_revisions VALUES (?,?,?,?,?,?,?,?)", id, Number(row.version), String(row.payload), String(row.content_hash), String(row.state), actorId, String(this.store.get("SELECT note FROM draft_private_notes WHERE draft_id=?", id)?.note || ""), new Date().toISOString()); }
  revisions(user: User | null, id: string): Record<string, unknown> { this.draft(user, id); return { items: this.store.all("SELECT version,payload,content_hash AS contentHash,state,changed_by AS changedBy,created_at AS createdAt FROM draft_revisions WHERE draft_id=? ORDER BY version DESC", id).map((row) => ({ ...row, record: publicRecord(JSON.parse(String(row.payload)) as unknown), payload: undefined })) }; }
  restore(user: User | null, id: string, value: unknown, requestId: string): DraftModel { const input = object(value); const row = this.store.get("SELECT * FROM draft_revisions WHERE draft_id=? AND version=?", id, version(input.revision)); check(row, 404, "RESOURCE_NOT_FOUND", "이전 초안 버전을 찾을 수 없습니다."); return this.save(user, id, { version: version(input.version), record: JSON.parse(String(row.payload)) as unknown, privateNotes: String(row.private_notes) }, requestId); }
  publicRecords(): ArchiveRecord[] { return this.store.all("SELECT payload FROM public_records ORDER BY record_id").map((row) => checkedPublicRecord(JSON.parse(String(row.payload)) as unknown)); }
  publicRecordById(id: string): ArchiveRecord { const row = this.store.get("SELECT payload FROM public_records WHERE record_id=?", id); check(row, 404, "RESOURCE_NOT_FOUND", "공개 기록을 찾을 수 없습니다."); return checkedPublicRecord(JSON.parse(String(row.payload)) as unknown); }
  publicRecordsByIds(recordIds: string[]): ArchiveRecord[] { if (!recordIds.length) return []; return this.store.all(`SELECT payload FROM public_records WHERE record_id IN (${recordIds.map(() => "?").join(",")}) ORDER BY record_id`, ...recordIds).map((row) => checkedPublicRecord(JSON.parse(String(row.payload)) as unknown)); }
  publicPage(page: number, limit: number): Record<string, unknown> { check(Number.isInteger(page) && page >= 1 && page <= 1000000 && Number.isInteger(limit) && limit >= 1 && limit <= 100, 400, "INVALID_INPUT", "목록 범위를 확인해 주세요."); return { version: 1, items: this.store.all("SELECT payload FROM public_records ORDER BY record_id LIMIT ? OFFSET ?", limit, (page - 1) * limit).map((row) => checkedPublicRecord(JSON.parse(String(row.payload)) as unknown)), total: Number(this.store.get("SELECT count(*) AS count FROM public_records")?.count), page, limit }; }
  correction(user: User | null, value: unknown, requestId: string): Record<string, unknown> {
    const input = object(value); check(input.consent === true, 400, "CONSENT_REQUIRED", "검토를 위한 자료 보관에 동의해 주세요."); const recordId = identifier(input.recordId); check(this.store.get("SELECT record_id FROM public_records WHERE record_id=?", recordId), 404, "RESOURCE_NOT_FOUND", "공개 기록을 찾을 수 없습니다."); const category = text(input.category, "분류", 100); const proposal = text(input.proposal, "정정 제안", 10000); const evidenceUrl = input.evidenceUrl ? httpsUrl(input.evidenceUrl, "근거 주소", true) : ""; const contact = input.contactEmail ? email(input.contactEmail) : null; const id = randomUUID(); const now = new Date().toISOString();
    this.store.transaction(() => { this.store.run("INSERT INTO corrections VALUES (?,?,?,?,?,?,?,?,?,?,?)", id, user?.id ?? null, recordId, category, proposal, evidenceUrl, contact, "received", "", now, now); this.store.audit(user?.id ?? null, "correction.received", id, requestId); if (this.adapters.notifications.enabled) enqueue(this.store, "notification", `correction:${id}:received`, { event: "correction_received", ...(contact ? { recipient: contact } : {}), data: { receiptId: id, recordId } }); }); return { receiptId: id, status: "received", createdAt: now };
  }
  corrections(user: User | null): { items: Record<string, unknown>[] } { check(user, 401, "AUTH_REQUIRED", "로그인이 필요합니다."); const staff = permissions(user).includes('content:read'); return { items: this.store.all(`SELECT c.*,cl.revision,cl.publication_id,cl.evidence AS closure_evidence FROM corrections c LEFT JOIN correction_closure_evidence cl ON cl.correction_id=c.id${staff ? "" : " WHERE c.user_id=?"} ORDER BY c.created_at DESC LIMIT 500`, ...staff ? [] : [user.id]).map((row) => ({ receiptId: row.id, recordId: row.record_id, category: row.category, proposal: row.proposal, evidenceUrl: row.evidence_url, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at,revision:row.revision??null,publicationId:row.publication_id??null,closureEvidence:row.closure_evidence??null, ...(staff ? { contactEmail: row.contact_email, moderationNote: row.moderation_note } : {}) })) }; }
  receipt(id: string): Record<string, unknown> { const row = this.store.get("SELECT id,status,updated_at FROM corrections WHERE id=?", id); check(row, 404, "RESOURCE_NOT_FOUND", "접수 기록을 찾을 수 없습니다."); return { receiptId: row.id, status: row.status, updatedAt: row.updated_at }; }
  moderate(user: User | null, id: string, value: unknown, requestId: string): Record<string, unknown> {
    const account=requirePermission(user,'content:review'),input=object(value);check(['triaged','accepted','rejected','resolved'].includes(String(input.status)),400,'INVALID_INPUT','처리 상태를 확인해 주세요.');const note=text(input.note,'처리 사유',2000);
    this.store.transaction(()=>{const row=this.store.get('SELECT * FROM corrections WHERE id=?',id);check(row,404,'RESOURCE_NOT_FOUND','접수 기록을 찾을 수 없습니다.');check(!['resolved','rejected'].includes(String(row.status)),409,'INVALID_TRANSITION','완료된 접수 기록은 변경할 수 없습니다.');if(input.status==='resolved'){check(row.status==='accepted',409,'INVALID_TRANSITION','제안을 먼저 수락해 주세요.');const revision=version(input.revision),publicationId=identifier(input.publicationId),evidence=text(input.closureEvidence,'반영 완료 근거',5000);const deployed=this.store.get("SELECT * FROM publication_stage_evidence WHERE id=? AND record_id=? AND revision=? AND stage IN ('deploy','feed')",publicationId,String(row.record_id),revision),current=this.store.get('SELECT content_hash FROM public_records WHERE record_id=?',String(row.record_id));check(deployed&&current?.content_hash===deployed.content_hash&&!this.store.get('SELECT record_id FROM publication_withheld WHERE record_id=?',String(row.record_id)),409,'DEPLOYMENT_EVIDENCE_REQUIRED','현재 공개 버전의 실제 배포·피드 검증 증거가 필요합니다.');const closureTable=this.store.get('SELECT id FROM publication_release_stages WHERE id=?',publicationId)?'correction_release_closures':'correction_closures';this.store.run(`INSERT INTO ${closureTable} VALUES (?,?,?,?,?,?)`,id,revision,publicationId,evidence,account.id,new Date().toISOString());}this.store.run('UPDATE corrections SET status=?,moderation_note=?,updated_at=? WHERE id=?',String(input.status),note,new Date().toISOString(),id);this.store.audit(account.id,'correction.moderate',id,requestId);if(this.adapters.notifications.enabled&&typeof row.contact_email==='string')enqueue(this.store,'notification',`correction:${id}:${String(input.status)}`,{event:'correction_updated',recipient:row.contact_email,data:{receiptId:id,status:input.status}});});return this.receipt(id);
  }
}
