import { randomUUID } from "node:crypto";
import { Store } from "../infrastructure/database.ts";
import { requireRole, type User } from "./auth.ts";
import { check } from "../domain/errors.ts";
import { object, text, version, identifier, isoDate, httpsUrl } from "../domain/validation.ts";
import { publicRecord } from "../domain/archive.ts";
import { requirePermission } from '../domain/permissions.ts';
type Resource = "organizations" | "rights" | "contracts";
function model(row: Record<string, unknown>): Record<string, unknown> { const result: Record<string, unknown> = {}; for (const [key, value] of Object.entries(row)) result[key.replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase())] = value; return result; }
export class InstitutionService {
  readonly store: Store;
  constructor(store: Store) { this.store = store; }
  list(user: User | null, resource: Resource): { items: Record<string, unknown>[] } { if(user?.scopes)requirePermission(user,'rights:manage');else requireRole(user,["editor","reviewer"]); return { items: this.store.all(`SELECT * FROM ${resource} ORDER BY updated_at DESC LIMIT 500`).map((row) => resource === "contracts" ? { ...model(row), ...this.contractReadiness(row) } : resource==='rights'?{...model(row),...this.rightDetails(String(row.id))}:model(row)) }; }
  approver(account:User):User {return account.scopes?requirePermission(account,'rights:manage'):requireRole(account,['reviewer']);}
  rightDetails(id:string):Record<string,unknown>{const row=this.store.get('SELECT * FROM rights_details WHERE rights_id=?',id);return {permissions:row?JSON.parse(String(row.permissions)) as unknown:[],territory:String(row?.territory||''),startsAt:row?.starts_at||null,attribution:String(row?.attribution||''),documentId:row?.document_id||null,scopeVerified:Boolean(row?.document_id && this.store.get("SELECT attachment_id FROM attachment_scans WHERE attachment_id=? AND status='clean'",String(row.document_id)))};}
  contractReadiness(row:Record<string,unknown>):Record<string,unknown>{
    const blockers:string[]=[],now=new Date().toISOString(),details=this.store.get('SELECT * FROM contract_details WHERE contract_id=?',String(row.id)),requiredRightsIds=details?JSON.parse(String(details.required_rights_ids)) as string[]:[],requiredPermissions=details?JSON.parse(String(details.required_permissions)) as string[]:[],territory=String(details?.territory||'');
    if(row.status!=='active')blockers.push('contract-inactive');if(this.store.get('SELECT status FROM organizations WHERE id=?',String(row.organization_id))?.status!=='active')blockers.push('organization-inactive');
    const rights=this.store.all("SELECT r.id,r.status,r.expires_at,d.starts_at,d.permissions,d.territory,d.document_id,s.status AS scan_status FROM rights r LEFT JOIN rights_details d ON d.rights_id=r.id LEFT JOIN attachment_scans s ON s.attachment_id=d.document_id WHERE r.organization_id=? ORDER BY r.id LIMIT 500",String(row.organization_id));
    const valid=(right:Record<string,unknown>):boolean=>right.status==='granted'&&(!right.expires_at||String(right.expires_at)>now)&&(!right.starts_at||String(right.starts_at)<=now)&&(!right.permissions||String(right.permissions)==='[]'||right.scan_status==='clean');
    if(!rights.some(valid))blockers.push('rights-unavailable');
    const scoped=requiredRightsIds.length>0&&requiredPermissions.length>0&&territory.length>0;if(requiredRightsIds.length||requiredPermissions.length||territory){if(!scoped)blockers.push('rights-scope-incomplete');for(const id of requiredRightsIds){const right=rights.find(r=>r.id===id),permissions=right?.permissions?JSON.parse(String(right.permissions)) as string[]:[];if(!right||!valid(right)||right.territory!==territory||!right.document_id||right.scan_status!=='clean'||!requiredPermissions.every(p=>permissions.includes(p)))blockers.push(`rights-scope-unavailable:${id}`);}}
    if(typeof row.starts_at==='string'&&row.starts_at>now)blockers.push('term-not-started');if(typeof row.ends_at==='string'&&row.ends_at<=now)blockers.push('term-ended');return {operationallyReady:blockers.length===0,scopeVerified:scoped&&blockers.length===0,coverageStatus:!scoped?'legacy-unspecified':blockers.length?'blocked':'verified',requiredRightsIds,requiredPermissions,territory,blockers};
  }
  save(user: User | null, resource: Resource, id: string | null, value: unknown, requestId: string): Record<string, unknown> {
    const account = user?.scopes?requirePermission(user,'rights:manage'):requireRole(user, ["editor", "reviewer"]); const input = object(value); const targetId = id || randomUUID(); const now = new Date().toISOString();
    let values: (string | number | null)[]; let columns: string[];
    if (resource === "organizations") {
      check(["prospect", "active", "suspended"].includes(String(input.status)), 400, "INVALID_INPUT", "기관 상태를 확인해 주세요."); if (input.status === "active") this.approver(account);
      const website = input.website ? httpsUrl(input.website, "기관 주소") : "";
      columns = ["title", "website", "status"]; values = [text(input.title, "기관명", 200), website, String(input.status)];
    } else {
      const organizationId = identifier(input.organizationId); const organization = this.store.get("SELECT * FROM organizations WHERE id=?", organizationId); check(organization, 404, "RESOURCE_NOT_FOUND", "기관을 찾을 수 없습니다.");
      if (resource === "rights") {
        check(["requested", "granted", "expired", "withdrawn"].includes(String(input.status)), 400, "INVALID_INPUT", "사용권 상태를 확인해 주세요."); if (["granted", "withdrawn"].includes(String(input.status))) this.approver(account);
        if (input.status === "granted") { check(organization.status === "active", 409, "ORGANIZATION_INACTIVE", "활성 기관의 사용권만 승인할 수 있습니다."); const recordId = identifier(input.recordId); const sourceId = identifier(input.sourceId); const stored = this.store.get("SELECT payload FROM public_records WHERE record_id=?", recordId) || this.store.get("SELECT payload FROM drafts WHERE record_id=?", recordId); check(stored, 404, "RESOURCE_NOT_FOUND", "사용권에 연결할 기록을 찾을 수 없습니다."); const record = publicRecord(JSON.parse(String(stored.payload)) as unknown); check(record.sources.some((source) => source.id === sourceId), 400, "SOURCE_MISMATCH", "사용권의 출처가 이 기록에 연결되어 있지 않습니다."); }
        const expiresAt = input.expiresAt ? isoDate(input.expiresAt) : null; if (input.status === "granted" && expiresAt) check(Date.parse(expiresAt) > Date.now(), 400, "RIGHTS_EXPIRED", "사용권 기한이 지났습니다.");
        columns = ["organization_id", "record_id", "source_id", "usage", "status", "expires_at", "note"]; values = [organizationId, identifier(input.recordId), identifier(input.sourceId), text(input.usage, "사용 범위", 2000), String(input.status), expiresAt, text(input.note, "허가 근거", 5000)];
      } else {
        check(["draft", "review", "active", "ended", "revoked"].includes(String(input.status)), 400, "INVALID_INPUT", "계약 상태를 확인해 주세요."); if (["active", "revoked"].includes(String(input.status))) this.approver(account);
        const startsAt = input.startsAt ? isoDate(input.startsAt) : null; const endsAt = input.endsAt ? isoDate(input.endsAt) : null; check(!startsAt || !endsAt || startsAt < endsAt, 400, "INVALID_INPUT", "계약 기간을 확인해 주세요.");
        if (input.status === "active") { check(organization.status === "active", 409, "ORGANIZATION_INACTIVE", "기관이 활성 상태여야 합니다."); check(this.store.get("SELECT id FROM rights WHERE organization_id=? AND status='granted' AND (expires_at IS NULL OR expires_at>?) LIMIT 1", organizationId, now), 409, "RIGHTS_REQUIRED", "현재 유효한 사용권을 먼저 등록해 주세요."); }
        columns = ["organization_id", "title", "status", "starts_at", "ends_at", "note"]; values = [organizationId, text(input.title, "계약명", 200), String(input.status), startsAt, endsAt, text(input.note, "계약 근거", 5000)];
      }
    }
    this.store.transaction(() => {
      if (id) { const current = this.store.get(`SELECT version FROM ${resource} WHERE id=?`, id); check(current, 404, "RESOURCE_NOT_FOUND", "자료를 찾을 수 없습니다."); const expected = version(input.version); check(current.version === expected, 409, "VERSION_CONFLICT", "자료의 최신 버전을 다시 불러와 주세요."); this.store.run(`UPDATE ${resource} SET ${columns.map((column) => `${column}=?`).join(",")},version=version+1,updated_at=? WHERE id=?`, ...values, now, id); }
      else { const fields = ["id", ...(resource === "organizations" ? ["owner_id"] : []), ...columns, "version", "updated_at"]; this.store.run(`INSERT INTO ${resource} (${fields.join(",")}) VALUES (${fields.map(() => "?").join(",")})`, targetId, ...(resource === "organizations" ? [account.id] : []), ...values, 1, now); }
      this.store.audit(account.id, `${resource}.${id ? "update" : "create"}`, targetId, requestId);
      if(resource==='contracts'){
        const previous=id?this.store.get('SELECT * FROM contract_details WHERE contract_id=?',id):undefined,requiredRightsIds=input.requiredRightsIds??(previous?JSON.parse(String(previous.required_rights_ids)) as unknown:[]),requiredPermissions=input.requiredPermissions??(previous?JSON.parse(String(previous.required_permissions)) as unknown:[]),territory=input.territory===undefined?String(previous?.territory||''):text(input.territory,'계약 지역',200,0);
        check(Array.isArray(requiredRightsIds)&&requiredRightsIds.length<=100&&new Set(requiredRightsIds).size===requiredRightsIds.length&&Array.isArray(requiredPermissions)&&requiredPermissions.length<=6&&requiredPermissions.every(p=>['display','download','teaching','commercial','translation','adaptation'].includes(String(p))),400,'INVALID_INPUT','계약 권리 범위를 확인해 주세요.');const rightsIds=requiredRightsIds.map(identifier);this.store.run('INSERT INTO contract_details VALUES (?,?,?,?) ON CONFLICT(contract_id) DO UPDATE SET required_rights_ids=excluded.required_rights_ids,required_permissions=excluded.required_permissions,territory=excluded.territory',targetId,JSON.stringify(rightsIds),JSON.stringify(requiredPermissions),territory);if(input.status==='active'){const current=this.store.get('SELECT * FROM contracts WHERE id=?',targetId);check(current&&this.contractReadiness(current).operationallyReady,409,'RIGHTS_SCOPE_REQUIRED','계약 범위의 실제 사용권과 검사 문서가 필요합니다.');}
      }
      if(resource==='rights'){
        const previous=id?this.store.get('SELECT * FROM rights_details WHERE rights_id=?',id):undefined;const permissions=input.permissions??(previous?JSON.parse(String(previous.permissions)) as unknown:[]);check(Array.isArray(permissions)&&permissions.length<=10&&permissions.every(p=>['display','download','teaching','commercial','translation','adaptation'].includes(String(p)))&&new Set(permissions).size===permissions.length,400,'INVALID_INPUT','사용권 세부 범위를 확인해 주세요.');const territory=input.territory===undefined?String(previous?.territory||''):input.territory?text(input.territory,'허용 지역',200):'',startsAt=input.startsAt===undefined?previous?.starts_at as string|null ?? null:input.startsAt?isoDate(input.startsAt):null,attribution=input.attribution===undefined?String(previous?.attribution||''):input.attribution?text(input.attribution,'저작자 표시',2000):'',documentId=input.documentId===undefined?previous?.document_id as string|null ?? null:input.documentId?identifier(input.documentId):null;
        check(!startsAt||!input.expiresAt||startsAt<isoDate(input.expiresAt),400,'INVALID_INPUT','사용권 기간을 확인해 주세요.');if(documentId){const document=this.store.get('SELECT record_id,source_id FROM attachments WHERE id=?',documentId);check(document&&document.record_id===input.recordId&&document.source_id===input.sourceId,400,'SOURCE_MISMATCH','권리 문서는 같은 기록·출처에 연결되어야 합니다.');}if(input.status==='granted'&&permissions.length){check(documentId&&territory&&attribution,400,'RIGHTS_DOCUMENT_REQUIRED','세부 허가의 문서·지역·저작자 표시가 필요합니다.');check(this.store.get("SELECT attachment_id FROM attachment_scans WHERE attachment_id=? AND status='clean'",documentId),409,'FILE_SCAN_REQUIRED','권리 문서의 실제 보안 검사 증거가 필요합니다.');}this.store.run('INSERT INTO rights_details VALUES (?,?,?,?,?,?) ON CONFLICT(rights_id) DO UPDATE SET permissions=excluded.permissions,territory=excluded.territory,starts_at=excluded.starts_at,attribution=excluded.attribution,document_id=excluded.document_id',targetId,JSON.stringify(permissions),territory,startsAt,attribution,documentId);
      }
    }); const saved = this.store.get(`SELECT * FROM ${resource} WHERE id=?`, targetId); check(saved, 500, "STORAGE_FAILURE", "자료 저장을 확인할 수 없습니다."); return resource === "contracts" ? { ...model(saved), ...this.contractReadiness(saved) } : resource==='rights'?{...model(saved),...this.rightDetails(targetId)}:model(saved);
  }
}
