import { createHmac,randomUUID,timingSafeEqual } from 'node:crypto';
import { readFileSync,lstatSync } from 'node:fs';
import { Store,hash } from '../infrastructure/database.ts';
import type { ApiConfig } from '../config.ts';
import type { User } from './auth.ts';
import { requireUser } from './auth.ts';
import { requirePermission,permissions,type Scope } from '../domain/permissions.ts';
import { check } from '../domain/errors.ts';
import { object,text,identifier,version,isoDate,httpsUrl } from '../domain/validation.ts';
import { publicRecord } from '../domain/archive.ts';
export function preflight(store:Store,config:ApiConfig,draftId:string):Record<string,unknown>{
 const draft=store.get('SELECT * FROM drafts WHERE id=?',draftId);check(draft,404,'RESOURCE_NOT_FOUND','초안을 찾을 수 없습니다.');const record=publicRecord(JSON.parse(String(draft.payload)) as unknown),issues:{code:string;message:string}[]=[],sourceIds=record.sources.map(s=>s.id),affectedKnowledgeIds:string[]=[];let registryHash:string|null=null;
 if(config.knowledgeFile){
  const info=lstatSync(config.knowledgeFile);check(info.isFile()&&!info.isSymbolicLink()&&info.size<=10*1024*1024,500,'KNOWLEDGE_INVALID','지식 레지스트리 파일이 안전하지 않습니다.');const raw=readFileSync(config.knowledgeFile,'utf8'),registry=object(JSON.parse(raw) as unknown);check(registry.version===1,500,'KNOWLEDGE_INVALID','지식 레지스트리 버전을 확인해 주세요.');registryHash=hash(raw);
  const registered=Array.isArray(registry.sources)?registry.sources.map(object):[];
  for(const source of record.sources){const reference=registered.find(item=>item.id===source.id);if(!reference || reference.url!==source.url || reference.title!==source.title || reference.creator!==source.creator || reference.kind!==source.kind || reference.provenanceGroup!==source.independenceGroup)issues.push({code:'SOURCE_IDENTITY_CHANGED',message:`${source.id} 서지 제목·URL을 함께 검수해야 합니다.`});}
  for(const [section,entries] of Object.entries(registry)){if(!Array.isArray(entries))continue;for(const value of entries){const item=object(value);const evidence=Array.isArray(item.evidence)?item.evidence.map(object):[];const linked=item.recordId===record.id||Array.isArray(item.recordIds)&&item.recordIds.includes(record.id)||typeof item.sourceId==='string'&&sourceIds.includes(item.sourceId)||section==='sources'&&sourceIds.includes(String(item.id))||evidence.some(ref=>sourceIds.includes(String(ref.sourceId)));if(!linked)continue;affectedKnowledgeIds.push(`${section}:${String(item.id||item.recordId)}`);
   if(item.recordId===record.id&&item.sourceIdentity){const identity=object(item.sourceIdentity);if(identity.title!==record.title||identity.summary!==record.summary)issues.push({code:'LOCALIZATION_STALE',message:`${String(item.locale)} 언어판 원본 제목·요약이 변경되었습니다.`});}
   if(section==='recordLinks'&&item.recordId===record.id&&Array.isArray(item.sourceIds))for(const ref of item.sourceIds){if(typeof ref==='string'&&!sourceIds.includes(ref))issues.push({code:'KNOWLEDGE_SOURCE_MISSING',message:`${ref} 기록 연결을 함께 수정해야 합니다.`});}
  }}
 }else issues.push({code:'KNOWLEDGE_UNCONFIGURED',message:'지식 레지스트리 대조가 설정되지 않았습니다.'});
 return {recordId:record.id,revision:Number(draft.version),contentHash:String(draft.content_hash),registryHash,ready:issues.length===0,issues,impact:{sourceIds,affectedKnowledgeIds:[...new Set(affectedKnowledgeIds)]}};
}
export function addPublicationStage(store:Store,value:{recordId:string;revision:number;contentHash:string;stage:'export'|'build'|'deploy'|'feed';commitSha?:string;artifactHash:string;url?:string;observedAt:string;evidenceSource:string}):string {
 const existing=store.get('SELECT id,content_hash,url FROM publication_stage_evidence WHERE record_id=? AND revision=? AND stage=? AND commit_sha IS ? AND artifact_hash=?',value.recordId,value.revision,value.stage,value.commitSha||null,value.artifactHash);
 if(existing){check(existing.content_hash===value.contentHash&&existing.url===(value.url||null),409,'PUBLICATION_EVIDENCE_CONFLICT','동일 릴리스 증거의 본문 또는 주소가 변경되었습니다.');return String(existing.id);}
 check(value.stage==='export'||Boolean(value.commitSha),400,'INVALID_EVIDENCE','공개 릴리스 증거에는 커밋 SHA가 필요합니다.');
 const id=randomUUID(),table=value.stage==='export'?'publication_stages':'publication_release_stages';store.run(`INSERT INTO ${table} VALUES (?,?,?,?,?,?,?,?,?,?)`,id,value.recordId,value.revision,value.contentHash,value.stage,value.commitSha||null,value.artifactHash,value.url||null,value.observedAt,value.evidenceSource);return id;
}
export class OperationsService {
 readonly store:Store;readonly config:ApiConfig;constructor(store:Store,config:ApiConfig){this.store=store;this.config=config;}
 assignees(user:User|null):Record<string,unknown>{requirePermission(user,'operations:manage');return {items:this.store.all('SELECT u.id,u.name,u.role,s.scopes FROM users u LEFT JOIN user_scope_settings s ON s.user_id=u.id WHERE u.deactivated=0 ORDER BY u.name LIMIT 500').map(row=>{const user:User={id:String(row.id),name:String(row.name),email:'',role:row.role as User['role'],...row.scopes?{scopes:JSON.parse(String(row.scopes)) as Scope[]}:{}};return {id:user.id,name:user.name,role:user.role,scopes:permissions(user)};}).filter(user=>user.scopes.length>0)};}
 workboard(user:User|null):Record<string,unknown>{const account=requireUser(user),allowed=permissions(account);check(allowed.length>0,403,'FORBIDDEN','운영 업무 권한이 필요합니다.');const items:Record<string,unknown>[]=[];const add=(kind:string,sql:string):void=>{for(const row of this.store.all(sql)){const metadata=this.store.get('SELECT version,assignee_id AS assigneeId,priority,due_at AS dueAt,next_action AS nextAction,updated_at AS updatedAt FROM work_items WHERE kind=? AND resource_id=?',kind,String(row.id));items.push({kind,...row,version:0,assigneeId:null,priority:'normal',dueAt:null,nextAction:'',...metadata});}};if(allowed.includes('content:read')){add('draft','SELECT id,record_id AS recordId,state AS status,updated_at AS updatedAt FROM drafts ORDER BY updated_at DESC LIMIT 200');add('correction',"SELECT id,record_id AS recordId,status,updated_at AS updatedAt FROM corrections WHERE status NOT IN ('resolved','rejected') ORDER BY updated_at DESC LIMIT 200");}if(allowed.includes('operations:manage'))add('job',"SELECT id,kind AS title,status,created_at AS updatedAt FROM jobs WHERE status IN ('pending','running','failed') ORDER BY created_at DESC LIMIT 200");if(allowed.includes('rights:manage'))add('rights','SELECT id,record_id AS recordId,usage AS title,status,updated_at AS updatedAt FROM rights ORDER BY updated_at DESC LIMIT 200');if(allowed.includes('finance:read')){add('service-request','SELECT id,title,status,updated_at AS updatedAt FROM service_requests ORDER BY updated_at DESC LIMIT 200');add('order','SELECT id,product_id AS title,status,updated_at AS updatedAt FROM orders ORDER BY updated_at DESC LIMIT 200');add('refund','SELECT r.id,r.order_id AS orderId,r.status,n.updated_at AS updatedAt FROM refund_requests r LEFT JOIN refund_notes n ON n.request_id=r.id ORDER BY n.updated_at DESC LIMIT 200');}return {items};}
 workItem(user:User|null,kind:string,id:string,value:unknown,requestId:string):Record<string,unknown>{const account=requirePermission(user,'operations:manage');const table={draft:'drafts',correction:'corrections',job:'jobs',order:'orders',rights:'rights',refund:'refund_requests','service-request':'service_requests'}[kind];check(table,400,'INVALID_INPUT','업무 종류를 확인해 주세요.');if(kind==='order'||kind==='refund'||kind==='service-request')requirePermission(account,'finance:manage');else if(kind==='rights')requirePermission(account,'rights:manage');else if(kind==='draft'||kind==='correction')requirePermission(account,'content:read');check(this.store.get(`SELECT id FROM ${table} WHERE id=?`,id),404,'RESOURCE_NOT_FOUND','업무를 찾을 수 없습니다.');const input=object(value),expected=version(input.version),assignee=input.assigneeId?identifier(input.assigneeId):null,priority=text(input.priority,'우선순위',20);check(['low','normal','high','urgent'].includes(priority),400,'INVALID_INPUT','우선순위를 확인해 주세요.');if(assignee){const selected=this.store.get('SELECT u.id,u.role,s.scopes FROM users u LEFT JOIN user_scope_settings s ON s.user_id=u.id WHERE u.id=? AND u.deactivated=0',assignee);check(selected,400,'INVALID_INPUT','활성 담당자를 선택해 주세요.');const allowed=permissions({id:assignee,name:'',email:'',role:selected.role as User['role'],...selected.scopes?{scopes:JSON.parse(String(selected.scopes)) as Scope[]}:{}}),needed=kind==='order'||kind==='refund'||kind==='service-request'?'finance:manage':kind==='rights'?'rights:manage':kind==='job'?'operations:manage':'content:read';check(allowed.includes(needed),400,'ASSIGNEE_SCOPE_REQUIRED','해당 업무 범위를 가진 담당자를 선택해 주세요.');}const dueAt=input.dueAt?isoDate(input.dueAt):null,nextAction=text(input.nextAction,'다음 조치',2000,0);this.store.transaction(()=>{check(Number(this.store.get('SELECT version FROM work_items WHERE kind=? AND resource_id=?',kind,id)?.version||0)===expected,409,'VERSION_CONFLICT','업무 배정이 변경되었습니다.');this.store.run('INSERT INTO work_items VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(kind,resource_id) DO UPDATE SET version=excluded.version,assignee_id=excluded.assignee_id,priority=excluded.priority,due_at=excluded.due_at,next_action=excluded.next_action,updated_at=excluded.updated_at',kind,id,expected+1,assignee,priority,dueAt,nextAction,new Date().toISOString());this.store.audit(account.id,'operations.assign',id,requestId);});return {kind,id,version:expected+1,assigneeId:assignee,priority,dueAt,nextAction};}
 publication(user:User|null,draftId:string):Record<string,unknown>{requirePermission(user,'content:read');const row=this.store.get('SELECT record_id,version,content_hash FROM drafts WHERE id=?',draftId);check(row,404,'RESOURCE_NOT_FOUND','초안을 찾을 수 없습니다.');return {recordId:row.record_id,revision:row.version,contentHash:row.content_hash,stages:this.store.all('SELECT id,revision,content_hash AS contentHash,stage,commit_sha AS commitSha,artifact_hash AS artifactHash,url,observed_at AS observedAt,evidence_source AS evidenceSource FROM publication_stage_evidence WHERE record_id=? ORDER BY observed_at DESC LIMIT 500',String(row.record_id))};}
 ingestEvidence(value:unknown):Record<string,unknown>{check(this.config.deploymentEvidenceSecret,503,'EVIDENCE_DISABLED','배포 증거 검증 키가 필요합니다.');const input=object(value),body={version:input.version,observedAt:input.observedAt,entries:input.entries};check(input.version===1&&Array.isArray(input.entries)&&input.entries.length>0&&input.entries.length<=10000&&typeof input.signature==='string'&&/^[a-f0-9]{64}$/.test(input.signature),400,'INVALID_EVIDENCE','배포 증거 형식을 확인해 주세요.');const expected=createHmac('sha256',this.config.deploymentEvidenceSecret).update(JSON.stringify(body)).digest('hex');check(timingSafeEqual(Buffer.from(expected),Buffer.from(input.signature)),403,'EVIDENCE_SIGNATURE_INVALID','배포 증거 서명이 일치하지 않습니다.');const observedAt=isoDate(input.observedAt);check(Date.parse(observedAt)>Date.now()-1800000&&Date.parse(observedAt)<Date.now()+300000,400,'EVIDENCE_EXPIRED','최근 실측한 배포 증거가 필요합니다.');let count=0;this.store.transaction(()=>{for(const value of input.entries as unknown[]){const item=object(value),recordId=identifier(item.recordId),revision=version(item.revision),stage=text(item.stage,'단계',20),contentHash=text(item.contentHash,'자료 해시',64),artifactHash=text(item.artifactHash,'산출물 해시',64),commitSha=text(item.commitSha,'커밋 SHA',64),url=httpsUrl(item.url,'증거 주소');check(['build','deploy','feed'].includes(stage)&&/^[a-f0-9]{64}$/.test(contentHash)&&/^[a-f0-9]{64}$/.test(artifactHash)&&/^(?:[a-f0-9]{40}|[a-f0-9]{64})$/.test(commitSha),400,'INVALID_EVIDENCE','배포 해시와 단계를 확인해 주세요.');check(this.config.allowedOrigins.includes(new URL(url).origin),403,'EVIDENCE_ORIGIN_REJECTED','허용된 사이트의 증거만 수입합니다.');check(this.store.get('SELECT record_id FROM publication_evidence WHERE record_id=? AND revision=? AND content_hash=?',recordId,revision,contentHash)&&this.store.get('SELECT content_hash FROM public_records WHERE record_id=?',recordId)?.content_hash===contentHash&&!this.store.get('SELECT record_id FROM publication_withheld WHERE record_id=?',recordId),409,'PUBLICATION_MISMATCH','현재 승인 발행과 증거가 일치하지 않습니다.');const previous=stage==='build'?'export':stage==='deploy'?'build':'deploy';const anyPrior=this.store.get('SELECT id FROM publication_stage_evidence WHERE record_id=? AND revision=? AND content_hash=? AND stage=? LIMIT 1',recordId,revision,contentHash,previous);check(anyPrior,409,'PUBLICATION_STAGE_MISSING','동일 버전의 이전 단계 증거가 필요합니다.');if(previous!=='export')check(this.store.get('SELECT id FROM publication_stage_evidence WHERE record_id=? AND revision=? AND content_hash=? AND stage=? AND commit_sha=? AND artifact_hash=? LIMIT 1',recordId,revision,contentHash,previous,commitSha,artifactHash),409,'PUBLICATION_ARTIFACT_MISMATCH','이전 단계의 커밋 SHA와 공개 채널 해시가 일치해야 합니다.');addPublicationStage(this.store,{recordId,revision,contentHash,stage:stage as 'build'|'deploy'|'feed',commitSha,artifactHash,url,observedAt,evidenceSource:'signed-deployment-observation'});count++;}this.store.audit(null,'operations.deployment_evidence',null,'cli-evidence');});return {accepted:count};}
 fulfillment(user:User|null,orderId:string):Record<string,unknown>{const account=requireUser(user),order=this.store.get('SELECT user_id,status FROM orders WHERE id=?',orderId);check(order&&(order.user_id===account.id||permissions(account).includes('finance:read')),404,'RESOURCE_NOT_FOUND','주문을 찾을 수 없습니다.');const row=this.store.get('SELECT version,status,delivery_note AS deliveryNote,delivery_url AS deliveryUrl,updated_at AS updatedAt,confirmed_at AS confirmedAt FROM order_fulfillments WHERE order_id=?',orderId);return {orderId,paymentStatus:order.status,version:0,status:'planned',deliveryNote:'',deliveryUrl:null,...row};}
 fulfill(user:User|null,orderId:string,value:unknown,requestId:string,confirm=false):Record<string,unknown>{const account=requireUser(user);if(!confirm)requirePermission(account,'finance:manage');const order=this.store.get('SELECT * FROM orders WHERE id=?',orderId);check(order&&(!confirm||order.user_id===account.id),404,'RESOURCE_NOT_FOUND','주문을 찾을 수 없습니다.');const input=object(value),expected=version(input.version),status=confirm?'confirmed':text(input.status,'이행 상태',30),note=confirm?'':text(input.deliveryNote,'이행 근거',5000,0),url=!confirm&&input.deliveryUrl?httpsUrl(input.deliveryUrl,'납품 주소'):null;check(['planned','in-progress','delivered','confirmed','cancelled'].includes(status)&& (confirm||status!=='confirmed'),400,'INVALID_INPUT','이행 상태를 확인해 주세요.');check(['paid','partially-refunded'].includes(String(order.status))||status==='cancelled',409,'PAYMENT_REQUIRED','실제 결제 확인 후 서비스를 이행합니다.');this.store.transaction(()=>{const current=this.store.get('SELECT * FROM order_fulfillments WHERE order_id=?',orderId);check(Number(current?.version||0)===expected,409,'VERSION_CONFLICT','이행 상태가 변경되었습니다.');const previous=String(current?.status||'planned');const transitions:Record<string,string[]>={planned:['in-progress','cancelled'], 'in-progress':['delivered','cancelled'],delivered:['confirmed'],confirmed:[],cancelled:[]};check(transitions[previous].includes(status),409,'INVALID_TRANSITION','이행 단계 순서를 확인해 주세요.');if(status==='delivered')check(note.length>0,400,'DELIVERY_EVIDENCE_REQUIRED','납품 근거를 남겨 주세요.');const now=new Date().toISOString();this.store.run('INSERT INTO order_fulfillments VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET version=excluded.version,status=excluded.status,delivery_note=excluded.delivery_note,delivery_url=excluded.delivery_url,updated_by=excluded.updated_by,updated_at=excluded.updated_at,confirmed_at=excluded.confirmed_at',orderId,expected+1,status,confirm?String(current?.delivery_note||''):note,confirm?String(current?.delivery_url||'')||null:url,account.id,now,confirm?now:null);this.store.audit(account.id,confirm?'order.customer_confirmed':'order.fulfillment',orderId,requestId);});return this.fulfillment(account,orderId);}
}
