import { createHmac,timingSafeEqual } from 'node:crypto';
import { Store,hash } from '../infrastructure/database.ts';
import type { ApiConfig } from '../config.ts';
import { check } from '../domain/errors.ts';
import { object,identifier,text,isoDate } from '../domain/validation.ts';
function verified(value:unknown,signature:unknown,secret:string):Record<string,unknown>{check(secret,503,'RECEIPT_DISABLED','수신 증거 검증이 설정되지 않았습니다.');check(typeof signature==='string'&&/^[a-f0-9]{64}$/.test(signature),403,'RECEIPT_SIGNATURE_INVALID','증거 서명이 필요합니다.');const input=object(value),expected=createHmac('sha256',secret).update(JSON.stringify(input)).digest('hex');check(timingSafeEqual(Buffer.from(expected),Buffer.from(signature)),403,'RECEIPT_SIGNATURE_INVALID','증거 서명이 일치하지 않습니다.');check(input.version===1,400,'INVALID_RECEIPT','증거 버전을 확인해 주세요.');const observed=isoDate(input.observedAt);check(Date.parse(observed)>Date.now()-300000&&Date.parse(observed)<Date.now()+60000,400,'RECEIPT_EXPIRED','최근 수신 증거가 필요합니다.');return input;}
export class ReceiptService {
 readonly store:Store;readonly config:ApiConfig;constructor(store:Store,config:ApiConfig){this.store=store;this.config=config;}
 notification(value:unknown,signature:unknown):Record<string,unknown>{const input=verified(value,signature,this.config.notificationReceiptSecret),eventId=identifier(input.eventId),jobId=identifier(input.jobId),status=text(input.status,'수신 상태',20);check(['delivered','failed'].includes(status),400,'INVALID_RECEIPT','수신 결과를 확인해 주세요.');return this.store.transaction(()=>{const existing=this.store.get('SELECT job_id,status,receipt_hash FROM notification_deliveries WHERE provider_event_id=?',eventId);const receiptHash=hash(JSON.stringify(input));if(existing){check(existing.job_id===jobId&&existing.receipt_hash===receiptHash,409,'RECEIPT_CONFLICT','수신 증거 식별자가 재사용되었습니다.');return {jobId,status:existing.status,duplicate:true};}const row=this.store.get('SELECT * FROM notification_deliveries WHERE job_id=?',jobId);check(row,404,'RESOURCE_NOT_FOUND','공급자 접수가 확인된 알림만 갱신할 수 있습니다.');check(row.status==='accepted'&&Date.parse(String(row.expires_at))>Date.now(),409,'NOTIFICATION_TERMINAL','만료되거나 완료된 알림입니다.');this.store.run('UPDATE notification_deliveries SET status=?,provider_event_id=?,updated_at=?,receipt_hash=? WHERE job_id=?',status,eventId,String(input.observedAt),receiptHash,jobId);this.store.audit(null,'notification.receipt',jobId,'provider-receipt');return {jobId,status};});}
 scan(value:unknown,signature:unknown):Record<string,unknown>{const input=verified(value,signature,this.config.fileScanSecret),id=identifier(input.attachmentId),status=text(input.status,'검사 결과',20),scanner=text(input.scanner,'검사기',200),sha256=text(input.sha256,'파일 해시',64);check(['clean','rejected'].includes(status),400,'INVALID_RECEIPT','검사 결과를 확인해 주세요.');const row=this.store.get('SELECT sha256 FROM attachments WHERE id=?',id);check(row&&row.sha256===sha256,409,'SCAN_FILE_MISMATCH','검사한 파일과 저장된 원본이 일치하지 않습니다.');const evidenceHash=hash(JSON.stringify(input));this.store.transaction(()=>{const prior=this.store.get('SELECT * FROM attachment_scans WHERE attachment_id=?',id);check(!prior||prior.status!=='rejected'||status==='rejected',409,'SCAN_TERMINAL','차단된 파일을 임의로 정상으로 바꿀 수 없습니다.');if(prior?.scanned_at)check(String(input.observedAt)>=String(prior.scanned_at),409,'SCAN_STALE','오래된 검사 결과입니다.');this.store.run('INSERT INTO attachment_scans VALUES (?,?,?,?,?) ON CONFLICT(attachment_id) DO UPDATE SET status=excluded.status,scanner=excluded.scanner,evidence_hash=excluded.evidence_hash,scanned_at=excluded.scanned_at',id,status,scanner,evidenceHash,String(input.observedAt));this.store.audit(null,'attachment.scan',id,'scanner-receipt');});return {attachmentId:id,scanStatus:status};}
}
