import { randomBytes } from 'node:crypto';
import { Store,hash } from '../infrastructure/database.ts';
import { verifyPassword } from '../infrastructure/passwords.ts';
import { base32,encryptSecret,decryptSecret,matchedCounter } from '../infrastructure/totp.ts';
import { check } from '../domain/errors.ts';
import { object,credential,identifier } from '../domain/validation.ts';
import { requirePermission,scopes,permissions,type Scope } from '../domain/permissions.ts';
import { requireUser,type Session,type User } from './auth.ts';
import type { ApiConfig } from '../config.ts';
import { invalidateResetNotifications } from './reset-notifications.ts';
export function recoveryEvent(store: Store,kind:'withhold'|'delete-account'|'role'|'scopes'|'offboard',targetId:string,payload:unknown): void {store.run('INSERT INTO recovery_events(kind,target_id,payload,occurred_at) VALUES (?,?,?,?)',kind,targetId,JSON.stringify(payload),new Date().toISOString());}
export class SecurityService {
 readonly store:Store;readonly config:ApiConfig;
 constructor(store:Store,config:ApiConfig){this.store=store;this.config=config;}
 status(session:Session|null):Record<string,unknown>{const user=requireUser(session?.user ?? null);const row=this.store.get('SELECT confirmed FROM user_mfa WHERE user_id=?',user.id);const state=this.store.get('SELECT * FROM session_security WHERE token_hash=?',hash(session!.token));return {enabled:row?.confirmed===1,enrollmentAvailable:Boolean(this.config.securityEncryptionKey),required:this.config.staffMfaRequired && permissions(user).length>0,recentAuthenticated:typeof state?.reauthenticated_at==='string' && Date.parse(state.reauthenticated_at)>Date.now()-600000,mfaVerified:typeof state?.mfa_at==='string' && Date.parse(state.mfa_at)>Date.now()-600000};}
 async authenticate(user:User,value:unknown):Promise<void>{const input=object(value),row=this.store.get('SELECT password_hash FROM users WHERE id=? AND deactivated=0',user.id);check(row && await verifyPassword(credential(input.password),String(row.password_hash)),401,'INVALID_CREDENTIALS','비밀번호를 확인해 주세요.');}
 async enroll(session:Session,value:unknown,requestId:string):Promise<Record<string,unknown>>{const user=requireUser(session.user);check(this.config.securityEncryptionKey,503,'MFA_DISABLED','MFA 암호화 키를 먼저 설정해 주세요.');await this.authenticate(user,value);check(!this.store.get('SELECT user_id FROM user_mfa WHERE user_id=? AND confirmed=1',user.id),409,'MFA_ALREADY_ENABLED','등록된 인증 키를 임의로 교체할 수 없습니다.');const secret=randomBytes(20);this.store.run('INSERT INTO user_mfa VALUES (?,?,0,-1,?) ON CONFLICT(user_id) DO UPDATE SET encrypted_secret=excluded.encrypted_secret,last_counter=-1,enrolled_at=excluded.enrolled_at',user.id,encryptSecret(secret,this.config.securityEncryptionKey,user.id),new Date().toISOString());this.store.audit(user.id,'security.mfa_enroll',user.id,requestId);return {secret:base32(secret),uri:`otpauth://totp/WarArchive:${encodeURIComponent(user.email)}?secret=${base32(secret)}&issuer=WarArchive&algorithm=SHA1&digits=6&period=30`};}
 verify(user:User,code:unknown,confirm=false):void {check(this.config.securityEncryptionKey,503,'MFA_DISABLED','MFA가 설정되지 않았습니다.');this.store.transaction(()=>{const row=this.store.get('SELECT * FROM user_mfa WHERE user_id=?',user.id);check(row && (confirm || row.confirmed===1),403,'MFA_ENROLLMENT_REQUIRED','MFA 등록을 완료해 주세요.');check(!confirm || row.confirmed===0,409,'MFA_ALREADY_ENABLED','이미 등록되었습니다.');check(!confirm || Date.parse(String(row.enrolled_at))>Date.now()-600000,409,'MFA_ENROLLMENT_EXPIRED','등록 요청이 만료되었습니다.');const counter=matchedCounter(decryptSecret(String(row.encrypted_secret),this.config.securityEncryptionKey,user.id),code,Number(row.last_counter));this.store.run('UPDATE user_mfa SET confirmed=1,last_counter=? WHERE user_id=?',counter,user.id);});}
 challenge(session:Session,value:unknown,confirm:boolean,requestId:string):Record<string,unknown>{const user=requireUser(session.user);this.verify(user,object(value).code,confirm);const now=new Date().toISOString();this.store.run('INSERT INTO session_security VALUES (?,?,?) ON CONFLICT(token_hash) DO UPDATE SET mfa_at=excluded.mfa_at',hash(session.token),null,now);this.store.audit(user.id,confirm?'security.mfa_confirm':'security.mfa_challenge',user.id,requestId);return this.status(session);}
 async reauth(session:Session,value:unknown,requestId:string):Promise<Record<string,unknown>>{const user=requireUser(session.user);await this.authenticate(user,value);const enrolled=this.store.get('SELECT confirmed FROM user_mfa WHERE user_id=?',user.id)?.confirmed===1;if(enrolled)this.verify(user,object(value).totp);const now=new Date().toISOString();this.store.run('INSERT INTO session_security VALUES (?,?,?) ON CONFLICT(token_hash) DO UPDATE SET reauthenticated_at=excluded.reauthenticated_at,mfa_at=COALESCE(excluded.mfa_at,session_security.mfa_at)',hash(session.token),now,enrolled?now:null);this.store.audit(user.id,'security.reauth',user.id,requestId);return this.status(session);}
 sensitive(session:Session|null):void {const user=requireUser(session?.user ?? null),state=this.status(session);if(this.config.staffMfaRequired && permissions(user).length)check(state.enabled && state.mfaVerified,403,'MFA_REQUIRED','직원 MFA 확인이 필요합니다.');if(this.config.recentReauthRequired)check(state.recentAuthenticated,403,'REAUTH_REQUIRED','10분 이내 재인증이 필요합니다.');}
 staff(session:Session|null):void{const user=requireUser(session?.user??null);if(this.config.staffMfaRequired&&permissions(user).length){const state=this.status(session),security=this.store.get('SELECT mfa_at FROM session_security WHERE token_hash=?',hash(session!.token));check(state.enabled&&typeof security?.mfa_at==='string',403,'MFA_REQUIRED','직원 MFA 등록·확인이 필요합니다.');}}
 scopeSettings(user:User|null,id:string):Record<string,unknown>{requirePermission(user,'security:manage');const target=this.store.get('SELECT role FROM users WHERE id=? AND deactivated=0',identifier(id));check(target,404,'RESOURCE_NOT_FOUND','사용자를 찾을 수 없습니다.');const row=this.store.get('SELECT scopes FROM user_scope_settings WHERE user_id=?',id);return {userId:id,explicit:Boolean(row),scopes:row?JSON.parse(String(row.scopes)) as unknown:permissions({id,email:'',name:'',role:target.role as User['role']})};}
 setScopes(user:User|null,id:string,value:unknown,requestId:string):Record<string,unknown>{const account=requirePermission(user,'security:manage');this.scopeSettings(account,id);const list=object(value).scopes;check(Array.isArray(list)&&list.length<=scopes.length&&list.every((s)=>scopes.includes(s as Scope))&&new Set(list).size===list.length,400,'INVALID_INPUT','업무 범위를 확인해 주세요.');check(account.id!==id || list.includes('security:manage'),409,'SELF_LOCKOUT','자신의 보안 관리 권한을 제거할 수 없습니다.');this.store.transaction(()=>{this.store.run('INSERT INTO user_scope_settings VALUES (?,?,?) ON CONFLICT(user_id) DO UPDATE SET scopes=excluded.scopes,updated_at=excluded.updated_at',id,JSON.stringify(list),new Date().toISOString());this.store.run('DELETE FROM sessions WHERE user_id=?',id);recoveryEvent(this.store,'scopes',id,{scopes:list});this.store.audit(account.id,'security.scopes_update',id,requestId);});return this.scopeSettings(account,id);}
 offboard(user:User|null,id:string,requestId:string):Record<string,unknown>{const account=requirePermission(user,'security:manage');check(account.id!==id,409,'SELF_LOCKOUT','자신을 퇴직 처리할 수 없습니다.');const target=this.store.get('SELECT * FROM users WHERE id=? AND deactivated=0',id);check(target,404,'RESOURCE_NOT_FOUND','사용자를 찾을 수 없습니다.');if(target.role==='admin')check(Number(this.store.get("SELECT count(*) AS count FROM users WHERE role='admin' AND deactivated=0")?.count)>1,409,'LAST_ADMIN','마지막 관리자를 보호합니다.');check(!this.store.get('SELECT id FROM spaces WHERE owner_id=? LIMIT 1',id),409,'OWNERSHIP_TRANSFER_REQUIRED','공동 공간 소유권을 이전해 주세요.');this.store.transaction(()=>{this.store.run('UPDATE users SET deactivated=1 WHERE id=?',id);this.store.run('DELETE FROM sessions WHERE user_id=?',id);this.store.run('DELETE FROM password_resets WHERE user_id=?',id);this.store.run('DELETE FROM user_mfa WHERE user_id=?',id);invalidateResetNotifications(this.store,id);recoveryEvent(this.store,'offboard',id,{});this.store.audit(account.id,'security.offboard',id,requestId);});return {userId:id,status:'offboarded'};}
}
