import { randomUUID } from 'node:crypto';
import { Store } from '../infrastructure/database.ts';
import { requireUser,type User } from './auth.ts';
import { requirePermission,permissions,type Scope } from '../domain/permissions.ts';
import { object,text,identifier,version,isoDate } from '../domain/validation.ts';
import { check } from '../domain/errors.ts';
import { InstitutionService } from './institutions.ts';
function model(row:Record<string,unknown>):Record<string,unknown>{return {id:row.id,userId:row.user_id,version:row.version,title:row.title,audience:row.audience,deliverables:JSON.parse(String(row.deliverables)) as unknown,rights:row.rights,deadline:row.deadline,status:row.status,assignedTo:row.assigned_to,dueAt:row.due_at,quoteNote:row.quote_note,contractId:row.contract_id,orderId:row.order_id,evidence:row.evidence,createdAt:row.created_at,updatedAt:row.updated_at};}
export class ServiceRequestService {
 readonly store:Store;constructor(store:Store){this.store=store;}
 list(user:User|null):Record<string,unknown>{const account=requireUser(user),staff=permissions(account).includes('finance:read');return {items:this.store.all(`SELECT * FROM service_requests${staff?'':' WHERE user_id=?'} ORDER BY updated_at DESC LIMIT 500`,...staff?[]:[account.id]).map(model)};}
 get(user:User|null,id:string):Record<string,unknown>{const account=requireUser(user),row=this.store.get('SELECT * FROM service_requests WHERE id=?',id);check(row&&(row.user_id===account.id||permissions(account).includes('finance:read')),404,'RESOURCE_NOT_FOUND','서비스 문의를 찾을 수 없습니다.');return model(row);}
 create(user:User|null,value:unknown,requestId:string):Record<string,unknown>{const account=requireUser(user),input=object(value),deliverables=input.deliverables;check(Array.isArray(deliverables)&&deliverables.length>0&&deliverables.length<=20,400,'INVALID_INPUT','원하는 납품 항목을 확인해 주세요.');const items=deliverables.map(v=>text(v,'납품 항목',500)),id=randomUUID(),now=new Date().toISOString();this.store.run('INSERT INTO service_requests VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,account.id,1,text(input.title,'문의 제목',200),text(input.audience,'이용 대상',2000),JSON.stringify(items),text(input.rights,'권리와 이용 범위',2000),input.deadline?isoDate(input.deadline):null,'received',null,null,'',null,null,'',now,now);this.store.audit(account.id,'service.request',id,requestId);return this.get(account,id);}
 update(user:User|null,id:string,value:unknown,requestId:string):Record<string,unknown>{const account=requirePermission(user,'finance:manage'),input=object(value),expected=version(input.version),status=text(input.status,'문의 상태',30);return this.store.transaction(()=>{const row=this.store.get('SELECT * FROM service_requests WHERE id=?',id);check(row,404,'RESOURCE_NOT_FOUND','서비스 문의를 찾을 수 없습니다.');check(row.version===expected,409,'VERSION_CONFLICT','문의가 변경되었습니다.');const transitions:Record<string,string[]>= {received:['qualified'],qualified:['quoted'],quoted:['contracted'],contracted:['fulfilling'],fulfilling:['delivered'],delivered:['closed'],closed:[]};check(transitions[String(row.status)]?.includes(status),409,'INVALID_TRANSITION','문의·견적·계약·이행 순서를 확인해 주세요.');const quoteNote=input.quoteNote===undefined?String(row.quote_note):text(input.quoteNote,'견적 내용',5000,0),contractId=input.contractId?identifier(input.contractId):row.contract_id as string|null,orderId=input.orderId?identifier(input.orderId):row.order_id as string|null,evidence=input.evidence===undefined?String(row.evidence):text(input.evidence,'이행 근거',5000,0),assignedTo=input.assignedTo===undefined?row.assigned_to as string|null:input.assignedTo?identifier(input.assignedTo):null,dueAt=input.dueAt===undefined?row.due_at as string|null:input.dueAt?isoDate(input.dueAt):null;
 if(assignedTo){const selected=this.store.get('SELECT u.id,u.role,s.scopes FROM users u LEFT JOIN user_scope_settings s ON s.user_id=u.id WHERE u.id=? AND u.deactivated=0',assignedTo);check(selected,400,'INVALID_INPUT','활성 담당자를 선택해 주세요.');check(permissions({id:assignedTo,name:'',email:'',role:selected.role as User['role'],...(selected.scopes?{scopes:JSON.parse(String(selected.scopes)) as Scope[]}:{})}).includes('finance:manage'),400,'ASSIGNEE_SCOPE_REQUIRED','금융 관리 업무 범위를 가진 담당자를 선택해 주세요.');}if(status==='quoted')check(quoteNote.length>0,400,'QUOTE_REQUIRED','실제 견적 내용을 남겨 주세요.');if(['contracted','fulfilling','delivered','closed'].includes(status)){const contract=contractId?this.store.get('SELECT * FROM contracts WHERE id=?',contractId):undefined,order=orderId?this.store.get('SELECT * FROM orders WHERE id=?',orderId):undefined;check(contract&&new InstitutionService(this.store).contractReadiness(contract).scopeVerified===true&&order?.user_id===row.user_id,409,'SERVICE_CONTRACT_REQUIRED','유효한 계약과 문의 고객의 실제 주문을 연결해 주세요.');if(status!=='contracted')check(['paid','partially-refunded'].includes(String(order.status)),409,'PAYMENT_REQUIRED','서버에서 확인한 결제 후 이행합니다.');}if(['delivered','closed'].includes(status)){const fulfillment=this.store.get('SELECT status FROM order_fulfillments WHERE order_id=?',String(orderId));check(fulfillment&& (status==='closed'?fulfillment.status==='confirmed':['delivered','confirmed'].includes(String(fulfillment.status))),409,'CUSTOMER_CONFIRMATION_REQUIRED','주문의 실제 납품·고객 확인 상태와 연결해야 합니다.');}if(['delivered','closed'].includes(status))check(evidence.length>0,400,'DELIVERY_EVIDENCE_REQUIRED','이행·종결 근거를 남겨 주세요.');this.store.run('UPDATE service_requests SET version=version+1,status=?,assigned_to=?,due_at=?,quote_note=?,contract_id=?,order_id=?,evidence=?,updated_at=? WHERE id=?',status,assignedTo,dueAt,quoteNote,contractId,orderId,evidence,new Date().toISOString(),id);this.store.audit(account.id,'service.transition',id,requestId);return this.get(account,id);});}
}
