import { apiItems, apiObject, apiString } from "./api-client.ts";
import { isResearchProject, isTeachingPlan, type ResearchProject, type TeachingPlan } from "./workspace-domain.ts";
export type ResearchFields = { claimText: string; claimId: string; recordId: string; sourceId: string; locator: string; evidenceKind: "quote" | "note"; evidenceText: string; sectionId: string; origin: "editorial" | "source-link"; nextCheck: string };
export type ResearchCapture = { id: string; projectId: string; form: ResearchFields; capturedAt: string };
export type ResearchRecovery = { draft: ResearchProject | null; buffers: ResearchProject[]; captures: ResearchCapture[]; form: ResearchFields; forms: Record<string, ResearchFields>; entryQuery: string };
export function emptyResearchFields(): ResearchFields { return { claimText: "", claimId: "", recordId: "", sourceId: "", locator: "", evidenceKind: "note", evidenceText: "", sectionId: "", origin: "editorial", nextCheck: "" }; }
export function emptyResearchRecovery(): ResearchRecovery { return { draft: null, buffers: [], captures: [], form: emptyResearchFields(), forms: {}, entryQuery: "" }; }
export function preserveResearchCapture(captures: ResearchCapture[], projectId: string, form: ResearchFields, id: string, capturedAt: string): ResearchCapture[] {
  if (!form.evidenceText && !form.locator && !form.sourceId && !form.sectionId) return captures;
  if (captures.some(item => item.projectId === projectId && JSON.stringify(item.form) === JSON.stringify(form))) return captures;
  if (captures.length >= 50) throw new Error("보관한 근거 입력이 50개입니다. 복구 초안을 내보내고 불필요한 입력 사본을 제거한 뒤 자료를 연결하세요.");
  return [...captures, { id, projectId, form: { ...form }, capturedAt }];
}
function decodeResearchFields(value: unknown): ResearchFields { const data = apiObject(value); return { claimText: apiString(data.claimText, 2000), claimId: apiString(data.claimId, 80), recordId: apiString(data.recordId, 80), sourceId: apiString(data.sourceId, 80), locator: apiString(data.locator, 500), evidenceKind: data.evidenceKind === "quote" ? "quote" : "note", evidenceText: apiString(data.evidenceText, 8000), sectionId: apiString(data.sectionId, 100), origin: data.origin === "source-link" ? "source-link" : "editorial", nextCheck: apiString(data.nextCheck ?? "", 1000) }; }
export function decodeResearchRecovery(value: unknown): ResearchRecovery {
  const data = apiObject(value); if (data.draft !== null && !isResearchProject(data.draft)) throw new Error("연구 초안을 확인하세요.");
  const buffers = apiItems(data.buffers).map(item => { if (!isResearchProject(item)) throw new Error("연구 사본을 확인하세요."); return item; }); if (buffers.length > 50) throw new Error("연구 초안은 50개 이하만 보관합니다.");
  const forms = Object.fromEntries(Object.entries(apiObject(data.forms)).map(([key, form]) => [key, decodeResearchFields(form)]));
  const captures = apiItems(data.captures ?? []).map(value => { const item = apiObject(value); return { id: apiString(item.id, 80), projectId: apiString(item.projectId, 80), capturedAt: apiString(item.capturedAt, 40), form: decodeResearchFields(item.form) }; }); if (captures.length > 50) throw new Error("근거 입력 사본은 50개 이하만 보관합니다.");
  return { draft: data.draft, buffers, captures, form: decodeResearchFields(data.form), forms, entryQuery: apiString(data.entryQuery, 14000) };
}
export type TeachingRecovery = { draft: TeachingPlan | null; buffers: TeachingPlan[]; questions: Record<string, string>; question: string; sharedPlan: boolean; entryQuery: string };
export function emptyTeachingRecovery(): TeachingRecovery { return { draft: null, buffers: [], questions: {}, question: "", sharedPlan: false, entryQuery: "" }; }
export function decodeTeachingRecovery(value: unknown): TeachingRecovery { const data = apiObject(value); if (data.draft !== null && !isTeachingPlan(data.draft)) throw new Error("수업 초안을 확인하세요."); const buffers = apiItems(data.buffers).map(item => { if (!isTeachingPlan(item)) throw new Error("수업 사본을 확인하세요."); return item; }); if (buffers.length > 50) throw new Error("수업 초안은 50개 이하만 보관합니다."); return { draft: data.draft, buffers, questions: Object.fromEntries(Object.entries(apiObject(data.questions)).map(([id, question]) => [id, apiString(question, 2000)])), question: apiString(data.question, 2000), sharedPlan: data.sharedPlan === true, entryQuery: apiString(data.entryQuery, 14000) }; }
export function safeInternalReturn(raw: string | null, basePath = ""): string | null {
  if (!raw || raw.length > 14000 || !raw.startsWith("/") || raw.startsWith("//") || raw.includes("\\") || Array.from(raw).some(character => character.charCodeAt(0) <= 32)) return null;
  try { const originalPath = decodeURIComponent(raw.split(/[?#]/)[0]); if (originalPath.split("/").some(segment => segment === "." || segment === "..") || originalPath.includes("%")) return null; const url = new URL(raw, "https://archive.invalid"); const path = decodeURIComponent(url.pathname); const base = basePath.replace(/\/$/, ""); if (url.origin !== "https://archive.invalid" || path.includes("\\") || path.startsWith("//") || path.split("/").some(segment => segment === "." || segment === "..")) return null; const relative = base && path.startsWith(base + "/") ? path.slice(base.length) : path; if (base && !path.startsWith(base + "/")) return null; if (!/^\/(workspace|teach|saved|archive|collections|stories|explore|timeline|about|admin|assist|services|corrections)(\/|$)/.test(relative)) return null; return url.pathname + url.search + url.hash; } catch { return null; }
}
export type SharedCopy = { id: string; title: string; capturedAt: string; version: number; text: string };
export type SharedRecovery = { title: string; description: string; joinCode: string; taskTitle: string; editingTaskId:string; editingTaskVersion:number; instructions: string; teacherNotes: string; answerKey: string; recordIds: string[]; payloadText: string; payloadVersion: number; copies: SharedCopy[]; spaceId: string; taskId: string; answer: string; evidenceNotes: string; planId: string; feedback: Record<string, string>; answers: Record<string, { answer: string; evidenceNotes: string; recordIds: string[]; version: number }> };
export function emptySharedRecovery(): SharedRecovery { return { title: "", description: "", joinCode: "", taskTitle: "", editingTaskId:"", editingTaskVersion:0, instructions: "", teacherNotes: "", answerKey: "", recordIds: [], payloadText: "", payloadVersion: 0, copies: [], spaceId: "", taskId: "", answer: "", evidenceNotes: "", planId: "", feedback: {}, answers: {} }; }
export function decodeSharedRecovery(value: unknown): SharedRecovery { const data = apiObject(value); const list = (value: unknown) => { const ids = apiItems(value).map(id => apiString(id, 80)); if (ids.length > 100 || !ids.every(id => /^[A-Za-z0-9_-]{1,80}$/.test(id))) throw new Error("복구 자료 목록을 확인하세요."); return ids; }; const answers = Object.fromEntries(Object.entries(apiObject(data.answers)).map(([key, value]) => { const item = apiObject(value); if (typeof item.version !== "number" || !Number.isSafeInteger(item.version) || item.version < 0) throw new Error("답안 복구 버전을 확인하세요."); return [key, { answer: apiString(item.answer, 16000), evidenceNotes: apiString(item.evidenceNotes, 8000), recordIds: list(item.recordIds), version: item.version }]; })); const payloadVersion=data.payloadVersion??0;if(typeof payloadVersion!=="number"||!Number.isSafeInteger(payloadVersion)||payloadVersion<0)throw new Error("공유 초안 버전을 확인하세요.");const copies=apiItems(data.copies??[]).map(value=>{const item=apiObject(value);if(typeof item.version!=="number"||!Number.isSafeInteger(item.version)||item.version<0)throw new Error("공유 사본 버전을 확인하세요.");return {id:apiString(item.id,100),title:apiString(item.title,160),capturedAt:apiString(item.capturedAt,40),version:item.version,text:apiString(item.text,250000)};});if(copies.length>20)throw new Error("공유 복구 사본은 20개 이하만 보관합니다.");const editingTaskVersion=data.editingTaskVersion??0;if(typeof editingTaskVersion!=="number"||!Number.isSafeInteger(editingTaskVersion)||editingTaskVersion<0)throw new Error("과제 편집 버전을 확인하세요.");return { editingTaskId:apiString(data.editingTaskId??"",100),editingTaskVersion,payloadVersion,copies,title: apiString(data.title, 160), description: apiString(data.description, 2000), joinCode: apiString(data.joinCode, 160), taskTitle: apiString(data.taskTitle, 160), instructions: apiString(data.instructions, 8000), teacherNotes: apiString(data.teacherNotes, 10000), answerKey: apiString(data.answerKey, 10000), recordIds: list(data.recordIds), payloadText: apiString(data.payloadText, 250000), spaceId: apiString(data.spaceId, 100), taskId: apiString(data.taskId, 100), answer: apiString(data.answer, 16000), evidenceNotes: apiString(data.evidenceNotes, 8000), planId: apiString(data.planId, 80), feedback: Object.fromEntries(Object.entries(apiObject(data.feedback)).map(([key, value]) => [key, apiString(value, 8000)])), answers }; }
