import test,{type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import type { AddressInfo } from 'node:net';
import { mkdtemp,readFile,writeFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { createHmac } from 'node:crypto';
import { Store,hash } from '../src/infrastructure/database.ts';
import { readConfig } from '../src/config.ts';
import { createApp } from '../src/http/app.ts';
import { disabledAdapters,type Adapters } from '../src/adapters/contracts.ts';
import { object } from '../src/domain/validation.ts';
import type { User } from '../src/application/auth.ts';
import { totp,decodeBase32 } from '../src/infrastructure/totp.ts';
import { backupBundle,restoreBundle } from '../src/infrastructure/backup-bundle.ts';
import { MetricsService } from '../src/application/metrics.ts';
import { preflight } from '../src/application/operations.ts';
const origin='http://localhost:3000',secret='refinement-separate-evidence-secret-'.repeat(2),password='tested-password-123';
const editorial=object(JSON.parse(await readFile(new URL('../../web/content/editorial.json',import.meta.url),'utf8')) as unknown);assert.ok(Array.isArray(editorial.records));const record=object(editorial.records[0]);
function signed(value:unknown,key=secret):string{return createHmac('sha256',key).update(JSON.stringify(value)).digest('hex');}
async function fixture(t:TestContext,extra:Record<string,string>={},adapters:Adapters=disabledAdapters()){
 const directory=await mkdtemp(resolve(tmpdir(),'war-refinement-')),config=readConfig({ARCHIVE_API_DB_PATH:resolve(directory,'api.sqlite'),ARCHIVE_API_EXPORT_DIR:resolve(directory,'exports'),ARCHIVE_API_PRIVATE_STORAGE_DIR:resolve(directory,'private'),ARCHIVE_API_ALLOWED_ORIGINS:`${origin},https://archive.example`,ARCHIVE_API_SESSION_SECRET:'test-session-secret-'.repeat(3),ARCHIVE_PUBLICATION_SECRET:'test-publication-secret-'.repeat(3),ARCHIVE_SECURITY_ENCRYPTION_KEY:'34'.repeat(32),ARCHIVE_DEPLOYMENT_EVIDENCE_SECRET:secret,ARCHIVE_NOTIFICATION_RECEIPT_SECRET:'notification-'+secret,ARCHIVE_FILE_SCAN_SECRET:'scan-'+secret,ARCHIVE_PRODUCTS_JSON:JSON.stringify([{id:'course',title:'Test course',amountMinor:1000,currency:'usd'}]),...extra}),store=new Store(config.dbPath),app=createApp({store,config,adapters}),server=createServer((req,res)=>void app.handler(req,res));await new Promise<void>(done=>server.listen(0,'127.0.0.1',done));const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;t.after(async()=>{server.closeAllConnections();await new Promise<void>(done=>server.close(()=>done()));store.close();assert.ok(directory.startsWith(resolve(tmpdir(),'war-refinement-')));await rm(directory,{recursive:true});});
 async function account(name:string,role:User['role']='member'){const session=await app.auth.register({email:`${name}@example.org`,name,password},app.auth.createSession(null).token,'test');assert.ok(session.user);store.run('UPDATE users SET role=? WHERE id=?',role,session.user.id);return {...session.user,role};}
 async function client(user?:User){let cookie='',csrf='';async function request(path:string,method='GET',value?:unknown){const response=await fetch(url+path,{method,headers:{Origin:origin,Cookie:cookie,...method!=='GET'?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{}},...value!==undefined?{body:JSON.stringify(value)}:{}});const envelope=object(await response.json());const next=response.headers.get('set-cookie');if(next)cookie=next.split(';')[0];const data=envelope.data?object(envelope.data):{};if(typeof data.csrfToken==='string')csrf=data.csrfToken;return {status:response.status,data,error:envelope.error?object(envelope.error):null};}await request('/api/v1/auth/session');if(user)assert.equal((await request('/api/v1/auth/login','POST',{email:user.email,password})).status,200);return {request};}
 async function publish(){const author=await account('author','editor'),reviewer=await account('reviewer','reviewer'),publisher=await account('publisher','publisher');let draft=app.editorial.save(author,null,{record},'test');draft=app.editorial.transition(author,draft.id,'submit',{version:draft.version},'test') as typeof draft;draft=app.editorial.transition(reviewer,draft.id,'source-check',{version:draft.version,note:'test source check'},'test') as typeof draft;draft=app.editorial.transition(reviewer,draft.id,'approve',{version:draft.version,contentHash:draft.contentHash,note:'test independent approval'},'test') as typeof draft;app.editorial.transition(publisher,draft.id,'publish',{version:draft.version},'test');assert.equal(await app.worker.tick(),true);assert.equal(await app.worker.tick(),true);return {draft,author,reviewer,publisher};}
 return {directory,config,store,app,url,account,client,publish};
}
test('RFC TOTP vectors and staff HTTP MFA prevent replay and require recent password authentication',async t=>{
 assert.equal(totp(Buffer.from('12345678901234567890'),1,8),'94287082');
 const env=await fixture(t,{ARCHIVE_STAFF_MFA_REQUIRED:'true',ARCHIVE_RECENT_REAUTH_REQUIRED:'true'}),admin=await env.account('admin','admin'),client=await env.client(admin);
 for(let attempt=0;attempt<12;attempt++)assert.equal((await client.request('/api/v1/auth/mfa')).status,200);
 assert.equal((await client.request('/api/v1/cms/dashboard')).error?.code,'MFA_REQUIRED');const enrollment=await client.request('/api/v1/auth/mfa/enroll','POST',{password});assert.equal(enrollment.status,200);assert.match(String(enrollment.data.uri),/^otpauth:\/\//);const key=decodeBase32(String(enrollment.data.secret)),counter=Math.floor(Date.now()/30000);
 assert.equal((await client.request('/api/v1/auth/mfa/confirm','POST',{code:totp(key,counter)})).data.enabled,true);assert.equal((await client.request('/api/v1/auth/reauth','POST',{password,totp:totp(key,counter)})).error?.code,'MFA_INVALID');assert.equal((await client.request('/api/v1/auth/reauth','POST',{password,totp:totp(key,counter+1)})).data.recentAuthenticated,true);
 assert.equal((await client.request('/api/v1/cms/dashboard')).status,200);assert.equal((await client.request('/api/v1/admin/users/'+admin.id+'/scopes','PUT',{scopes:['security:manage','content:read']})).status,200);assert.equal((await client.request('/api/v1/shelf')).status,401);const stored=String(env.store.get('SELECT encrypted_secret FROM user_mfa WHERE user_id=?',admin.id)?.encrypted_secret);assert.ok(!stored.includes(String(enrollment.data.secret))&&!stored.includes(key.toString('hex')));
 assert.equal((await (await env.client(admin)).request('/api/v1/cms/dashboard')).error?.code,'MFA_REQUIRED');
});
test('explicit finance grants deny content and scope changes revoke live sessions',async t=>{
 const env=await fixture(t),admin=await env.account('admin','admin'),staff=await env.account('finance','reviewer'),adminClient=await env.client(admin),old=await env.client(staff);
 assert.equal((await adminClient.request('/api/v1/admin/users/'+staff.id+'/scopes','PUT',{scopes:['finance:read','finance:manage']})).status,200);assert.equal((await old.request('/api/v1/shelf')).status,401);const client=await env.client(staff);assert.equal((await client.request('/api/v1/cms/drafts')).status,403);assert.equal((await client.request('/api/v1/payments/refund-requests')).status,200);assert.equal((await client.request('/api/v1/operations/workboard')).status,200);assert.equal((await client.request('/api/v1/admin/users')).status,403);
});
test('teacher-only fields are absent for students and immutable feedback remains bound to submission and task versions',async t=>{
 const env=await fixture(t),teacher=await env.account('teacher'),student=await env.account('student'),staff=await env.client(teacher),learner=await env.client(student);const space=(await staff.request('/api/v1/spaces','POST',{kind:'study',title:'Class',payload:{plan:{teacherNotes:'private plan',answerKey:'private answer'}}})).data,id=String(space.id);await staff.request(`/api/v1/spaces/${id}/members`,'POST',{email:student.email,role:'viewer'});
 const created=await staff.request(`/api/v1/spaces/${id}/tasks`,'POST',{title:'Read',instructions:'Compare',recordIds:['imjin-war'],teacherNotes:'private task',answerKey:'private key',readingMetadata:[{recordId:'imjin-war',minutes:12,sourceKind:'institutional',limitations:'Institution summary'}]});assert.equal(created.status,200);assert.ok(Array.isArray(created.data.tasks));const task=object(created.data.tasks[0]);assert.equal(task.version,1);const taskId=String(task.id);
 const visible=await learner.request(`/api/v1/spaces/${id}`);assert.ok(!JSON.stringify(visible.data).includes('private')&&!JSON.stringify(visible.data).includes('answerKey'));
 const updated=await staff.request(`/api/v1/spaces/${id}/tasks/${taskId}`,'PUT',{version:1,title:'Read revised',instructions:'Compare',recordIds:['imjin-war'],teacherNotes:'private new'});assert.equal(updated.status,200);assert.equal((await staff.request(`/api/v1/spaces/${id}/tasks/${taskId}`,'PUT',{version:1,title:'stale',instructions:'Compare',recordIds:[]})).error?.code,'VERSION_CONFLICT');
 const submitted=await learner.request(`/api/v1/spaces/${id}/tasks/${taskId}/submissions`,'POST',{version:0,payload:{answer:'first',recordIds:['imjin-war']}});assert.ok(Array.isArray(submitted.data.submissions));const submission=object(submitted.data.submissions[0]);assert.equal(submission.taskVersion,2);const submissionId=String(submission.id);const feedback=await staff.request(`/api/v1/spaces/${id}/submissions/${submissionId}/feedback`,'PUT',{version:1,feedback:'First evaluation'});assert.equal(feedback.status,200);
 await learner.request(`/api/v1/spaces/${id}/tasks/${taskId}/submissions`,'POST',{version:1,payload:{answer:'second',recordIds:[]}});const history=await learner.request(`/api/v1/spaces/${id}/submissions/${submissionId}/history`);assert.ok(Array.isArray(history.data.feedback));assert.equal(object(history.data.feedback[0]).submissionVersion,1);assert.equal(object(history.data.feedback[0]).feedbackVersion,1);assert.equal((await staff.request(`/api/v1/spaces/${id}/submissions/${submissionId}/feedback`,'PUT',{version:1,feedback:'stale evaluation'})).error?.code,'VERSION_CONFLICT');
});
test('knowledge preflight detects bibliography changes and registry changes invalidate queued approvals',async t=>{
 const env=await fixture(t);env.config.knowledgeFile=resolve(env.directory,'knowledge.json');const source=await readFile(new URL('../../web/content/knowledge.json',import.meta.url),'utf8');await writeFile(env.config.knowledgeFile,source);const author=await env.account('author','editor'),reviewer=await env.account('reviewer','reviewer'),publisher=await env.account('publisher','publisher');let draft=env.app.editorial.save(author,null,{record},'test');assert.equal(preflight(env.store,env.config,draft.id).ready,true);draft=env.app.editorial.transition(author,draft.id,'submit',{version:draft.version},'test') as typeof draft;draft=env.app.editorial.transition(reviewer,draft.id,'source-check',{version:draft.version,note:'test'},'test') as typeof draft;draft=env.app.editorial.transition(reviewer,draft.id,'approve',{version:draft.version,contentHash:draft.contentHash,note:'test'},'test') as typeof draft;await writeFile(env.config.knowledgeFile,source+'\n');assert.throws(()=>env.app.editorial.transition(publisher,draft.id,'publish',{version:draft.version},'test'),/레지스트리/);
 const changed=structuredClone(record);assert.ok(Array.isArray(changed.sources));object(changed.sources[0]).creator='changed provider';draft=env.app.editorial.save(author,draft.id,{version:draft.version,record:changed},'test');const result=preflight(env.store,env.config,draft.id);assert.equal(result.ready,false);assert.ok(Array.isArray(result.issues)&&result.issues.some(v=>object(v).code==='SOURCE_IDENTITY_CHANGED'));
});
test('signed export, build, deploy and feed evidence are ordered and corrections cannot close before actual matching deployment evidence',async t=>{
 const env=await fixture(t),{draft,reviewer}=await env.publish();const correction=env.app.editorial.correction(null,{recordId:record.id,category:'test',proposal:'test correction',consent:true},'test'),id=String(correction.receiptId);env.app.editorial.moderate(reviewer,id,{status:'accepted',note:'Accept for review'},'test');assert.throws(()=>env.app.editorial.moderate(reviewer,id,{status:'resolved',note:'Closed',revision:draft.version,publicationId:'invented',closureEvidence:'test'},'test'),/증거/);
 const entry=(stage:string)=>({recordId:record.id,revision:draft.version,contentHash:draft.contentHash,stage,commitSha:'a'.repeat(40),artifactHash:hash('observed-public-channel'),url:'https://archive.example/release.json'});const observedAt=new Date().toISOString(),outOfOrder={version:1,observedAt,entries:[entry('deploy')]};assert.throws(()=>env.app.operations.ingestEvidence({...outOfOrder,signature:signed(outOfOrder)}),/이전/);
 const buildOnly={version:1,observedAt,entries:[entry('build')]};env.app.operations.ingestEvidence({...buildOnly,signature:signed(buildOnly)});const forgedArtifact={version:1,observedAt,entries:[{...entry('deploy'),artifactHash:'0'.repeat(64)}]};assert.throws(()=>env.app.operations.ingestEvidence({...forgedArtifact,signature:signed(forgedArtifact)}),/채널 해시/);
 const body={version:1,observedAt,entries:['build','deploy','feed'].map(entry)};assert.equal(env.app.operations.ingestEvidence({...body,signature:signed(body)}).accepted,3);assert.equal(env.app.operations.ingestEvidence({...body,signature:signed(body)}).accepted,3);const stage=env.store.get("SELECT id FROM publication_stage_evidence WHERE stage='feed'");assert.ok(stage);assert.equal(env.app.editorial.moderate(reviewer,id,{status:'resolved',note:'Deployed',revision:draft.version,publicationId:stage.id,closureEvidence:'Verified release and feed'},'test').status,'resolved');assert.equal(env.store.get('SELECT count(*) AS count FROM publication_stage_evidence')?.count,4);
});
test('unchanged approved records retain distinct release evidence across interleaved SHAs and correction closures use the actual release',async t=>{
 const env=await fixture(t),{draft,reviewer}=await env.publish(),channelHash=hash('same-public-channel'),shaA='a'.repeat(40),shaB='b'.repeat(40);
 const legacy=env.store.all('SELECT * FROM publication_stages');assert.equal(legacy.length,1);assert.equal(legacy[0].stage,'export');
 const entry=(stage:string,commitSha:string,artifactHash=channelHash)=>({recordId:record.id,revision:draft.version,contentHash:draft.contentHash,stage,commitSha,artifactHash,url:'https://archive.example/release.json'});
 const ingest=(entries:unknown[])=>{const body={version:1,observedAt:new Date().toISOString(),entries};return env.app.operations.ingestEvidence({...body,signature:signed(body)});};
 ingest([entry('build',shaA),entry('build',shaB)]);
 assert.throws(()=>ingest([entry('deploy','c'.repeat(40))]),/커밋 SHA/);
 assert.throws(()=>ingest([entry('deploy',shaB,'0'.repeat(64))]),/채널 해시/);
 ingest([entry('deploy',shaA)]);assert.throws(()=>ingest([entry('feed',shaB)]),/커밋 SHA/);
 ingest([entry('deploy',shaB),entry('feed',shaB),entry('feed',shaA)]);
 const entries=[shaA,shaB].flatMap(sha=>['build','deploy','feed'].map(stage=>entry(stage,sha)));assert.equal(ingest(entries).accepted,6);
 assert.equal(env.store.get('SELECT count(*) AS count FROM publication_release_stages')?.count,6);assert.deepEqual(env.store.all('SELECT * FROM publication_stages'),legacy);
 const progress=env.app.operations.publication(reviewer,draft.id);assert.ok(Array.isArray(progress.stages));assert.equal(progress.stages.length,7);
 for(const sha of [shaA,shaB])assert.deepEqual(progress.stages.filter(value=>object(value).commitSha===sha).map(value=>object(value).stage).sort(),['build','deploy','feed']);
 const correction=env.app.editorial.correction(null,{recordId:record.id,category:'test',proposal:'Actual second release correction',consent:true},'test'),id=String(correction.receiptId),stage=env.store.get("SELECT id FROM publication_release_stages WHERE commit_sha=? AND stage='feed'",shaB);assert.ok(stage);
 env.app.editorial.moderate(reviewer,id,{status:'accepted',note:'Accept for review'},'test');env.app.editorial.moderate(reviewer,id,{status:'resolved',note:'Second release verified',revision:draft.version,publicationId:stage.id,closureEvidence:'Actual matching release evidence'},'test');
 assert.equal(env.store.get('SELECT publication_id FROM correction_release_closures WHERE correction_id=?',id)?.publication_id,stage.id);assert.equal(env.app.editorial.corrections(reviewer).items.find(item=>item.receiptId===id)?.publicationId,stage.id);
});
test('legacy release evidence and its correction foreign keys remain compatible after additive release migration',async t=>{
 const env=await fixture(t),{draft,reviewer}=await env.publish(),sha='d'.repeat(40),artifactHash=hash('legacy-channel'),url='https://archive.example/release.json',observedAt=new Date().toISOString();
 for(const stage of ['build','deploy','feed'])env.store.run('INSERT INTO publication_stages VALUES (?,?,?,?,?,?,?,?,?,?)',`legacy-${stage}`,String(record.id),draft.version,draft.contentHash,stage,sha,artifactHash,url,observedAt,'signed-deployment-observation');
 const legacy=env.store.all('SELECT * FROM publication_stages'),body={version:1,observedAt,entries:['build','deploy','feed'].map(stage=>({recordId:record.id,revision:draft.version,contentHash:draft.contentHash,stage,commitSha:sha,artifactHash,url}))};assert.equal(env.app.operations.ingestEvidence({...body,signature:signed(body)}).accepted,3);assert.equal(env.store.get('SELECT count(*) AS count FROM publication_release_stages')?.count,0);assert.deepEqual(env.store.all('SELECT * FROM publication_stages'),legacy);
 const correction=env.app.editorial.correction(null,{recordId:record.id,category:'test',proposal:'Compatible legacy correction',consent:true},'test'),id=String(correction.receiptId);env.app.editorial.moderate(reviewer,id,{status:'accepted',note:'Accept for review'},'test');env.app.editorial.moderate(reviewer,id,{status:'resolved',note:'Legacy release verified',revision:draft.version,publicationId:'legacy-feed',closureEvidence:'Actual legacy feed evidence'},'test');assert.equal(env.store.get('SELECT publication_id FROM correction_closures WHERE correction_id=?',id)?.publication_id,'legacy-feed');assert.equal(env.app.editorial.corrections(reviewer).items.find(item=>item.receiptId===id)?.publicationId,'legacy-feed');
 assert.equal(env.store.get('PRAGMA quick_check')?.quick_check,'ok');assert.equal(env.store.all('PRAGMA foreign_key_check').length,0);
});
test('notification supplier acknowledgement remains accepted until a signed receipt and rejects forged or reordered final statuses',async t=>{
 const adapters=disabledAdapters();adapters.notifications={enabled:true,send:async()=>{}};const env=await fixture(t,{},adapters);env.app.editorial.importTrustedLocalSnapshot({version:1,records:[record]},'test');const correction=env.app.editorial.correction(null,{recordId:record.id,category:'test',proposal:'test',consent:true},'test');assert.ok(correction.receiptId);await env.app.worker.tick();const row=env.store.get('SELECT job_id,status FROM notification_deliveries');assert.equal(row?.status,'accepted');assert.equal(env.store.get('SELECT payload FROM jobs')?.payload,'{"providerAccepted":true}');
 const body={version:1,eventId:'provider-event-1',jobId:row?.job_id,status:'delivered',observedAt:new Date().toISOString()};const send=async(value:unknown,signature:string)=>{const response=await fetch(env.url+'/api/v1/notifications/receipts',{method:'POST',headers:{'Content-Type':'application/json','X-Archive-Signature':signature},body:JSON.stringify(value)});return {status:response.status,body:object(await response.json())};};assert.equal((await send(body,'0'.repeat(64))).status,403);assert.equal((await send(body,signed(body,env.config.notificationReceiptSecret))).status,200);assert.equal((await send(body,signed(body,env.config.notificationReceiptSecret))).status,200);const late={...body,eventId:'provider-event-2',status:'failed'};assert.equal((await send(late,signed(late,env.config.notificationReceiptSecret))).status,409);
});
test('order fulfillment has separate optimistic lifecycle and only its customer can confirm delivery',async t=>{
 const adapters=disabledAdapters();adapters.payments={enabled:true,createCheckout:async()=>({sessionId:'test-session',url:'https://checkout.stripe.com/test'}),verifyWebhook:async()=>null,refund:async()=>({refundId:'r',status:'pending'})};const env=await fixture(t,{},adapters),customer=await env.account('customer'),other=await env.account('other'),reviewer=await env.account('reviewer','reviewer');const checkout=await env.app.commerce.checkout(customer,{productId:'course',idempotencyKey:'checkout-key'},'test'),id=String(checkout.orderId);assert.throws(()=>env.app.operations.fulfill(reviewer,id,{version:0,status:'in-progress',deliveryNote:''},'test'),/결제/);env.app.commerce.applyEvent({eventId:'paid-event',type:'test',orderId:id,sessionId:'test-session',status:'paid',amountMinor:1000,currency:'usd'});
 const staff=await env.client(reviewer),owner=await env.client(customer),stranger=await env.client(other);assert.equal((await staff.request(`/api/v1/payments/orders/${id}/fulfillment`,'PUT',{version:0,status:'in-progress',deliveryNote:'Processing'})).status,200);assert.equal((await owner.request(`/api/v1/payments/orders/${id}/fulfillment/confirm`,'POST',{version:1})).status,409);assert.equal((await staff.request(`/api/v1/payments/orders/${id}/fulfillment`,'PUT',{version:1,status:'delivered',deliveryNote:'Delivered as agreed',deliveryUrl:'https://archive.example/course'})).status,200);assert.equal((await stranger.request(`/api/v1/payments/orders/${id}/fulfillment/confirm`,'POST',{version:2})).status,404);assert.equal((await owner.request(`/api/v1/payments/orders/${id}/fulfillment/confirm`,'POST',{version:2})).data.status,'confirmed');assert.equal(env.store.get('SELECT status FROM orders WHERE id=?',id)?.status,'paid');
});
test('bundle restoration reconciles later withdrawals, account deletion and role revocation without resurrecting sessions',async t=>{
 const env=await fixture(t),{draft,reviewer,author}=await env.publish(),admin=await env.account('admin','admin'),member=await env.account('member');const bundle=resolve(env.directory,'bundle');await backupBundle(env.store,env.config,bundle);env.app.editorial.transition(reviewer,draft.id,'withhold',{version:draft.version,note:'test withdrawal'},'test');env.app.auth.setRole(admin,author.id,{role:'member'},'test');await env.app.auth.deleteAccount(member,{password},'test');const result=await restoreBundle(env.config,bundle,resolve(env.directory,'restored'),env.store),restored=new Store(result.restoredDatabase);try{assert.equal(restored.get('SELECT record_id FROM public_records WHERE record_id=?',String(record.id)),undefined);assert.equal(restored.get('SELECT deactivated FROM users WHERE id=?',member.id)?.deactivated,1);assert.equal(restored.get('SELECT role FROM users WHERE id=?',author.id)?.role,'member');assert.equal(restored.get('SELECT count(*) AS count FROM sessions')?.count,0);assert.equal(restored.get('SELECT count(*) AS count FROM artifacts')?.count,0);assert.equal(restored.get('PRAGMA quick_check')?.quick_check,'ok');}finally{restored.close();}assert.equal(env.store.get('SELECT role FROM users WHERE id=?',author.id)?.role,'member');
});
test('latency histogram and error SLO survive SQLite restart and do not claim production evidence',async t=>{
 const env=await fixture(t);for(let i=0;i<100;i++)env.app.metrics.observe(i===99?1200:40,i===99?503:200);const second=new Store(env.config.dbPath);try{const result=new MetricsService(second).summary();assert.equal(result.requests,100);assert.equal(result.serverErrors,1);assert.equal(object(result.latencyMs).p95,50);assert.equal(object(result.slo).meetsObservedTarget,false);assert.equal(object(result.slo).productionEvidence,false);}finally{second.close();}
});
test('workboard assigns actual draft, rights, refund and service work with conflicts and permission separation',async t=>{
 const env=await fixture(t),admin=await env.account('admin','admin'),author=await env.account('author','editor'),member=await env.account('member');const draft=env.app.editorial.save(author,null,{record},'test'),client=await env.client(admin);const updated=await client.request(`/api/v1/operations/workboard/draft/${draft.id}`,'PUT',{version:0,assigneeId:author.id,priority:'urgent',dueAt:new Date(Date.now()+86400000).toISOString(),nextAction:'Check source'});assert.equal(updated.data.version,1);assert.equal((await client.request(`/api/v1/operations/workboard/draft/${draft.id}`,'PUT',{version:0,assigneeId:null,priority:'normal',dueAt:null,nextAction:'stale'})).error?.code,'VERSION_CONFLICT');assert.equal((await (await env.client(member)).request('/api/v1/operations/workboard')).status,403);const board=await client.request('/api/v1/operations/workboard');assert.ok(Array.isArray(board.data.items));assert.equal(object(board.data.items[0]).priority,'urgent');
});
test('scanned private evidence verifies the exact bytes and detailed rights require real clean evidence',async t=>{
 const env=await fixture(t),reviewer=await env.account('reviewer','reviewer');env.app.editorial.importTrustedLocalSnapshot({version:1,records:[record]},'test');assert.ok(Array.isArray(record.sources));const source=object(record.sources[0]),bytes=Buffer.from('%PDF-1.7\nverified test-only file\n%%EOF\n');const attachment=await env.app.attachments.upload(reviewer,{recordId:record.id,sourceId:source.id,rights:'Test permission evidence'},bytes,'application/pdf','test');assert.equal(attachment.scanStatus,'unknown');const organization=env.app.institutions.save(reviewer,'organizations',null,{title:'Test institution',website:'https://archive.example',status:'active'},'test');const rights={organizationId:organization.id,recordId:record.id,sourceId:source.id,usage:'test usage',status:'granted',note:'test document',permissions:['teaching'],territory:'KR',attribution:'Test attribution',documentId:attachment.attachmentId};assert.throws(()=>env.app.institutions.save(reviewer,'rights',null,rights,'test'),/보안 검사/);
 const receipt={version:1,attachmentId:attachment.attachmentId,sha256:attachment.sha256,status:'clean',scanner:'test-scanner',observedAt:new Date().toISOString()};assert.throws(()=>env.app.receipts.scan(receipt,'0'.repeat(64)),/서명/);env.app.receipts.scan(receipt,signed(receipt,env.config.fileScanSecret));const grant=env.app.institutions.save(reviewer,'rights',null,rights,'test');assert.equal(grant.scopeVerified,true);const mismatched={...receipt,sha256:'0'.repeat(64)};assert.throws(()=>env.app.receipts.scan(mismatched,signed(mismatched,env.config.fileScanSecret)),/원본/);const blocked={...receipt,status:'rejected',observedAt:new Date(Date.now()+10).toISOString()};env.app.receipts.scan(blocked,signed(blocked,env.config.fileScanSecret));await assert.rejects(env.app.attachments.download(reviewer,String(attachment.attachmentId),'test'),/차단/);
});
test('real service inquiries keep owner data private and require actual quote, contract and customer order before fulfillment',async t=>{
 const env=await fixture(t),owner=await env.account('owner'),other=await env.account('other'),reviewer=await env.account('reviewer','reviewer'),client=await env.client(owner),staff=await env.client(reviewer),stranger=await env.client(other);const created=await client.request('/api/v1/service-requests','POST',{title:'Institution class',audience:'Teachers',deliverables:['Teaching kit'],rights:'School use',deadline:new Date(Date.now()+86400000).toISOString()});assert.equal(created.status,200);const id=String(created.data.id);assert.equal((await stranger.request(`/api/v1/service-requests/${id}`)).status,404);assert.equal((await client.request(`/api/v1/service-requests/${id}`,'PUT',{version:1,status:'qualified'})).status,403);assert.equal((await staff.request(`/api/v1/service-requests/${id}`,'PUT',{version:1,status:'qualified',assignedTo:reviewer.id})).status,200);assert.equal((await staff.request(`/api/v1/service-requests/${id}`,'PUT',{version:2,status:'quoted'})).error?.code,'QUOTE_REQUIRED');assert.equal((await staff.request(`/api/v1/service-requests/${id}`,'PUT',{version:2,status:'quoted',quoteNote:'Actual test quote'})).status,200);assert.equal((await staff.request(`/api/v1/service-requests/${id}`,'PUT',{version:3,status:'contracted'})).error?.code,'SERVICE_CONTRACT_REQUIRED');assert.equal((await client.request(`/api/v1/service-requests/${id}`)).data.status,'quoted');
});
test('service inquiry assignment requires an active finance manager rather than a customer or read-only employee',async t=>{
 const env=await fixture(t),owner=await env.account('owner'),manager=await env.account('manager','reviewer'),readOnly=await env.account('read-only','reviewer'),editor=await env.account('editor','editor'),staff=await env.client(manager);
 env.store.run('INSERT INTO user_scope_settings VALUES (?,?,?)',readOnly.id,JSON.stringify(['finance:read']),new Date().toISOString());
 const inquiry=env.app.services.create(owner,{title:'School request',audience:'Teachers',deliverables:['Teaching kit'],rights:'Classroom use'},'test'),path=`/api/v1/service-requests/${String(inquiry.id)}`;
 for(const assignee of [owner,readOnly,editor])assert.equal((await staff.request(path,'PUT',{version:1,status:'qualified',assignedTo:assignee.id})).error?.code,'ASSIGNEE_SCOPE_REQUIRED');
 assert.equal(env.app.services.get(owner,String(inquiry.id)).version,1);assert.equal((await staff.request(path,'PUT',{version:1,status:'qualified',assignedTo:manager.id})).status,200);
 env.store.run('INSERT INTO user_scope_settings VALUES (?,?,?)',manager.id,JSON.stringify(['finance:read']),new Date().toISOString());
 const replacement=await env.account('replacement','reviewer'),replacementClient=await env.client(replacement);assert.equal((await replacementClient.request(path,'PUT',{version:2,status:'quoted',quoteNote:'Actual quote'})).error?.code,'ASSIGNEE_SCOPE_REQUIRED');assert.equal((await replacementClient.request(path,'PUT',{version:2,status:'quoted',assignedTo:replacement.id,quoteNote:'Actual quote'})).status,200);
});
test('staff inquiry and correction inboxes require MFA while owner lists and anonymous receipts remain available',async t=>{
 const env=await fixture(t,{ARCHIVE_STAFF_MFA_REQUIRED:'true'}),owner=await env.account('owner'),reviewer=await env.account('reviewer','reviewer'),customer=await env.client(owner),staff=await env.client(reviewer),anonymous=await env.client();env.app.editorial.importTrustedLocalSnapshot({version:1,records:[record]},'test');
 const inquiry=await customer.request('/api/v1/service-requests','POST',{title:'School teaching request',audience:'Teachers',deliverables:['Teaching kit'],rights:'Classroom use'}),correction=await customer.request('/api/v1/corrections','POST',{recordId:record.id,category:'Source clarification',proposal:'Please review this passage against the original source.',contactEmail:owner.email,consent:true});assert.equal(inquiry.status,200);assert.equal(correction.status,201);const id=String(inquiry.data.id),receiptId=String(correction.data.receiptId);
 assert.equal((await customer.request('/api/v1/service-requests')).status,200);assert.equal((await customer.request(`/api/v1/service-requests/${id}`)).status,200);const ownCorrections=await customer.request('/api/v1/corrections');assert.equal(ownCorrections.status,200);assert.ok(Array.isArray(ownCorrections.data.items));assert.equal(object(ownCorrections.data.items[0]).contactEmail,undefined);assert.equal((await anonymous.request(`/api/v1/corrections/${receiptId}`)).status,200);
 for(const path of ['/api/v1/service-requests',`/api/v1/service-requests/${id}`,'/api/v1/corrections'])assert.equal((await staff.request(path)).error?.code,'MFA_REQUIRED');assert.equal((await staff.request(`/api/v1/corrections/${receiptId}/status`,'POST',{status:'triaged',note:'Checking actual evidence'})).error?.code,'MFA_REQUIRED');
 const enrollment=await staff.request('/api/v1/auth/mfa/enroll','POST',{password}),code=totp(decodeBase32(String(enrollment.data.secret)),Math.floor(Date.now()/30000));assert.equal((await staff.request('/api/v1/auth/mfa/confirm','POST',{code})).status,200);assert.equal((await staff.request('/api/v1/service-requests')).status,200);const inbox=await staff.request('/api/v1/corrections');assert.equal(inbox.status,200);assert.ok(Array.isArray(inbox.data.items));assert.equal(object(inbox.data.items[0]).contactEmail,owner.email);assert.equal((await staff.request(`/api/v1/corrections/${receiptId}/status`,'POST',{status:'triaged',note:'Checking actual evidence'})).status,200);
});
test('live payment catalogue rejects undefined deliverables and AI citation details come only from selected versioned records',async t=>{
 assert.throws(()=>readConfig({ARCHIVE_PAYMENT_LIVE_ENABLED:'true',ARCHIVE_PRODUCTS_JSON:JSON.stringify([{id:'p',title:'Incomplete',amountMinor:100,currency:'usd'}])}),/납품/);
 const adapters=disabledAdapters();let calls=0;adapters.ai={enabled:true,publicEnabled:true,answer:async input=>{calls++;return {text:'Test answer',citations:[{recordId:input.records[0].id,sectionId:input.records[0].sections[0].id}],citationDetails:[]};}};const env=await fixture(t,{},adapters),member=await env.account('member');env.app.editorial.importTrustedLocalSnapshot({version:1,records:[record]},'test');const answer=await env.app.ai.answer(member,{mode:'answer',recordIds:[record.id],question:'test'},'test');assert.ok(answer.citationDetails?.[0].excerpt);assert.equal(answer.citationDetails?.[0].contentHash,hash(JSON.stringify(env.app.editorial.publicRecords()[0])));adapters.ai.evaluationContentHash='0'.repeat(64);await assert.rejects(env.app.ai.answer(member,{mode:'answer',recordIds:[record.id],question:'test'},'test'),/평가/);assert.equal(calls,1);assert.equal(env.store.get('SELECT reserved_calls FROM ai_daily_usage')?.reserved_calls,1);
});
test('staff offboarding revokes sessions and pending approval jobs cannot publish after reviewer access removal',async t=>{
 const env=await fixture(t),admin=await env.account('admin','admin'),author=await env.account('author','editor'),reviewer=await env.account('reviewer','reviewer'),publisher=await env.account('publisher','publisher'),staffClient=await env.client(reviewer);let draft=env.app.editorial.save(author,null,{record},'test');draft=env.app.editorial.transition(author,draft.id,'submit',{version:draft.version},'test') as typeof draft;draft=env.app.editorial.transition(reviewer,draft.id,'source-check',{version:draft.version,note:'test'},'test') as typeof draft;draft=env.app.editorial.transition(reviewer,draft.id,'approve',{version:draft.version,contentHash:draft.contentHash,note:'test'},'test') as typeof draft;env.app.editorial.transition(publisher,draft.id,'publish',{version:draft.version},'test');env.app.security.offboard(admin,reviewer.id,'test');assert.equal((await staffClient.request('/api/v1/shelf')).status,401);await env.app.worker.tick();assert.equal(env.store.get('SELECT record_id FROM public_records'),undefined);assert.equal(env.store.get('SELECT error_code FROM jobs')?.error_code,'APPROVAL_REVIEWER_UNAVAILABLE');
});
test('scoped institution service advances from genuine contract and payment through delivery and customer confirmation, then stops when rights are withdrawn',async t=>{
 const adapters=disabledAdapters();adapters.payments={enabled:true,createCheckout:async()=>({sessionId:'test-session',url:'https://checkout.stripe.com/test'}),verifyWebhook:async()=>null,refund:async()=>({refundId:'r',status:'pending'})};const env=await fixture(t,{},adapters),customer=await env.account('customer'),reviewer=await env.account('reviewer','reviewer');env.app.editorial.importTrustedLocalSnapshot({version:1,records:[record]},'test');assert.ok(Array.isArray(record.sources));const source=object(record.sources[0]),attachment=await env.app.attachments.upload(reviewer,{recordId:record.id,sourceId:source.id,rights:'Test permission document'},Buffer.from('%PDF-1.7\ntest-only document\n%%EOF\n'),'application/pdf','test');const scan={version:1,attachmentId:attachment.attachmentId,sha256:attachment.sha256,status:'clean',scanner:'test-scanner',observedAt:new Date().toISOString()};env.app.receipts.scan(scan,signed(scan,env.config.fileScanSecret));const organization=env.app.institutions.save(reviewer,'organizations',null,{title:'Test institution',status:'active'},'test'),grantInput={organizationId:organization.id,recordId:record.id,sourceId:source.id,usage:'Test teaching use',status:'granted',note:'Test signed permission',permissions:['teaching'],territory:'KR',attribution:'Test attribution',documentId:attachment.attachmentId},grant=env.app.institutions.save(reviewer,'rights',null,grantInput,'test'),contract=env.app.institutions.save(reviewer,'contracts',null,{organizationId:organization.id,title:'Test agreement',status:'active',note:'Test executed contract',requiredRightsIds:[grant.id],requiredPermissions:['teaching'],territory:'KR'},'test');assert.equal(contract.scopeVerified,true);
 const request=env.app.services.create(customer,{title:'Test class',audience:'Teachers',deliverables:['Kit'],rights:'Teaching only'},'test'),id=String(request.id);env.app.services.update(reviewer,id,{version:1,status:'qualified'},'test');env.app.services.update(reviewer,id,{version:2,status:'quoted',quoteNote:'Test actual quote'},'test');const checkout=await env.app.commerce.checkout(customer,{productId:'course',idempotencyKey:'service-checkout'},'test'),orderId=String(checkout.orderId);env.app.services.update(reviewer,id,{version:3,status:'contracted',contractId:contract.id,orderId},'test');assert.throws(()=>env.app.services.update(reviewer,id,{version:4,status:'fulfilling'},'test'),/결제/);env.app.commerce.applyEvent({eventId:'paid',type:'test',orderId,sessionId:'test-session',status:'paid',amountMinor:1000,currency:'usd'});env.app.services.update(reviewer,id,{version:4,status:'fulfilling'},'test');env.app.operations.fulfill(reviewer,orderId,{version:0,status:'in-progress',deliveryNote:'Building kit'},'test');env.app.operations.fulfill(reviewer,orderId,{version:1,status:'delivered',deliveryNote:'Delivered teaching kit'},'test');env.app.services.update(reviewer,id,{version:5,status:'delivered',evidence:'Test actual delivery'},'test');assert.throws(()=>env.app.services.update(reviewer,id,{version:6,status:'closed',evidence:'Test completion'},'test'),/고객 확인/);env.app.operations.fulfill(customer,orderId,{version:2},'test',true);assert.equal(env.app.services.update(reviewer,id,{version:6,status:'closed',evidence:'Customer confirmed delivery'},'test').status,'closed');env.app.institutions.save(reviewer,'rights',String(grant.id),{...grantInput,version:1,status:'withdrawn'},'test');const row=env.store.get('SELECT * FROM contracts WHERE id=?',String(contract.id));assert.ok(row);assert.equal(env.app.institutions.contractReadiness(row).operationallyReady,false);
});
test('purpose secrets stay separate and production startup cannot bypass MFA or a valid registry',async t=>{
 const env=await fixture(t);assert.throws(()=>readConfig({ARCHIVE_DEPLOYMENT_EVIDENCE_SECRET:secret,ARCHIVE_FILE_SCAN_SECRET:secret}),/분리/);assert.throws(()=>readConfig({ARCHIVE_KNOWLEDGE_FILE:resolve(env.directory,'missing.json')}),/레지스트리/);const file=resolve(env.directory,'registry.json');await writeFile(file,await readFile(new URL('../../web/content/knowledge.json',import.meta.url),'utf8'));const config=readConfig({NODE_ENV:'production',ARCHIVE_API_ALLOWED_ORIGINS:'https://archive.example',ARCHIVE_API_SESSION_SECRET:'test-production-session-'.repeat(3),ARCHIVE_SECURITY_ENCRYPTION_KEY:'12'.repeat(32),ARCHIVE_KNOWLEDGE_FILE:file,ARCHIVE_STAFF_MFA_REQUIRED:'false',ARCHIVE_RECENT_REAUTH_REQUIRED:'false'});assert.equal(config.staffMfaRequired,true);assert.equal(config.recentReauthRequired,true);
});
