import { isArchiveRecord, isPublicRecord } from "../lib/archive-domain.ts";
import { readArchiveContent } from "./read-archive-content.mjs";

const { records: archiveRecords } = await readArchiveContent();
const idPosition = process.argv.indexOf("--id");
const requestedId = idPosition >= 0 ? process.argv[idPosition + 1] : undefined;
if (idPosition >= 0 && !requestedId) throw new Error("Provide a record ID after --id.");
const records = requestedId ? archiveRecords.filter((record) => record.id === requestedId) : archiveRecords;
if (requestedId && !records.length) throw new Error(`Record not found: ${requestedId}`);
const rows = records.map((record) => ({
  id: record.id,
  title: record.title,
  status: record.review?.status || "invalid",
  humanReviewed: record.review?.humanReviewed === true,
  public: isArchiveRecord(record) && isPublicRecord(record),
  sources: record.sources?.length || 0,
  updatedAt: record.updatedAt
}));
console.table(rows);
if (requestedId) {
  const record = records[0];
  console.log(JSON.stringify({ review: record.review, limitations: record.limitations, sources: record.sources, sections: record.sections.map(({ id, title, sourceIds }) => ({ id, title, sourceIds })) }, null, 2));
}
console.log("Human approval is never generated by this command. Check claims, independent sources, rights and date precision before editing review status in the private editorial workflow.");
if (process.argv.includes("--gate")) {
  const invalid = archiveRecords.filter((record) => !isArchiveRecord(record));
  if (invalid.length) throw new Error(`Editorial gate failed for: ${invalid.map((record) => record.id || "unknown").join(", ")}`);
  console.log(`Editorial schema gate passed; ${rows.filter((row) => row.public).length} selected public records. This is not human fact verification.`);
}
