"use client";
import { LoginReturnLink } from "./personal-context";
import { useState } from "react";
import { formatMoney, parseMoney, refundBalances } from "../../lib/commerce-domain";
import { useRecoveryDraft } from "./local-draft";
import { StaffSecurity } from "./staff-security";
import { InstitutionRequests } from "./institution-requests";
import { apiAvailable, apiItems, apiNumber, apiObject, apiRequest, apiString, decodeOrderReceipt, decodePaymentOrder, decodePaymentProduct, decodeRefundRequest, safeApiMessage, verifiedCheckoutUrl, type PaymentOrder, type PaymentOrderReceipt, type PaymentProduct, type RefundRequest } from "../../lib/api-client";
import { useApiSession } from "./expansion-common";

const statusNames: Record<string, string> = { pending: "결제 상태 확인 대기", "checkout-ready": "결제창 준비됨", paid: "서버 결제 확인", unknown: "공급자 결과 확인 필요", failed: "실패", cancelled: "취소", refunded: "환불 확인", "partially-refunded": "일부 환불 확인", "refund-pending": "환불 확인 대기", requested: "환불 검토 접수", rejected: "환불 요청 반려" };
function statusName(status: string): string { return statusNames[status] ?? "서버 상태 확인 필요"; }
function money(amount: number, currency: string): string { try { return formatMoney(amount, currency); } catch { return `${amount} (금액 단위 확인 필요) ${currency}`; } }
type OperationKeys = { ownerId: string; orderKeys: Record<string, string>; refundKeys: Record<string, string> };
function decodeKeys(value: unknown): OperationKeys { const item = apiObject(value); const map = (value: unknown): Record<string, string> => { const entries = Object.entries(apiObject(value)); if (entries.length > 500 || entries.some(([key, value]) => !/^[a-zA-Z0-9_-]{1,100}$/.test(key) || ["__proto__", "constructor", "prototype"].includes(key) || typeof value !== "string" || !/^[a-zA-Z0-9_-]{1,100}$/.test(value))) throw new Error("결제 요청 복구 키를 확인하세요."); return Object.fromEntries(entries) as Record<string, string>; }; return { ownerId: apiString(item.ownerId, 100), orderKeys: map(item.orderKeys), refundKeys: map(item.refundKeys) }; }
async function refundKeyName(orderId: string, amount: number, reason: string): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify([orderId, amount, reason]))); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, "0")).join(""); }
function CheckoutLink({ raw }: { raw: string }) { const verified = verifiedCheckoutUrl(raw); return verified ? <a href={verified} target="_blank" rel="noopener noreferrer">실제 Stripe 결제창 열기 ↗</a> : raw ? <p>결제 주소의 제공자를 확인할 수 없어 링크를 표시하지 않았습니다.</p> : null; }
export function InstitutionServices() {
  const { session, error, loading, refresh } = useApiSession(); const [products, setProducts] = useState<PaymentProduct[]>([]); const [orders, setOrders] = useState<PaymentOrder[]>([]);
  const [order, setOrder] = useState<PaymentOrder | null>(null); const [created, setCreated] = useState<PaymentOrderReceipt | null>(null);
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [checkedProducts, setCheckedProducts] = useState(false); const [productEnabled, setProductEnabled] = useState(false);
  const [refundAmount, setRefundAmount] = useState(""); const [refundReason, setRefundReason] = useState(""); const [receipt, setReceipt] = useState<RefundRequest | null>(null);
  const keys = useRecoveryDraft<OperationKeys>(`services:requests:${session?.user?.id ?? "guest"}`, () => ({ ownerId: session?.user?.id ?? "guest", orderKeys: {}, refundKeys: {} }), decodeKeys);
  const enabled = session?.capabilities.payments === true && productEnabled;
  const canRefund = session?.user?.scopes ? session.user.scopes.includes("finance:manage") : ["reviewer", "admin"].includes(session?.user?.role ?? "");
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (problem) { setMessage(safeApiMessage(problem)); } finally { setBusy(false); } }
  async function readOrder(id: string) { setOrder(await apiRequest(`/payments/orders/${id}`, {}, decodePaymentOrder)); }
  function chooseOrder(item: PaymentOrder) { setOrder(item); setCreated(null); setReceipt(null); setRefundAmount(""); setRefundReason(""); }
  const balances = order ? refundBalances(order) : null;
  const remaining = balances?.available ?? 0;
  return <div className="expansionManager">
    <p role="status">{message || error || (loading ? "상품과 서비스 정책을 확인하고 있습니다." : "")}</p><StaffSecurity /><InstitutionRequests canManage={canRefund} /><p role="status">{keys.error || keys.status}</p>
    {!apiAvailable ? <p className="expansionNotice">기관 서비스 API가 연결되지 않았습니다. 등록 상품과 실제 결제를 제공하지 않습니다.</p> : <>
      <div className="expansionActions"><button disabled={busy} type="button" onClick={() => void run(async () => { const catalog = await apiRequest("/payments/products", {}, apiObject); setProducts(apiItems(catalog).map(decodePaymentProduct)); setProductEnabled(catalog.enabled === true); setCheckedProducts(true); setMessage("서버에 등록된 실제 상품을 확인했습니다."); })}>실제 기관 상품 확인</button><button disabled={busy || loading} type="button" onClick={() => void refresh()}>서비스 상태 다시 확인</button></div>
      {checkedProducts && !products.length ? <p>현재 운영자가 등록한 기관 상품이 없습니다. 기본 자료는 계속 열람할 수 있습니다.</p> : null}
      {!enabled ? <p>상품과 실제 결제 공급자의 활성 상태를 확인한 후 주문할 수 있습니다.</p> : null}
      {!session?.user ? <p><LoginReturnLink /> 후 본인 주문과 접수 상태를 관리할 수 있습니다.</p> : null}
      <ul className="expansionList">{products.map(product => <li key={product.id}><div><h2>{product.title}</h2><p>{money(product.amountMinor, product.currency)}</p>{product.serviceDefinition ? <div><p>{product.serviceDefinition.description}</p><p>대상: {product.serviceDefinition.audience} · 제공 일정: {product.serviceDefinition.deliveryDays}일</p><ul>{product.serviceDefinition.deliverables.map(item => <li key={item}>{item}</li>)}</ul><p>이용 권리: {product.serviceDefinition.rightsStatement}</p><p>문의·지원: {product.serviceDefinition.supportPolicy}</p></div> : <p>제공 범위와 이용 조건을 운영자에게 확인하세요.</p>}</div><button disabled={busy || !session?.user || !enabled || !keys.ready || keys.blocked} type="button" onClick={() => void run(async () => { const key = keys.value.orderKeys[product.id] ?? crypto.randomUUID(); if (!keys.setValue({ ...keys.value, ownerId: session?.user?.id ?? "guest", orderKeys: { ...keys.value.orderKeys, [product.id]: key } })) { setMessage("결제 요청 키를 복구 저장하지 못했습니다. 기기 저장을 확인한 뒤 주문하세요."); return; } const item = await apiRequest("/payments/orders", { method: "POST", body: { productId: product.id, idempotencyKey: key } }, decodeOrderReceipt); setCreated(item); setOrder(null); setReceipt(null); setMessage("서버에 주문을 만들었습니다. 결제 완료는 서버 상태 조회로 확인하세요."); await readOrder(item.orderId); })}>서버 주문 만들기</button></li>)}</ul>
      {session?.user ? <section><h2>내 주문</h2><button disabled={busy} type="button" onClick={() => void run(async () => { setOrders(await apiRequest("/payments/orders", {}, value => apiItems(value).map(decodePaymentOrder))); setMessage("서버에서 본인 주문 상태를 조회했습니다."); })}>서버 주문 상태 확인</button><ul className="expansionList">{orders.map(item => <li key={item.id}><button type="button" onClick={() => chooseOrder(item)}>{item.id}</button><span>{statusName(item.status)}</span></li>)}</ul></section> : null}
    </>}
    {created && !order ? <section className="expansionNotice"><h2>생성한 주문 {created.orderId}</h2><p>{statusName(created.status)}</p><CheckoutLink raw={created.checkoutUrl} /><button disabled={busy} type="button" onClick={() => void run(() => readOrder(created.orderId))}>생성한 주문 서버 상태 조회</button></section> : null}
    {order ? <section className="expansionNotice"><h2>주문 {order.id}</h2><p>{money(order.amountMinor, order.currency)} · {statusName(order.status)}</p><p>서버 확인 환불 누계 {money(order.refundedMinor, order.currency)}</p><p>검토 중 예약 금액 {money(balances?.reserved ?? 0, order.currency)} · 새 요청 가능 금액 {money(remaining, order.currency)}</p><OrderFulfillment orderId={order.id} canManage={canRefund} /><button disabled={busy || !["paid", "cancelled", "failed", "refunded", "partially-refunded"].includes(order.status)} type="button" onClick={() => { if (!window.confirm("서버의 현재 주문 상태를 확인했습니다. 같은 상품의 별도 새 주문을 준비할까요?")) return; const orderKeys = { ...keys.value.orderKeys }; delete orderKeys[order.productId]; if (keys.setValue({ ...keys.value, orderKeys })) setMessage("이 상품의 별도 새 주문 요청을 준비했습니다."); }}>확인한 주문 이후 별도 새 주문 준비</button>
      {["pending", "checkout-ready", "unknown"].includes(order.status) ? <CheckoutLink raw={order.checkoutUrl} /> : null}
      <p>브라우저의 돌아오기 주소나 완료 문구로 결제 성공을 판단하지 않습니다. 서버가 공급자의 상태를 확인한 결과를 조회하세요.</p>
      <button disabled={busy} type="button" onClick={() => void run(async () => { await readOrder(order.id); setMessage("서버에서 현재 주문 상태를 조회했습니다."); })}>이 주문 서버 상태 조회</button>
      {order.refundRequests.length ? <section><h3>서버의 환불 접수 상태</h3><ul>{order.refundRequests.map(item => <li key={item.requestId}>접수 {item.requestId} · {statusName(item.status)} · {money(item.amountMinor, order.currency)}</li>)}</ul></section> : null}
      {["paid", "partially-refunded"].includes(order.status) && remaining > 0 ? <form onSubmit={event => { event.preventDefault(); let amount: number; try { amount = parseMoney(refundAmount, order.currency); } catch (problem) { setMessage(problem instanceof Error ? problem.message : "금액을 확인하세요."); return; } if (!Number.isSafeInteger(amount) || amount <= 0 || amount > remaining || refundReason.trim().length < 10) { setMessage("환불 가능 금액과 구체적인 사유를 확인하세요."); return; } void run(async () => { const name = await refundKeyName(order.id, amount, refundReason.trim()); const key = keys.value.refundKeys[name] ?? crypto.randomUUID(); if (!keys.setValue({ ...keys.value, refundKeys: { ...keys.value.refundKeys, [name]: key } })) { setMessage("환불 요청 키를 복구 저장하지 못했습니다. 기존 요청 상태를 먼저 확인하세요."); return; } const item = await apiRequest(`/payments/orders/${order.id}/refund-requests`, { method: "POST", body: { amountMinor: amount, reason: refundReason.trim(), idempotencyKey: key } }, decodeRefundRequest); setReceipt(item); setMessage("환불 검토 요청을 접수했습니다. 실제 환불 완료와는 구분됩니다."); }); }}><h3>본인 주문 환불 검토 요청</h3><p>잔액 {money(remaining, order.currency)}. 이미 검토 중인 요청의 예약 금액과 정책은 서버가 다시 확인합니다.</p><label>요청 금액 ({order.currency.toUpperCase()} 표시 단위)<input type="text" inputMode="decimal" value={refundAmount} onChange={event => setRefundAmount(event.target.value)} required /></label><label>요청 사유<textarea minLength={10} maxLength={2000} value={refundReason} onChange={event => setRefundReason(event.target.value)} required /></label><button disabled={busy || !keys.ready || keys.blocked} type="submit">환불 검토 요청 접수</button></form> : null}
      {receipt ? <p role="status">접수번호 {receipt.requestId} · {statusName(receipt.status)} · {money(receipt.amountMinor, order.currency)}. 접수번호를 보관하세요.</p> : null}
    </section> : null}
    {canRefund ? <><OperatorOrderLookup /><RefundReview enabled={enabled} /></> : null}
  </div>;
}
function RefundReview({ enabled }: { enabled: boolean }) {
  const [items, setItems] = useState<RefundRequest[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [notes, setNotes] = useState<Record<string, string>>({});
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (problem) { setMessage(safeApiMessage(problem)); } finally { setBusy(false); } }
  async function refresh() { setItems(await apiRequest("/payments/refund-requests", {}, value => apiItems(value).map(decodeRefundRequest))); }
  return <section><h2>운영자 환불 검토</h2><p>검수자와 관리자만 실제 공급자 환불을 실행할 수 있으며, 서버가 다시 권한과 잔액을 확인합니다. 같은 요청의 재확인은 접수번호를 유지합니다.</p><p role="status">{message}</p><button disabled={busy} type="button" onClick={() => void run(refresh)}>환불 접수 큐 확인</button>{items.map(item => <article className="expansionNotice" key={item.requestId}><h3>접수 {item.requestId}</h3><p>주문 {item.orderId} · {item.amountMinor} (통화 최소단위) · {statusName(item.status)}</p><p className="privateText">{item.reason}</p><button disabled={busy || !enabled || !["requested", "pending", "unknown"].includes(item.status)} type="button" onClick={() => void run(async () => { if (!window.confirm("이 접수번호와 금액으로 실제 공급자 환불을 실행 또는 재확인할까요?")) return; const result = await apiRequest(`/payments/orders/${item.orderId}/refunds`, { method: "POST", body: { amountMinor: item.amountMinor, idempotencyKey: item.requestId } }, apiObject); setMessage(result.status === "refunded" ? "서버가 공급자의 환불을 확인했습니다." : "환불 결과를 확인 중입니다. 동일 접수번호로 다시 확인하세요."); await refresh(); })}>실제 환불 실행·동일 요청 재확인</button><label>반려 검토 사유<textarea maxLength={2000} value={notes[item.requestId] ?? ""} onChange={event => setNotes({ ...notes, [item.requestId]: event.target.value })} /></label><button disabled={busy || item.status !== "requested" || (notes[item.requestId] ?? "").trim().length < 10} type="button" onClick={() => void run(async () => { await apiRequest(`/payments/refund-requests/${item.requestId}/reject`, { method: "POST", body: { note: notes[item.requestId].trim() } }, apiObject); await refresh(); setMessage("환불 요청 반려 사유를 기록했습니다."); })}>검토 요청 반려</button></article>)}</section>;
}
function OperatorOrderLookup() {
  const [orderId, setOrderId] = useState(""); const [selected, setSelected] = useState(""); const [message, setMessage] = useState("");
  return <section><h2>운영자 주문 이행 조회</h2><p>기관 문의와 업무 보드의 실제 주문 ID로 이행을 확인합니다. 서버가 재무 권한을 다시 확인합니다.</p><form onSubmit={event => { event.preventDefault(); if (!/^[a-zA-Z0-9_-]{1,100}$/.test(orderId)) { setMessage("등록된 주문 ID를 입력하세요."); return; } setSelected(orderId); setMessage(""); }}><label>주문 ID<input maxLength={100} value={orderId} onChange={event => setOrderId(event.target.value)} required /></label><button type="submit">주문 이행 열기</button></form><p role="status">{message}</p>{selected ? <OrderFulfillment key={selected} orderId={selected} canManage owner={false} /> : null}</section>;
}
function OrderFulfillment({ orderId, canManage, owner = true }: { orderId: string; canManage: boolean; owner?: boolean }) {
  const [item, setItem] = useState<Record<string, unknown> | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const states: Record<string, string> = { planned: "이행 준비", "in-progress": "서비스 제공 중", delivered: "납품 근거 등록", confirmed: "주문자의 수령 확인", cancelled: "이행 취소" };
  async function refresh() { setItem(await apiRequest(`/payments/orders/${orderId}/fulfillment`, {}, apiObject)); }
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage(safeApiMessage(error)); } finally { setBusy(false); } }
  return <section><h3>주문 서비스 이행</h3><p>결제 확인과 서비스 전달을 별도로 확인합니다.</p><p role="status">{message}</p><button disabled={busy} type="button" onClick={() => void run(refresh)}>이행·수령 상태 확인</button>{item ? <><p>{states[String(item.status)] ?? "미확인"} · 이행 버전 {String(item.version)}</p><p>{typeof item.deliveryNote === "string" ? item.deliveryNote : "납품 근거 없음"}</p>{typeof item.deliveryUrl === "string" && /^https:\/\//.test(item.deliveryUrl) ? <a href={item.deliveryUrl} target="_blank" rel="noopener noreferrer">등록된 결과물 열기 ↗</a> : null}{owner && item.status === "delivered" ? <button disabled={busy} type="button" onClick={() => void run(async () => { if (!window.confirm("실제 결과물을 수령하고 내용을 확인했나요?")) return; setItem(await apiRequest(`/payments/orders/${orderId}/fulfillment/confirm`, { method: "POST", body: { version: apiNumber(item.version) } }, apiObject)); setMessage("주문자의 실제 수령 확인을 서버에 기록했습니다."); })}>결과물 수령·내용 확인</button> : null}{canManage ? <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(async () => { setItem(await apiRequest(`/payments/orders/${orderId}/fulfillment`, { method: "PUT", body: { version: apiNumber(item.version), status: String(data.get("status")), deliveryNote: String(data.get("note") ?? ""), deliveryUrl: String(data.get("url") ?? "").trim() } }, apiObject)); setMessage("실제 이행 단계와 근거를 서버에 저장했습니다."); }); }}><label>이행 다음 단계<select name="status" defaultValue={item.status === "planned" ? "in-progress" : item.status === "in-progress" ? "delivered" : "cancelled"}><option value="in-progress">서비스 제공 시작</option><option value="delivered">실제 납품 근거 등록</option><option value="cancelled">이행 취소</option></select></label><label>제공 범위·납품·취소 근거<textarea name="note" maxLength={5000} defaultValue={typeof item.deliveryNote === "string" ? item.deliveryNote : ""} /></label><label>실제 결과물 HTTPS 주소<input name="url" type="url" maxLength={2000} defaultValue={typeof item.deliveryUrl === "string" ? item.deliveryUrl : ""} /></label><button disabled={busy || ["confirmed", "cancelled"].includes(String(item.status))} type="submit">이행 단계 기록</button></form> : null}</> : null}</section>;
}
