"use client";
import { useState } from "react";
import type { ArchiveRecord } from "../../lib/archive-types";
import { isArchiveRecord } from "../../lib/archive-domain";
import { apiItems, apiNumber, apiObject, apiRequest, apiString, safeApiMessage } from "../../lib/api-client";
import { blankEditorialRecord, cleanRecordEditor, decodeEditorialDraft, editableRecord, editorialChanges, recordEditorIssues, type EditorialDraft } from "../../lib/refinement-admin";
import { ServiceBoundary, useApiSession, downloadExpansion } from "./expansion-common";
import { useRecoveryDraft } from "./local-draft";
import { PrivateEvidenceFiles } from "./expansion-attachments";
import { RecordEditor } from "./record-editor";
import { OperationsWorkboard, PublicationProgress, CorrectionReview } from "./refinement-operations";
import { InstitutionAgreements } from "./institution-agreements";
import { StaffSecurity } from "./staff-security";
import { StaffPermissions, OperationsMetrics } from "./staff-permissions";
import styles from "./refinement-admin.module.css";

type Revision = { version: number; record: ArchiveRecord; state: string; contentHash: string; createdAt: string };
type Editing = { draftId: string; baseVersion: number; json: string; note: string; privateNotes: string };
const emptyEditing = (): Editing => ({ draftId: "", baseVersion: 0, json: "", note: "", privateNotes: "" });
function editingValue(value: unknown): Editing { const item = apiObject(value); return { draftId: apiString(item.draftId, 100), baseVersion: apiNumber(item.baseVersion), json: apiString(item.json, 300000), note: apiString(item.note, 2000), privateNotes: apiString(item.privateNotes, 10000) }; }
const stateNames: Record<string, string> = { draft: "초안", submitted: "검수 대기", "source-checked": "출처 대조", source_checked: "출처 대조", approved: "승인", rejected: "수정 요청", published: "API 공개", withheld: "공개 보류" };
export function AdminManager({ records }: { records: ArchiveRecord[] }) { return <ServiceBoundary><EditorialAdmin records={records} /></ServiceBoundary>; }
function EditorialAdmin({ records }: { records: ArchiveRecord[] }) {
  const { session } = useApiSession(); const role = session?.user?.role; const scopes = session?.user?.scopes; const canEdit = scopes !== undefined ? scopes.includes("content:write") : role === "editor" || role === "admin"; const canReview = scopes !== undefined ? scopes.includes("content:review") : role === "reviewer" || role === "admin"; const canPublish = (scopes !== undefined ? scopes.includes("content:publish") : role === "publisher" || role === "admin") && session?.capabilities.publicationEnabled === true;
  const recovery = useRecoveryDraft<Editing>(`admin:editor:${session?.user?.id ?? "guest"}`, emptyEditing, editingValue); const editing = recovery.value;
  const [drafts, setDrafts] = useState<EditorialDraft[]>([]); const [draft, setDraft] = useState<EditorialDraft | null>(null); const [revisions, setRevisions] = useState<Revision[]>([]); const [acknowledged, setAcknowledged] = useState(""); const [preflight, setPreflight] = useState<Record<string, unknown> | null>(null);
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [showErrors, setShowErrors] = useState(false);
  const formRecord = (() => { try { return editableRecord(JSON.parse(editing.json)); } catch { return null; } })();
  const dirty = Boolean(draft && (JSON.stringify(formRecord) !== JSON.stringify(draft.record) || editing.privateNotes !== draft.privateNotes));
  const currentMatches = draft && editing.draftId === draft.id && editing.baseVersion === draft.version;
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage(safeApiMessage(error)); } finally { setBusy(false); } }
  function updateEditing(patch: Partial<Editing>) { recovery.setValue(value => ({ ...value, ...patch })); setAcknowledged(""); setPreflight(null); }
  function choose(item: EditorialDraft, preserve = false) { if (!preserve && dirty && !window.confirm("편집 중인 내용이 있습니다.복구 초안을 내보내 보관한 뒤 다른 버전을 선택하세요. 현재 편집 내용을 바꿀까요?")) return; setDraft(item); if (!preserve) recovery.setValue({ draftId: item.id, baseVersion: item.version, json: JSON.stringify(item.record, null, 2), note: "", privateNotes: item.privateNotes }); setAcknowledged(""); setPreflight(null); setRevisions([]); }
  async function transition(action: string) {
    if (!draft || !currentMatches) { setMessage("복구된 편집의 원본 서버 버전을 먼저 확인하세요."); return; }
    if (dirty) { setMessage("먼저 편집 내용을 저장하세요. 저장되지 않은 본문을 승인하지 않습니다."); return; }
    if (["source-check", "approve", "reject", "withhold"].includes(action) && editing.note.trim().length < 10) { setMessage("확인한 내용과 사유를 10자 이상 남기세요."); return; }
    if (action === "approve" && acknowledged !== `${draft.version}:${draft.contentHash}`) { setMessage("현재 버전의 본문·근거·변경 내용을 확인했다고 선택하세요."); return; }
    if ((action === "publish" || action === "withhold") && !window.confirm(action === "publish" ? "이 승인 버전의 발행 작업을 요청할까요? 배포 완료는 별도로 확인합니다." : "이 기록을 공개 보류할까요? API에서 제외하고 공개 산출물 갱신 작업을 등록합니다.")) return;
    const result = await apiRequest(`/cms/drafts/${draft.id}/${action}`, { method: "POST", body: { version: draft.version, note: editing.note.trim(), ...(action === "approve" ? { contentHash: draft.contentHash } : {}) } }, apiObject);
    choose(result.record ? decodeEditorialDraft(result) : await apiRequest(`/cms/drafts/${draft.id}`, {}, decodeEditorialDraft));
    setMessage(action === "publish" ? "발행 작업을 접수했습니다. 내보내기·빌드·배포·모바일 확인은 각각 아래에서 확인하세요." : "서버가 검수 단계와 새 버전을 기록했습니다.");
  }
  if (!(scopes !== undefined ? scopes.some(scope => ["content:read", "rights:manage", "operations:manage", "security:manage", "analytics:read"].includes(scope)) : ["editor", "reviewer", "publisher", "admin"].includes(role ?? ""))) return <p>이 화면은 해당 역할의 계정에만 제공됩니다. 실제 권한은 서버에서 다시 확인합니다.</p>;
  return <div className="expansionManager"><p role="status">{message}</p><StaffSecurity /><StaffPermissions /><OperationsMetrics /><ServiceBoundary requiredScope="operations:manage" requiredRole={["editor", "reviewer", "publisher", "admin"]}><OperationsWorkboard onSelectDraft={id => void run(async () => choose(await apiRequest(`/cms/drafts/${id}`, {}, decodeEditorialDraft)))} /></ServiceBoundary>
    <ServiceBoundary requiredScope="content:read" requiredRole={["editor", "reviewer", "publisher", "admin"]}>
    <section><h2>편집할 자료</h2><button disabled={busy} type="button" onClick={() => void run(async () => { setDrafts(await apiRequest("/cms/drafts", {}, value => apiItems(value).map(decodeEditorialDraft))); setMessage("저장된 초안 목록을 확인했습니다."); })}>초안 목록 확인</button><ul className="expansionList">{drafts.map(item => <li key={item.id}><button type="button" disabled={busy} onClick={() => choose(item)}>{item.record.title}</button><span>{stateNames[item.state] ?? item.state} · 버전 {item.version} · {item.updatedAt}</span></li>)}</ul>
      <label>현재 공개 기록을 편집 시작점으로 선택<select defaultValue="" disabled={!canEdit} onChange={event => { const record = records.find(item => item.id === event.target.value); if (record && (!dirty || window.confirm("기존 편집 내용은 내보내기로 먼저 보관하세요. 이 자료로 편집을 시작할까요?"))) { setDraft(null); updateEditing({ draftId: "", baseVersion: 0, json: JSON.stringify(record, null, 2), privateNotes: "", note: "" }); } }}><option value="">기록 선택</option>{records.map(record => <option value={record.id} key={record.id}>{record.title}</option>)}</select></label><button type="button" disabled={!canEdit || busy} onClick={() => { if (dirty && !window.confirm("기존 편집 내용은 내보내기로 먼저 보관하세요. 새 자료를 작성할까요?")) return; setDraft(null); updateEditing({ ...emptyEditing(), json: JSON.stringify(blankEditorialRecord(new Date().toISOString()), null, 2) }); }}>새 자료 작성</button>
    </section>
    <section><h2>기록 전체 편집</h2><p role="status">{recovery.status}{recovery.error ? ` · ${recovery.error}` : ""}</p><p>입력 복구 초안과 실제 서버 초안은 구분됩니다. 아래 서버 저장 버튼을 누를 때 계정 초안의 새 버전을 만듭니다.</p>
      {editing.json ? <div className="expansionActions"><button type="button" onClick={recovery.exportCurrent}>복구 초안 파일로 보관</button>{editing.draftId && !draft ? <button disabled={busy} type="button" onClick={() => void run(async () => { const current = await apiRequest(`/cms/drafts/${editing.draftId}`, {}, decodeEditorialDraft); choose(current, true); setMessage(current.version === editing.baseVersion ? "복구 편집의 원본 버전을 확인했습니다. 입력은 유지했습니다." : "서버에 다른 버전이 있습니다. 복구 편집을 보관하고 아래 변경 비교로 확인하세요. 덮어쓰지 않았습니다."); })}>복구된 초안 서버 버전 확인</button> : null}</div> : <p>기존 자료를 선택하거나 새 자료를 작성하세요.</p>}
      {formRecord ? <RecordEditor record={formRecord} immutableId={Boolean(editing.draftId)} readOnly={!canEdit} showErrors={showErrors} onChange={record => updateEditing({ json: JSON.stringify(record, null, 2) })} /> : editing.json ? <p role="alert">편집 형식을 확인할 수 없습니다. 입력 원본은 유지했습니다. 고급 JSON 또는 복구 파일에서 확인하세요.</p> : null}
      {formRecord ? <details><summary>독자 화면 미리보기</summary><p>현재 편집 입력을 읽기 형태로 확인합니다. 서버 저장·검수·공개 완료 상태와 구분하세요.</p><article className={styles.card}><h2>{formRecord.title || "제목 입력 필요"}</h2><p>{formRecord.summary}</p><p>{formRecord.period} · {formRecord.region} · {formRecord.language}</p>{formRecord.sections.map((section, index) => <section key={`${section.id}-${index}`}><h3>{section.title || "문단 제목 입력 필요"}</h3>{section.paragraphs.map((paragraph, position) => <p key={position}>{paragraph}</p>)}<p>연결 근거: {section.sourceIds.join(", ") || "아직 없음"}{section.interpretation ? " · 편집 해석" : ""}</p></section>)}<section><h3>자료의 한계</h3><ul>{formRecord.limitations.map((line, index) => <li key={index}>{line}</li>)}</ul></section><section><h3>확인할 출처</h3><ul>{formRecord.sources.map((source, index) => <li key={`${source.id}-${index}`}><strong>{source.title}</strong><p>{source.creator} · {source.institution}</p><p>{source.location} · {source.rights}</p><p className={styles.mono}>{source.url}</p></li>)}</ul></section></article></details> : null}
      <details><summary>고급 JSON 가져오기·내보내기</summary><p>전체 계약이 필요한 경우에만 사용하세요. 저장 시 동일한 서버 검증과 버전 확인을 적용합니다.</p><label>기록 JSON<textarea className="jsonEditor" maxLength={300000} readOnly={!canEdit} value={editing.json} onChange={event => updateEditing({ json: event.target.value })} spellCheck={false} /></label><button type="button" onClick={() => downloadExpansion(editing.json, "editorial-input.json")}>편집 본문 JSON 보관</button></details>
      <label>운영자 비공개 편집 메모<textarea maxLength={10000} readOnly={!canEdit} value={editing.privateNotes} onChange={event => updateEditing({ privateNotes: event.target.value })} /></label>
      <button disabled={busy || !canEdit || !editing.json.trim() || recovery.blocked || Boolean(editing.draftId && !currentMatches)} type="button" onClick={() => void run(async () => { setShowErrors(true); const checkedRecord = formRecord ? cleanRecordEditor(formRecord) : null; if (!checkedRecord || recordEditorIssues(checkedRecord).length || !isArchiveRecord(checkedRecord)) { setMessage("기록의 필수 항목과 근거를 확인하세요. 입력은 유지했습니다."); window.setTimeout(() => document.getElementById("cms-errors")?.focus(), 0); return; } const saved = await apiRequest(editing.draftId ? `/cms/drafts/${editing.draftId}` : "/cms/drafts", { method: editing.draftId ? "PUT" : "POST", body: { ...(editing.draftId ? { version: editing.baseVersion } : {}), record: checkedRecord, privateNotes: editing.privateNotes } }, decodeEditorialDraft); choose(saved, true); recovery.setValue({ ...editing, draftId: saved.id, baseVersion: saved.version, json: JSON.stringify(saved.record, null, 2), privateNotes: saved.privateNotes }); setShowErrors(false); setMessage(`서버에 초안 버전 ${saved.version}을 저장했습니다. 검수와 공개 발행은 아직입니다.`); })}>초안 저장</button>
    </section>
    {draft ? <section className="expansionNotice"><h2>버전별 검수</h2><p>상태 {stateNames[draft.state] ?? draft.state} · 서버 버전 {draft.version} · 편집 기준 버전 {editing.baseVersion}</p><p className={styles.mono}>현재 콘텐츠 해시: {draft.contentHash}</p><p className={styles.mono}>승인 해시: {draft.approvedHash || "없음"}</p>
      {!currentMatches ? <p role="alert">편집 기준과 서버 버전이 다릅니다. 복구 입력을 파일로 보관하고 비교한 뒤 새 버전으로 다시 편집하세요.</p> : null}
      {formRecord ? <ChangeComparison before={draft.record} after={formRecord} title="저장되지 않은 편집과 현재 서버 버전 비교" /> : null}
      <button disabled={busy} type="button" onClick={() => void run(async () => { setPreflight(await apiRequest(`/cms/drafts/${draft.id}/preflight`, {}, apiObject)); })}>자료 일치·변경 영향 사전 확인</button>{preflight ? <div><p>현재 서버 버전 사전 검사: {preflight.ready === true ? "통과" : "추가 확인 필요"}</p><ul>{apiItems(preflight.issues ?? []).map((value, index) => { const item = apiObject(value); return <li key={index}>{apiString(item.message, 2000)}</li>; })}</ul><details><summary>연결 자료와 영향 목록</summary><pre className="privateText">{JSON.stringify(preflight.impact, null, 2)}</pre></details></div> : null}
      <label>확인 내용·변경 사유<textarea maxLength={2000} value={editing.note} onChange={event => recovery.setValue(value => ({ ...value, note: event.target.value }))} /></label>
      <label><input type="checkbox" checked={acknowledged === `${draft.version}:${draft.contentHash}`} disabled={!canReview || dirty || !currentMatches} onChange={event => setAcknowledged(event.target.checked ? `${draft.version}:${draft.contentHash}` : "")} />현재 버전 {draft.version}의 본문·근거·한계·변경 내용을 확인했습니다.</label><p>작성자와 다른 검수자가 선택한 불변 버전을 승인합니다. 편집·버전 변경 시 이 확인은 해제됩니다.</p>
      <div className="expansionActions">{[["submit", "검수 제출"], ["source-check", "출처 확인 기록"], ["approve", "독립 사람 승인"], ["reject", "수정 요청"], ["publish", "승인 버전 발행"], ["withhold", "공개 보류"]].map(([action, label]) => <button disabled={busy || dirty || !currentMatches || (action === "submit" ? !canEdit : action === "publish" ? !canPublish : !canReview)} key={action} type="button" onClick={() => void run(() => transition(action))}>{label}</button>)}</div>
      <PublicationProgress draftId={draft.id} />
      <button disabled={busy} type="button" onClick={() => void run(async () => { setRevisions(await apiRequest(`/cms/drafts/${draft.id}/revisions`, {}, value => apiItems(value).map(value => { const item = apiObject(value); if (!isArchiveRecord(item.record)) throw new Error("이력의 자료 계약을 확인할 수 없습니다."); return { version: apiNumber(item.version), record: item.record, state: apiString(item.state, 80), contentHash: apiString(item.contentHash, 200), createdAt: apiString(item.createdAt, 80) }; }))); })}>버전 이력 확인</button>{revisions.map((revision, index) => <details key={revision.version}><summary>버전 {revision.version} · {stateNames[revision.state] ?? revision.state} · {revision.createdAt}</summary><ChangeComparison before={revisions[index + 1]?.record ?? revision.record} after={revision.record} title="직전 저장 버전에서 변경된 내용" /><p className={styles.mono}>{revision.contentHash}</p><button disabled={busy || !canEdit} type="button" onClick={() => void run(async () => { if (!window.confirm("이 과거 본문을 새 초안 버전으로 복구할까요? 현재 버전의 승인은 해제되며 재검수가 필요합니다.")) return; choose(await apiRequest(`/cms/drafts/${draft.id}/restore`, { method: "POST", body: { version: draft.version, revision: revision.version } }, decodeEditorialDraft)); setMessage("새 초안 버전으로 복구했습니다. 검수와 승인을 다시 진행하세요."); })}>이 본문을 새 초안으로 복구</button></details>)}
    </section> : null}
    <PrivateEvidenceFiles key={draft?.record.id ?? "no-record"} record={draft?.record ?? null} />
    <CorrectionReview canReview={canReview} />
    </ServiceBoundary>
    <ServiceBoundary requiredScope="rights:manage" requiredRole={["editor", "reviewer", "admin"]}><InstitutionAgreements records={records} /></ServiceBoundary>
  </div>;
}
function ChangeComparison({ before, after, title }: { before: ArchiveRecord; after: ArchiveRecord; title: string }) { const changes = editorialChanges(before, after); return <details><summary>{title} · {changes.length}개 변경</summary>{!changes.length ? <p>본문과 자료 항목이 같습니다.</p> : changes.map((change, index) => <section key={`${change.field}-${index}`}><h4>{change.field}</h4><div className={styles.diff}><div><strong>이전</strong><pre>{change.before}</pre></div><div><strong>변경 후</strong><pre>{change.after}</pre></div></div></section>)}</details>; }
