"use client";
import { useState } from "react";
import type { ArchiveRecord } from "../../lib/archive-types";
import { apiItems, apiNumber, apiObject, apiRequest, apiString, safeApiMessage } from "../../lib/api-client";
import { useRecoveryDraft } from "./local-draft";
import { useApiSession } from "./expansion-common";
import styles from "./refinement-admin.module.css";

type AgreementForm = { resource: string; id: string; version: number; title: string; website: string; status: string; organizationId: string; recordId: string; sourceId: string; usage: string; note: string; startsAt: string; expiresAt: string; endsAt: string; territory: string; attribution: string; documentId: string; permissions: string[]; requiredRightsIds: string[]; requiredPermissions: string[] };
const initial = (): AgreementForm => ({ resource: "organizations", id: "", version: 0, title: "", website: "", status: "prospect", organizationId: "", recordId: "", sourceId: "", usage: "", note: "", startsAt: "", expiresAt: "", endsAt: "", territory: "", attribution: "", documentId: "", permissions: [], requiredRightsIds: [], requiredPermissions: [] });
function decodeForm(value: unknown): AgreementForm { const item = apiObject(value); const result = initial(); for (const key of Object.keys(result) as (keyof AgreementForm)[]) { if (key === "version") result.version = apiNumber(item.version); else if (key === "permissions" || key === "requiredRightsIds" || key === "requiredPermissions") result[key] = apiItems(item[key] ?? []).map(value => apiString(value, 100)); else result[key] = apiString(item[key], 10000); } if (!["organizations", "rights", "contracts"].includes(result.resource) || result.permissions.some(permission => !["display", "download", "teaching", "commercial", "translation", "adaptation"].includes(permission))) throw new Error("기관 편집 초안을 확인하세요."); return result; }
const states: Record<string, [string, string][]> = { organizations: [["prospect", "검토 중"], ["active", "활성"], ["suspended", "중단"]], rights: [["requested", "허가 요청"], ["granted", "허가 근거 확인"], ["expired", "기한 만료"], ["withdrawn", "철회"]], contracts: [["draft", "초안"], ["review", "검토"], ["active", "유효"], ["ended", "종료"], ["revoked", "취소"]] };
export function InstitutionAgreements({ records }: { records: ArchiveRecord[] }) {
  const { session } = useApiSession();
  const recovery = useRecoveryDraft<AgreementForm>(`admin:agreements:${session?.user?.id ?? "guest"}`, initial, decodeForm); const form = recovery.value;
  const [items, setItems] = useState<Record<string, unknown>[]>([]); const [organizations, setOrganizations] = useState<Record<string, unknown>[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const record = records.find(record => record.id === form.recordId);
  function update(patch: Partial<AgreementForm>) { recovery.setValue(value => ({ ...value, ...patch })); }
  async function refresh() { setItems(await apiRequest(`/${form.resource}`, {}, value => apiItems(value).map(apiObject))); setOrganizations(await apiRequest("/organizations", {}, value => apiItems(value).map(apiObject))); }
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage(safeApiMessage(error)); } finally { setBusy(false); } }
  function choose(item: Record<string, unknown>) { const data = initial(); data.resource = form.resource; data.id = apiString(item.id, 100); data.version = apiNumber(item.version); for (const key of Object.keys(data) as (keyof AgreementForm)[]) { if (["resource", "id", "version", "permissions", "requiredRightsIds", "requiredPermissions"].includes(key)) continue; if (typeof item[key] === "string") data[key as Exclude<keyof AgreementForm, "version" | "permissions" | "requiredRightsIds" | "requiredPermissions">] = String(item[key]); } data.requiredRightsIds = Array.isArray(item.requiredRightsIds) ? item.requiredRightsIds.filter((value): value is string => typeof value === "string") : []; data.requiredPermissions = Array.isArray(item.requiredPermissions) ? item.requiredPermissions.filter((value): value is string => typeof value === "string") : []; data.permissions = Array.isArray(item.permissions) ? item.permissions.filter((entry): entry is string => typeof entry === "string" && ["display", "download", "teaching", "commercial", "translation", "adaptation"].includes(entry)) : []; recovery.setValue(data); }
  return <section><h2>기관·이용 허가·계약</h2><p>자료별 표시·다운로드·재사용 허가와 기간·귀속 문구·허가 문서·철회를 관리합니다. 한 자료에 대한 허가는 기관 전체 자료의 허가로 확대하지 않습니다.</p><p role="status">{message || recovery.error || recovery.status}</p><label>관리 항목<select value={form.resource} onChange={event => { if (form.title || form.note || form.usage) { if (!window.confirm("현재 입력은 복구 파일로 먼저 보관하세요. 관리 항목을 바꿀까요?")) return; } const resource = event.target.value; recovery.setValue({ ...initial(), resource, status: states[resource][0][0] }); setItems([]); }}><option value="organizations">기관</option><option value="rights">자료 이용 허가</option><option value="contracts">기관 계약</option></select></label><div className="expansionActions"><button disabled={busy} type="button" onClick={() => void run(refresh)}>목록 확인</button><button type="button" onClick={() => recovery.setValue({ ...initial(), resource: form.resource, status: states[form.resource][0][0] })}>새 항목 작성</button><button type="button" onClick={recovery.exportCurrent}>현재 입력 파일로 보관</button></div><ul className="expansionList">{items.map(item => <li key={String(item.id)}><button type="button" onClick={() => choose(item)}>{typeof item.title === "string" ? item.title : String(item.sourceId)}</button><span>{String(item.status)} · 버전 {String(item.version)}</span></li>)}</ul>
    <form className={styles.card} onSubmit={event => { event.preventDefault(); void run(async () => { const body: Record<string, unknown> = { ...(form.id ? { version: form.version } : {}), status: form.status }; const iso = (value: string) => value ? new Date(`${value}T00:00:00Z`).toISOString() : null;
      if (form.resource === "organizations") Object.assign(body, { title: form.title.trim(), website: form.website.trim() });
      else { Object.assign(body, { organizationId: form.organizationId, note: form.note.trim(), startsAt: iso(form.startsAt) }); if (form.resource === "rights") Object.assign(body, { recordId: form.recordId, sourceId: form.sourceId, usage: form.usage.trim(), expiresAt: iso(form.expiresAt), permissions: form.permissions, territory: form.territory.trim(), attribution: form.attribution.trim(), documentId: form.documentId.trim() || null }); else Object.assign(body, { title: form.title.trim(), endsAt: iso(form.endsAt), requiredRightsIds: form.requiredRightsIds.map(item => item.trim()).filter(Boolean), requiredPermissions: form.requiredPermissions, territory: form.territory.trim() }); }
      const saved = await apiRequest(form.id ? `/${form.resource}/${form.id}` : `/${form.resource}`, { method: form.id ? "PUT" : "POST", body }, apiObject); choose(saved); await refresh(); setMessage("서버에 기관 항목의 새 버전을 저장했습니다. 등록 상태와 실제 허가 원문을 함께 확인하세요.");
    }); }}><h3>{form.id ? `선택 항목 · 버전 ${form.version}` : "새 기관 항목"}</h3><div className={styles.grid}>
      {form.resource !== "rights" ? <label>{form.resource === "organizations" ? "기관명" : "계약명"}<input required maxLength={200} value={form.title} onChange={event => update({ title: event.target.value })} /></label> : null}
      <label>처리 상태<select value={form.status} onChange={event => update({ status: event.target.value })}>{states[form.resource].map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>
      {form.resource === "organizations" ? <label>기관 공식 URL<input type="url" maxLength={2000} value={form.website} onChange={event => update({ website: event.target.value })} /></label> : <label>계약·허가 기관<select required value={form.organizationId} onChange={event => update({ organizationId: event.target.value })}><option value="">기관 목록 확인 후 선택</option>{organizations.map(item => <option value={String(item.id)} key={String(item.id)}>{String(item.title)} · {String(item.status)}</option>)}</select></label>}
      {form.resource !== "organizations" ? <label>시작일 (UTC)<input type="date" value={form.startsAt.slice(0, 10)} onChange={event => update({ startsAt: event.target.value })} /></label> : null}
      {form.resource === "rights" ? <label>허가 만료일 (UTC)<input type="date" value={form.expiresAt.slice(0, 10)} onChange={event => update({ expiresAt: event.target.value })} /></label> : form.resource === "contracts" ? <label>계약 종료일 (UTC)<input type="date" value={form.endsAt.slice(0, 10)} onChange={event => update({ endsAt: event.target.value })} /></label> : null}
    </div>
    {form.resource === "rights" ? <><label>허가 대상 기록<select required value={form.recordId} onChange={event => update({ recordId: event.target.value, sourceId: "" })}><option value="">기록 선택</option>{records.map(record => <option value={record.id} key={record.id}>{record.title}</option>)}{form.recordId && !record ? <option value={form.recordId}>{form.recordId} · 현재 공개 목록에 없음</option> : null}</select></label><label>허가 대상 원자료<select required value={form.sourceId} onChange={event => update({ sourceId: event.target.value })}><option value="">자료 선택</option>{record?.sources.map(source => <option value={source.id} key={source.id}>{source.title}</option>)}{form.sourceId && !record?.sources.some(source => source.id === form.sourceId) ? <option value={form.sourceId}>{form.sourceId}</option> : null}</select></label><label>구체적인 사용 대상·범위<textarea required maxLength={2000} value={form.usage} onChange={event => update({ usage: event.target.value })} /></label><fieldset><legend>문서로 확인된 허가</legend><div className={styles.checks}>{[["display", "표시"], ["download", "다운로드"], ["teaching", "교육 활용"], ["commercial", "상업 활용"], ["translation", "번역"], ["adaptation", "변형·재구성"]].map(([value, label]) => <label key={value}><input type="checkbox" checked={form.permissions.includes(value)} onChange={event => update({ permissions: event.target.checked ? [...form.permissions, value] : form.permissions.filter(item => item !== value) })} />{label}</label>)}</div></fieldset><div className={styles.grid}><label>허가 적용 지역·매체<input maxLength={200} value={form.territory} onChange={event => update({ territory: event.target.value })} /></label><label>검수 파일로 보관한 허가 문서 ID<input maxLength={100} value={form.documentId} onChange={event => update({ documentId: event.target.value })} /></label></div><label>필수 귀속·출처 표시 문구<textarea maxLength={2000} value={form.attribution} onChange={event => update({ attribution: event.target.value })} /></label></> : null}
    {form.resource === "contracts" ? <><label>계약에 필요한 허가 ID (한 줄에 하나)<textarea value={form.requiredRightsIds.join("\n")} onChange={event => update({ requiredRightsIds: event.target.value.split("\n") })} /></label><label>계약 대상 지역·매체<input maxLength={200} value={form.territory} onChange={event => update({ territory: event.target.value })} /></label><fieldset><legend>계약에 필요한 확인된 이용 범위</legend><div className={styles.checks}>{[["display", "표시"], ["download", "다운로드"], ["teaching", "교육"], ["commercial", "상업"], ["translation", "번역"], ["adaptation", "변형"]].map(([value, label]) => <label key={value}><input type="checkbox" checked={form.requiredPermissions.includes(value)} onChange={event => update({ requiredPermissions: event.target.checked ? [...form.requiredPermissions, value] : form.requiredPermissions.filter(item => item !== value) })} />{label}</label>)}</div></fieldset><p>서버가 각 허가의 대상·기간·지역·권한·문서 검토 상태를 확인합니다. 이용 범위를 지정하지 않은 기존 계약은 실제 서비스 이행의 충분한 근거가 되지 않습니다.</p></> : null}
    {form.resource !== "organizations" ? <label>실제 계약·허가 근거 및 철회 사유<textarea required maxLength={5000} value={form.note} onChange={event => update({ note: event.target.value })} /></label> : null}<button disabled={busy || recovery.blocked} type="submit">항목 저장</button></form>
  </section>;
}
