"use client";
import { useState } from "react";
import { apiItems, apiNumber, apiObject, apiRequest, apiString, safeApiMessage } from "../../lib/api-client";
import { ServiceBoundary, useApiSession } from "./expansion-common";
import { useRecoveryDraft } from "./local-draft";
import styles from "./refinement-admin.module.css";

type Inquiry = { title: string; audience: string; deliverables: string; rights: string; deadline: string };
const initial = (): Inquiry => ({ title: "", audience: "", deliverables: "", rights: "", deadline: "" });
function decodeInquiry(value: unknown): Inquiry { const item = apiObject(value); return { title: apiString(item.title, 200), audience: apiString(item.audience, 2000), deliverables: apiString(item.deliverables, 10000), rights: apiString(item.rights, 2000), deadline: apiString(item.deadline, 100) }; }
const states: Record<string, string> = { received: "요청 접수", qualified: "요구 범위 확인", quoted: "견적 근거 준비", contracted: "실제 계약 연결", fulfilling: "서비스 이행 중", delivered: "납품 근거 등록", closed: "고객 확인·종결" };
export function InstitutionRequests({ canManage }: { canManage: boolean }) { return <ServiceBoundary><Requests canManage={canManage} /></ServiceBoundary>; }
function Requests({ canManage }: { canManage: boolean }) {
  const { session } = useApiSession();
  const recovery = useRecoveryDraft<Inquiry>(`services:inquiry:${session?.user?.id ?? "guest"}`, initial, decodeInquiry); const form = recovery.value; const [items, setItems] = useState<Record<string, unknown>[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { setItems(await apiRequest("/service-requests", {}, value => apiItems(value).map(apiObject))); }
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage(safeApiMessage(error)); } finally { setBusy(false); } }
  const update = (patch: Partial<Inquiry>) => recovery.setValue(value => ({ ...value, ...patch }));
  return <section><h2>기관 서비스 요청·견적·계약 진행</h2><p>필요한 결과물·대상·이용 범위·일정을 먼저 남기세요. 실제 견적·계약·결제·납품은 각각 근거가 확인된 뒤 진행됩니다.</p><p role="status">{message || recovery.error || recovery.status}</p><form className={styles.card} onSubmit={event => { event.preventDefault(); void run(async () => { const deliverables = form.deliverables.split("\n").map(line => line.trim()).filter(Boolean); if (!deliverables.length || deliverables.length > 20 || deliverables.some(line => line.length > 500)) { setMessage("결과물은 한 줄에 하나씩, 최대 20개·각 500자 이하로 입력하세요."); return; } const item = await apiRequest("/service-requests", { method: "POST", body: { title: form.title.trim(), audience: form.audience.trim(), deliverables, rights: form.rights.trim(), ...(form.deadline ? { deadline: new Date(form.deadline).toISOString() } : {}) } }, apiObject); setMessage(`기관 요청 ${apiString(item.id, 100)}을 서버에 접수했습니다. 견적과 계약 완료는 아직입니다.`); await refresh(); }); }}><label>요청 제목<input required maxLength={200} value={form.title} onChange={event => update({ title: event.target.value })} /></label><label>이용 대상과 목적<textarea required maxLength={2000} value={form.audience} onChange={event => update({ audience: event.target.value })} /></label><label>필요한 결과물 (한 줄에 하나)<textarea required maxLength={10000} value={form.deliverables} onChange={event => update({ deliverables: event.target.value })} /></label><label>필요한 이용 범위·권리 조건<textarea required maxLength={2000} value={form.rights} onChange={event => update({ rights: event.target.value })} /></label><label>희망 완료 시점<input type="datetime-local" value={form.deadline} onChange={event => update({ deadline: event.target.value })} /></label><button disabled={busy || recovery.blocked || !recovery.ready} type="submit">기관 요청 접수</button><button type="button" onClick={recovery.exportCurrent}>요청 초안 파일로 보관</button></form><button disabled={busy} type="button" onClick={() => void run(refresh)}>내 요청·관리 가능한 진행 목록 확인</button>
    {items.map(item => <article key={String(item.id)} className={styles.card}><h3>{String(item.title)}</h3><p>{states[String(item.status)] ?? String(item.status)} · 버전 {String(item.version)} · 접수 {String(item.id)}</p><p>{typeof item.audience === "string" ? item.audience : ""}</p>{Array.isArray(item.deliverables) ? <ul>{item.deliverables.map((value, index) => <li key={index}>{String(value)}</li>)}</ul> : null}<p>이용 조건: {typeof item.rights === "string" ? item.rights : "미확인"}</p><p>견적·진행 근거: {typeof item.quoteNote === "string" ? item.quoteNote : "아직 등록되지 않았습니다."}</p><p>종결·납품 근거: {typeof item.evidence === "string" ? item.evidence : "아직 등록되지 않았습니다."}</p>
      {canManage ? <form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); void run(async () => { const due = String(fields.get("dueAt") ?? ""); const body = { version: apiNumber(item.version), status: String(fields.get("status")), assignedTo: String(fields.get("assignedTo") ?? "").trim() || null, dueAt: due ? new Date(due).toISOString() : null, quoteNote: String(fields.get("quoteNote") ?? ""), contractId: String(fields.get("contractId") ?? "").trim() || undefined, orderId: String(fields.get("orderId") ?? "").trim() || undefined, evidence: String(fields.get("evidence") ?? "") }; await apiRequest(`/service-requests/${apiString(item.id, 100)}`, { method: "PUT", body }, apiObject); await refresh(); setMessage("서버가 서비스 진행 단계와 실제 연결 근거를 저장했습니다."); }); }}><label>다음 진행 단계<select name="status" defaultValue={String(item.status) === "received" ? "qualified" : String(item.status)}>{Object.entries(states).filter(([value]) => value !== "received").map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className={styles.grid}><label>담당 운영자 ID<input name="assignedTo" maxLength={100} defaultValue={typeof item.assignedTo === "string" ? item.assignedTo : ""} /></label><label>실제 계약 ID<input name="contractId" maxLength={100} defaultValue={typeof item.contractId === "string" ? item.contractId : ""} /></label><label>요청자 실제 주문 ID<input name="orderId" maxLength={100} defaultValue={typeof item.orderId === "string" ? item.orderId : ""} /></label><label>처리 기한<input name="dueAt" type="datetime-local" /></label></div><label>실제 견적·제공 범위 근거<textarea name="quoteNote" maxLength={5000} defaultValue={typeof item.quoteNote === "string" ? item.quoteNote : ""} /></label><label>실제 납품·고객 확인·종결 근거<textarea name="evidence" maxLength={5000} defaultValue={typeof item.evidence === "string" ? item.evidence : ""} /></label><button disabled={busy || item.status === "closed"} type="submit">진행 단계·근거 저장</button></form> : null}
    </article>)}
  </section>;
}
