"use client";
import Link from "next/link";
import { useState } from "react";
import type { HistoricalDate, KnowledgeLocation, KnowledgeSource } from "../../lib/knowledge-types";
import { formatHistoricalDate } from "../../lib/knowledge-domain";
import { verifiedCoordinates } from "../../lib/knowledge-reading";
import styles from "./knowledge-refinement.module.css";

export const purposeLabels: Record<HistoricalDate["purpose"], string> = { event: "사건 시점", article: "기사·보고 날짜", creation: "작성·제작 시기", publication: "간행 시기", registration: "현대 등록 시기" };
export function KnowledgeChronology({ dates }: { dates: HistoricalDate[] }) {
  const [purpose, setPurpose] = useState(""); const [calendar, setCalendar] = useState("");
  const filtered = dates.filter(date => (!purpose || date.purpose === purpose) && (!calendar || date.calendar === calendar)).sort((a, b) => (a.startYear ?? Infinity) - (b.startYear ?? Infinity));
  return <section className={styles.panel} aria-label="날짜 목적과 역법별 자료 연표"><h2>사건과 기록이 만들어진 시간을 구분합니다.</h2><p>아래는 자료에 연결한 날짜입니다. 기사 날짜·제작 기간·간행·등록 연도는 전투 발생일과 같은 종류의 날짜가 아닙니다.</p><div className={styles.row}><label>날짜의 의미<select value={purpose} onChange={event => setPurpose(event.target.value)}><option value="">전체</option>{Object.entries(purposeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>역법<select value={calendar} onChange={event => setCalendar(event.target.value)}><option value="">전체</option><option value="gregorian">그레고리력</option><option value="julian">율리우스력</option><option value="lunisolar">당시 역법·음력</option><option value="unknown">역법 미확정</option></select></label></div><p role="status">조건에 맞는 날짜 {filtered.length}개</p><ol className={styles.list}>{filtered.map(date => <li key={date.id} id={date.id}><strong>{purposeLabels[date.purpose]} · {date.label}</strong><p>{formatHistoricalDate(date)}</p><p>원자료 표기: {date.originalText}{date.calendar === "lunisolar" && !date.conversion ? " · 현대 달력 환산 미확인" : ""}</p><p>정밀도: {{ day: "자료에 일자 표기", year: "연도", range: "기간", approximate: "추정 범위", unknown: "미상" }[date.precision]} · {date.review.humanReviewed ? "사람 검수 완료" : "사람 검수 대기"}</p>{date.evidence.map((reference, index) => <Link key={`${reference.sourceId}-${index}`} href={`/sources/${reference.sourceId}/`}>{reference.locator} · 근거 확인 → </Link>)}</li>)}</ol>{!filtered.length ? <p>현재 공개 자료에 이 조건의 날짜가 없습니다. 다른 역법으로 자동 환산해 채우지 않습니다.</p> : null}</section>;
}
export function VerifiedPlacesMap({ locations, sources }: { locations: KnowledgeLocation[]; sources: KnowledgeSource[] }) {
  const positioned = verifiedCoordinates(locations, sources);
  return <section className={styles.panel}><h2>좌표와 불확실성</h2><p>등록 장소 {locations.length}곳 · 위치 근거와 사람 검수를 확인한 좌표 {positioned.length}곳. 역사적 경계를 임의로 표시하지 않습니다.</p>{positioned.length ? <figure><svg viewBox="0 0 720 360" className={styles.map} role="img" aria-label="검수한 좌표의 위도·경도 분포"><title>검수한 장소 좌표</title><desc>전투 관련 장소·역사적 지역·소장 위치는 목록에서 구분합니다. 근사 좌표는 윤곽 원으로 표시하며 지리적 경계나 실제 오차 반경을 뜻하지 않습니다.</desc>{positioned.map(location => location.coordinate ? <g key={location.id}><circle cx={360 + location.coordinate.longitude * 1.8} cy={180 - location.coordinate.latitude * 1.8} r={location.coordinate.precision === "approximate" ? 9 : 4} fill={location.coordinate.precision === "approximate" ? "none" : "#983b29"} stroke="#983b29" strokeWidth="2" /><text x={370 + location.coordinate.longitude * 1.8} y={180 - location.coordinate.latitude * 1.8} fontSize="12">{location.label}</text></g> : null)}</svg><figcaption>좌표 분포도이며 지도 투영·국경·검증된 불확실성 반경을 제공하지 않습니다.</figcaption></figure> : <p>현재 공개 자료에 검수한 좌표가 없습니다. 아래 장소 목록에서 명칭·역할·근거를 확인하세요.</p>}<ul className={styles.list}>{locations.map(location => <li key={location.id}><Link href={`/entities/${location.entityId}/`}>{location.label}</Link> · {{ "historical-region": "역사적 지역", "battle-reference": "전투 관련 장소", "custodian-location": "소장 안내 장소" }[location.kind]}<p>{location.uncertainty}</p>{positioned.some(item => item.id === location.id) && location.coordinate ? <p>{location.coordinate.latitude}, {location.coordinate.longitude} · {location.coordinate.precision === "site" ? "해당 위치" : "근사 위치"}</p> : <p>지도 좌표 공개 보류</p>}</li>)}</ul></section>;
}
