"use client";
import { useState } from "react";
import { createLocalBackup, draftStorageKey, localDataKeys, parseLocalBackup, type LocalBackup, type LocalDataKey } from "../../lib/local-draft-storage";
import { emptyShelf, parseShelf, shelfKey } from "../../lib/shelf-storage";
import { workspaceKey } from "../../lib/workspace-domain";
import { downloadExpansion } from "./expansion-common";
import { useShelf } from "./reading-tools";
const names: Record<LocalDataKey, string> = { [shelfKey]: "보관함·개인 메모·열람·설정", [workspaceKey]: "저장한 연구·수업과 교사 전용 메모", [draftStorageKey]: "연구·수업·답안·운영 작업의 복구 초안" };
function notify() { window.dispatchEvent(new Event("archive-shelf-change")); window.dispatchEvent(new Event("archive-workspace-change")); window.dispatchEvent(new Event("archive-local-data-change")); }
export function LocalDataManager() {
  const [selected, setSelected] = useState<LocalDataKey[]>([...localDataKeys]); const [incoming, setIncoming] = useState<LocalBackup | null>(null); const [message, setMessage] = useState(""); const [previous, setPrevious] = useState<LocalBackup | null>(null); const { update } = useShelf();
  function backup() { try { const snapshot = createLocalBackup(key => localStorage.getItem(key), selected, new Date().toISOString()); downloadExpansion(JSON.stringify(snapshot, null, 2), "archive-local-backup.json"); setMessage("선택한 범위를 파일로 보관했습니다. 손상 원본도 파일에 그대로 포함됩니다."); } catch (problem) { setMessage(problem instanceof Error ? problem.message : "기기 저장 접근이 제한되었습니다. 각 화면의 현재 초안 내보내기를 이용하세요."); } }
  return <section aria-labelledby="local-data-title"><h2 id="local-data-title">기기 데이터 백업·복구·범위별 삭제</h2><p>계정 서버와 로그인 쿠키는 이 작업에 포함되지 않습니다. 복구 초안과 교사 메모를 포함한 파일에는 비공개 내용이 있으므로 안전하게 보관하세요.</p><fieldset><legend>내보내거나 지울 범위</legend>{localDataKeys.map(key => <label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={() => setSelected(selected.includes(key) ? selected.filter(item => item !== key) : [...selected, key])} />{names[key]}</label>)}</fieldset><button type="button" disabled={!selected.length} onClick={backup}>선택 범위 통합 백업</button>
    <label>통합 백업 파일 확인<input type="file" accept="application/json,.json" onChange={event => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; void (async () => { try { if (file.size > 7000000) throw new Error("7MB 이하 백업만 확인할 수 있습니다."); setIncoming(parseLocalBackup(await file.text())); setMessage("파일을 검사했습니다. 복구 범위를 확인하기 전에는 기기 데이터를 바꾸지 않습니다."); } catch (problem) { setMessage(problem instanceof Error ? problem.message : "백업을 읽지 못했습니다."); } })(); }} /></label>
    {incoming ? <section className="expansionNotice"><h3>복구 전 범위 확인</h3><p>파일 생성 {incoming.createdAt}</p><ul>{incoming.items.map(item => <li key={item.key}>{names[item.key]} · {item.raw === null ? "빈 상태" : `${item.raw.length.toLocaleString("ko-KR")}자`}</li>)}</ul><p>이 범위의 기존 사본은 교체 전 파일로 보관할 수 있습니다. 개별 연구 충돌 병합은 연구 작업공간의 가져오기를 이용하세요.</p><button type="button" onClick={() => { try { const snapshot = createLocalBackup(key => localStorage.getItem(key), incoming.items.map(item => item.key), new Date().toISOString()); setPrevious(snapshot); downloadExpansion(JSON.stringify(snapshot, null, 2), "archive-before-restore.json"); setMessage("교체 전 기기 원본을 내려받았습니다."); } catch { setMessage("기기 원본을 읽지 못했습니다. 복구를 중단하세요."); } }}>교체 전 원본 보관</button><button type="button" onClick={() => { if (!window.confirm("표시된 범위만 이 백업의 사본으로 교체할까요? 필요한 기존 원본을 먼저 보관하세요.")) return; try { const snapshot = createLocalBackup(key => localStorage.getItem(key), incoming.items.map(item => item.key), new Date().toISOString()); setPrevious(snapshot); downloadExpansion(JSON.stringify(snapshot,null,2),"archive-before-restore.json"); for (const item of incoming.items) { if (item.raw === null) localStorage.removeItem(item.key); else localStorage.setItem(item.key, item.raw); } if (incoming.items.some(item => item.key === shelfKey)) update(() => parseShelf(incoming.items.find(item => item.key === shelfKey)?.raw ?? null), true); notify(); setIncoming(null); setMessage("검사한 범위를 복구했습니다. 연구·수업 화면을 다시 열어 확인하세요."); } catch { setMessage("복구를 끝내지 못했습니다. 일부 범위가 바뀌었을 수 있습니다. 교체 전 원본을 보관하고 저장 공간을 확인하세요."); } }}>표시 범위 복구 실행</button><button type="button" onClick={() => setIncoming(null)}>복구 취소</button></section> : null}
    {previous ? <button type="button" onClick={() => downloadExpansion(JSON.stringify(previous, null, 2), "archive-before-change.json")}>변경 전 원본 다시 보관</button> : null}<p role="status">{message}</p>
    <button type="button" disabled={!selected.length} onClick={() => { if (!window.confirm(`선택한 기기 범위 ${selected.length}개를 지울까요? 서버 자료는 유지됩니다. 필요한 원본을 먼저 백업하세요. 열린 탭의 입력과 로그인은 유지되므로 공용 기기에서는 로그아웃하고 창을 닫으세요.`)) return; try { setPrevious(null); setIncoming(null); for (const key of selected) localStorage.removeItem(key); if (selected.includes(shelfKey)) update(emptyShelf, true); notify(); setMessage("선택한 기기 범위를 지웠습니다. 화면에 열려 있던 초안은 다시 열기 전에 현재 입력을 보관하세요."); } catch { setMessage("기기 삭제를 끝내지 못했습니다. 남아 있는 범위를 확인하세요."); } }}>이 기기 저장 데이터 지우기</button>
  </section>;
}
