"use client";
import type { ArchiveRecord, ArchiveSource, ArchiveSection, ArchiveEntity } from "../../lib/archive-types";
import { recordEditorIssues } from "../../lib/refinement-admin";
import styles from "./refinement-admin.module.css";

const lines = (value: string) => value.split("\n");
export function RecordEditor({ record, onChange, readOnly = false, immutableId = false, showErrors = false }: { record: ArchiveRecord; onChange: (record: ArchiveRecord) => void; readOnly?: boolean; immutableId?: boolean; showErrors?: boolean }) {
  const issues = showErrors ? recordEditorIssues(record) : [];
  const update = (patch: Partial<ArchiveRecord>) => onChange({ ...record, ...patch });
  const sourceUpdate = (index: number, patch: Partial<ArchiveSource>) => update({ sources: record.sources.map((item, position) => position === index ? { ...item, ...patch } : item), sourceCount: record.sources.length });
  const sectionUpdate = (index: number, patch: Partial<ArchiveSection>) => update({ sections: record.sections.map((item, position) => position === index ? { ...item, ...patch } : item) });
  const move = <T,>(items: T[], index: number, direction: number): T[] => { const copy = [...items]; [copy[index], copy[index + direction]] = [copy[index + direction], copy[index]]; return copy; };
  const textField = (key: "title" | "summary" | "period" | "region" | "language", label: string, limit: number, multiline = false) => <label key={key}>{label}{multiline ? <textarea id={`cms-${key}`} maxLength={limit} readOnly={readOnly} value={record[key]} onChange={event => update({ [key]: event.target.value })} aria-invalid={issues.some(issue => issue.target === `cms-${key}`) || undefined} /> : <input id={`cms-${key}`} maxLength={limit} readOnly={readOnly} value={record[key]} onChange={event => update({ [key]: event.target.value })} aria-invalid={issues.some(issue => issue.target === `cms-${key}`) || undefined} />}</label>;
  return <div className={styles.editor}>
    {issues.length ? <div className={styles.error} role="alert" tabIndex={-1} id="cms-errors"><p>저장 전에 {issues.length}개 항목을 확인하세요.</p><ul>{issues.map((issue, index) => <li key={`${issue.target}-${index}`}><a href={`#${issue.target}`} onClick={() => window.setTimeout(() => document.getElementById(issue.target)?.focus(), 0)}>{issue.message}</a></li>)}</ul></div> : null}
    <section className={styles.card} id="cms-basics" tabIndex={-1}><h3>자료 기본 정보</h3><div className={styles.grid}>
      <label>고유 자료 ID<input id="cms-id" maxLength={80} value={record.id} readOnly={readOnly || immutableId} onChange={event => update({ id: event.target.value })} /><small>{immutableId ? "기존 자료 ID와 주소는 유지됩니다." : "한 번 저장한 자료 ID는 변경할 수 없습니다."}</small></label>
      {textField("title", "자료 제목", 300)}{textField("period", "시대 표시", 160)}{textField("region", "지역 표시", 160)}{textField("language", "자료의 언어", 80)}
      <label>자료 종류<select disabled={readOnly} value={record.kind} onChange={event => update({ kind: event.target.value === "source" ? "source" : "event" })}><option value="event">사건 해설</option><option value="source">사료 안내</option></select></label>
      <label>읽기 시간 (분)<input type="number" min={1} max={240} readOnly={readOnly} value={record.readingMinutes} onChange={event => update({ readingMinutes: Number(event.target.value) })} /></label>
    </div>{textField("summary", "핵심 요약", 4000, true)}<div className={styles.grid}><label>주제 (한 줄에 하나)<textarea value={record.labels.join("\n")} readOnly={readOnly} onChange={event => update({ labels: lines(event.target.value) })} /></label><label>검색 별칭 (한 줄에 하나)<textarea value={record.aliases.join("\n")} readOnly={readOnly} onChange={event => update({ aliases: lines(event.target.value) })} /></label></div></section>
    <section className={styles.card} id="cms-date" tabIndex={-1}><h3>사건 연대와 불확실성</h3><p>자료 제작일·기사 날짜와 사건 연대는 구분합니다. 음력 원문을 임의로 양력으로 바꾸지 마세요.</p><div className={styles.grid}><label>시작 연도<input type="number" min={-9999} max={9999} readOnly={readOnly || record.date.precision === "unknown"} value={record.date.startYear ?? ""} onChange={event => update({ date: { ...record.date, startYear: event.target.value === "" ? null : Number(event.target.value) } })} /></label><label>종료 연도<input type="number" min={-9999} max={9999} readOnly={readOnly || record.date.precision === "unknown"} value={record.date.endYear ?? ""} onChange={event => update({ date: { ...record.date, endYear: event.target.value === "" ? null : Number(event.target.value) } })} /></label><label>연대 정밀도<select disabled={readOnly} value={record.date.precision} onChange={event => { const precision = event.target.value as ArchiveRecord["date"]["precision"]; update({ date: precision === "unknown" ? { startYear: null, endYear: null, precision } : { ...record.date, precision } }); }}><option value="unknown">미확인</option><option value="year">연도</option><option value="range">범위</option><option value="approximate">대략적인 시기</option><option value="day">일자 근거 포함</option></select></label></div></section>
    {(["people", "places"] as const).map(kind => <section className={styles.card} key={kind}><h3>{kind === "people" ? "관련 인물" : "관련 장소"}</h3>{record[kind].map((entity, index) => <div key={index} className={styles.grid}><label>개체 ID<input readOnly={readOnly} value={entity.id} onChange={event => update({ [kind]: record[kind].map((item, position) => position === index ? { ...item, id: event.target.value } : item) })} /></label><label>표시 이름<input readOnly={readOnly} value={entity.name} onChange={event => update({ [kind]: record[kind].map((item, position) => position === index ? { ...item, name: event.target.value } : item) })} /></label><label>별칭 (한 줄에 하나)<textarea readOnly={readOnly} value={entity.aliases.join("\n")} onChange={event => update({ [kind]: record[kind].map((item, position) => position === index ? { ...item, aliases: lines(event.target.value) } : item) })} /></label>{!readOnly ? <button type="button" onClick={() => update({ [kind]: record[kind].filter((_, position) => position !== index) })}>{entity.name || "이 항목"} 제외</button> : null}</div>)}{!readOnly ? <button type="button" onClick={() => { const entity: ArchiveEntity = { id: crypto.randomUUID(), name: "", aliases: [] }; update({ [kind]: [...record[kind], entity] }); }}>{kind === "people" ? "인물 추가" : "장소 추가"}</button> : null}</section>)}
    <section className={styles.card} id="cms-sources" tabIndex={-1}><h3>자료·제공기관·이용 권리</h3><p>같은 원자료를 여러 기관이 소개해도 독립된 증언으로 계산하지 않습니다. 원자료 그룹과 구체적인 위치를 입력하세요.</p>{record.sources.map((source, index) => <fieldset id={`cms-source-${index}`} tabIndex={-1} key={index}><legend>자료 {index + 1}</legend><div className={styles.grid}>{([ ["id", "자료 ID"], ["title", "자료 제목"], ["creator", "제작자"], ["institution", "제공기관"], ["url", "공개 기관 자료 URL"], ["location", "권·편·쪽·기사 또는 식별 위치"], ["language", "원자료 언어"], ["independenceGroup", "독립 원자료 그룹"] ] as const).map(([key, label]) => <label key={key}>{label}<input maxLength={key === "url" ? 2000 : 500} type={key === "url" ? "url" : "text"} readOnly={readOnly} value={source[key]} onChange={event => sourceUpdate(index, { [key]: event.target.value })} /></label>)}<label>자료 유형<select disabled={readOnly} value={source.kind} onChange={event => sourceUpdate(index, { kind: event.target.value as ArchiveSource["kind"] })}>{[["primary", "일차 사료"], ["institutional", "기관 해설"], ["research", "연구"], ["testimony", "증언"], ["media", "미디어"]].map(([value, title]) => <option value={value} key={value}>{title}</option>)}</select></label><label>출처 확인일<input type="date" value={source.checkedAt.slice(0, 10)} readOnly={readOnly} onChange={event => sourceUpdate(index, { checkedAt: event.target.value })} /></label><label>자료 제작 시점<input readOnly={readOnly} value={source.created ?? ""} onChange={event => sourceUpdate(index, event.target.value ? { created: event.target.value } : { created: undefined })} /></label></div><label>권리와 이용 범위<textarea maxLength={2000} readOnly={readOnly} value={source.rights} onChange={event => sourceUpdate(index, { rights: event.target.value })} /></label>{!readOnly ? <button type="button" onClick={() => { const sources = record.sources.filter((_, position) => position !== index); update({ sources, sourceCount: sources.length }); }}>자료 {index + 1} 제외</button> : null}</fieldset>)}{!readOnly ? <button type="button" onClick={() => { const sources = [...record.sources, { id: crypto.randomUUID(), title: "", creator: "", institution: "", url: "", location: "", language: "", independenceGroup: "", rights: "", kind: "institutional" as const, checkedAt: new Date().toISOString().slice(0, 10) }]; update({ sources, sourceCount: sources.length }); }}>근거 자료 추가</button> : null}</section>
    <section className={styles.card} id="cms-sections" tabIndex={-1}><h3>본문과 문단별 근거</h3>{record.sections.map((section, index) => <fieldset key={index} id={`cms-section-${index}`} tabIndex={-1}><legend>본문 {index + 1}</legend><label>본문 고유 ID<input readOnly={readOnly} value={section.id} onChange={event => sectionUpdate(index, { id: event.target.value })} /></label><label>본문 소제목<input maxLength={300} readOnly={readOnly} value={section.title} onChange={event => sectionUpdate(index, { title: event.target.value })} /></label><label>문단 (빈 줄로 구분)<textarea maxLength={50000} rows={7} readOnly={readOnly} value={section.paragraphs.join("\n\n")} onChange={event => sectionUpdate(index, { paragraphs: event.target.value.split("\n\n") })} /></label><div className={styles.checks}><label><input type="checkbox" disabled={readOnly} checked={section.interpretation === true} onChange={event => sectionUpdate(index, { interpretation: event.target.checked })} />편집자가 작성한 해석</label>{record.sources.map(source => <label key={source.id}><input type="checkbox" disabled={readOnly} checked={section.sourceIds.includes(source.id)} onChange={event => sectionUpdate(index, { sourceIds: event.target.checked ? [...section.sourceIds, source.id] : section.sourceIds.filter(id => id !== source.id) })} />{source.title || source.id}</label>)}</div>{!readOnly ? <div className="expansionActions"><button disabled={index === 0} type="button" onClick={() => update({ sections: move(record.sections, index, -1) })}>본문 {index + 1} 위로</button><button disabled={index === record.sections.length - 1} type="button" onClick={() => update({ sections: move(record.sections, index, 1) })}>본문 {index + 1} 아래로</button><button type="button" onClick={() => update({ sections: record.sections.filter((_, position) => position !== index) })}>본문 {index + 1} 제외</button></div> : null}</fieldset>)}{!readOnly ? <button type="button" onClick={() => update({ sections: [...record.sections, { id: crypto.randomUUID(), title: "", paragraphs: [""], sourceIds: [], interpretation: true }] })}>본문 문단 추가</button> : null}</section>
    <section className={styles.card} id="cms-chronology" tabIndex={-1}><h3>연표와 근거</h3>{record.chronology.map((moment, index) => <fieldset key={index}><legend>시점 {index + 1}</legend><div className={styles.grid}><label>원문의 날짜 표시<input readOnly={readOnly} value={moment.date} onChange={event => update({ chronology: record.chronology.map((item, position) => position === index ? { ...item, date: event.target.value } : item) })} /></label><label>확인된 연도 (미확인은 비움)<input type="number" readOnly={readOnly} value={moment.year ?? ""} onChange={event => update({ chronology: record.chronology.map((item, position) => position === index ? { ...item, year: event.target.value === "" ? null : Number(event.target.value) } : item) })} /></label><label>연표 제목<input readOnly={readOnly} value={moment.title} onChange={event => update({ chronology: record.chronology.map((item, position) => position === index ? { ...item, title: event.target.value } : item) })} /></label></div><label>연표 설명<textarea readOnly={readOnly} value={moment.text} onChange={event => update({ chronology: record.chronology.map((item, position) => position === index ? { ...item, text: event.target.value } : item) })} /></label><div className={styles.checks}>{record.sources.map(source => <label key={source.id}><input type="checkbox" disabled={readOnly} checked={moment.sourceIds.includes(source.id)} onChange={event => update({ chronology: record.chronology.map((item, position) => position === index ? { ...item, sourceIds: event.target.checked ? [...item.sourceIds, source.id] : item.sourceIds.filter(id => id !== source.id) } : item) })} />{source.title || source.id}</label>)}</div>{!readOnly ? <button type="button" onClick={() => update({ chronology: record.chronology.filter((_, position) => position !== index) })}>시점 {index + 1} 제외</button> : null}</fieldset>)}{!readOnly ? <button type="button" onClick={() => update({ chronology: [...record.chronology, { date: "", year: null, title: "", text: "", sourceIds: [] }] })}>연표 시점 추가</button> : null}</section>
    <section className={styles.card}><h3>한계·읽기 안내·연결</h3><label>자료의 한계 (한 줄에 하나)<textarea maxLength={10000} readOnly={readOnly} value={record.limitations.join("\n")} onChange={event => update({ limitations: lines(event.target.value) })} /></label><label>민감성 안내<textarea maxLength={2000} readOnly={readOnly} value={record.sensitivity ?? ""} onChange={event => update({ sensitivity: event.target.value || undefined })} /></label><label>추천 이유<textarea maxLength={2000} readOnly={readOnly} value={record.featuredReason ?? ""} onChange={event => update({ featuredReason: event.target.value || undefined })} /></label><div className={styles.grid}><label>관련 자료 ID (한 줄에 하나)<textarea readOnly={readOnly} value={record.relatedIds.join("\n")} onChange={event => update({ relatedIds: lines(event.target.value) })} /></label><label>컬렉션 ID (한 줄에 하나)<textarea readOnly={readOnly} value={record.collectionIds.join("\n")} onChange={event => update({ collectionIds: lines(event.target.value) })} /></label></div><details><summary>기록 자체의 정정 이력</summary>{record.corrections.map((correction, index) => <fieldset key={index}><legend>정정 {index + 1}</legend><label>정정일<input type="date" readOnly={readOnly} value={correction.date.slice(0, 10)} onChange={event => update({ corrections: record.corrections.map((item, position) => position === index ? { ...item, date: event.target.value } : item) })} /></label><label>정정 내용<textarea readOnly={readOnly} value={correction.reason} onChange={event => update({ corrections: record.corrections.map((item, position) => position === index ? { ...item, reason: event.target.value } : item) })} /></label>{!readOnly ? <button type="button" onClick={() => update({ corrections: record.corrections.filter((_, position) => position !== index) })}>정정 {index + 1} 제외</button> : null}</fieldset>)}{!readOnly ? <button type="button" onClick={() => update({ corrections: [...record.corrections, { date: new Date().toISOString().slice(0, 10), reason: "" }] })}>정정 이력 추가</button> : null}</details><p>검수자·승인·수정 버전·자료 개수는 서버와 등록 자료에서 확정합니다.</p></section>
  </div>;
}
