"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { apiItems, apiNumber, apiObject, apiRequest, apiString, safeApiMessage } from "../../lib/api-client";
import { decodePublicationSnapshot, publicationProgress, selectedPublicationRelease } from "../../lib/publication-progress";
import type { PublicationSnapshot, PublicationStage } from "../../lib/publication-progress";
import styles from "./refinement-admin.module.css";

const names: Record<string, string> = { draft: "편집", order: "주문 이행", "service-request": "기관 문의", correction: "정정", rights: "자료 권리", refund: "환불", job: "자동 작업", notification: "알림", normal: "보통", low: "낮음", high: "높음", urgent: "긴급", pending: "대기", running: "처리 중", completed: "완료", failed: "실패", accepted: "공급자 접수", delivered: "전달 확인", expired: "기한 만료", export: "승인 내보내기", build: "정적 빌드", deploy: "공개 사이트 확인", feed: "모바일 배포 자료 확인" };
function localDateTime(value: string): string { const date = new Date(value); if (!Number.isFinite(date.getTime())) return ""; const pad = (n: number) => String(n).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
const named = (value: unknown) => typeof value === "string" ? names[value] ?? value : "미확인";
export function OperationsWorkboard({ onSelectDraft }: { onSelectDraft: (id: string) => void }) {
  const [assignees, setAssignees] = useState<Record<string, unknown>[]>([]); const [items, setItems] = useState<Record<string, unknown>[]>([]); const [jobs, setJobs] = useState<Record<string, unknown>[]>([]); const [checked, setChecked] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { setAssignees(await apiRequest("/operations/assignees", {}, value => apiItems(value).map(apiObject))); setItems(await apiRequest("/operations/workboard", {}, value => apiItems(value).map(apiObject))); setJobs(await apiRequest("/jobs", {}, value => apiItems(value).map(apiObject))); setChecked(true); }
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage(safeApiMessage(error)); } finally { setBusy(false); } }
  return <section><h2>운영 업무 보드</h2><p>담당자·기한·다음 작업을 기록하고 지연된 업무를 확인하세요. 실패 작업은 사유에 따라 재시도·새 요청·재검수를 선택합니다.</p><p role="status">{message}</p><button disabled={busy} type="button" onClick={() => void run(refresh)}>운영 큐 확인</button>{checked && !items.length ? <p>현재 처리할 업무가 없습니다.</p> : null}
    {items.map((item, index) => <article key={String(item.kind) + String(item.id ?? index)} className={styles.card}><h3>{named(item.kind)} · {typeof item.title === "string" ? item.title : String(item.id)}</h3><p>상태 {named(item.status ?? item.state)} · {typeof item.createdAt === "string" ? item.createdAt : "등록 시점 확인 필요"}</p>{item.overdue === true ? <p role="status">처리 기한이 지났습니다.</p> : null}{item.kind === "draft" ? <button type="button" onClick={() => onSelectDraft(apiString(item.id, 100))}>자료 편집·검수 열기</button> : null}{["refund", "order", "service-request"].includes(String(item.kind)) ? <Link href="/services/">기관 문의·주문·환불 처리로 이동 →</Link> : null}
      <form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); void run(async () => { const date = String(fields.get("dueAt") ?? ""); await apiRequest(`/operations/workboard/${apiString(item.kind, 80)}/${apiString(item.id, 100)}`, { method: "PUT", body: { version: typeof item.version === "number" ? apiNumber(item.version) : 0, assigneeId: String(fields.get("assigneeId") ?? "").trim() || null, priority: String(fields.get("priority")), dueAt: date ? new Date(date).toISOString() : null, nextAction: String(fields.get("nextAction") ?? "").trim() } }, apiObject); await refresh(); setMessage("업무 담당·기한·다음 작업을 서버에 저장했습니다."); }); }}><div className={styles.grid}><label>담당 운영자<select name="assigneeId" defaultValue={typeof item.assigneeId === "string" ? item.assigneeId : ""}><option value="">담당자 미정</option>{assignees.map(person => <option key={String(person.id)} value={String(person.id)}>{String(person.name)}</option>)}</select></label><label>우선순위<select name="priority" defaultValue={typeof item.priority === "string" ? item.priority : "normal"}><option value="normal">보통</option><option value="low">낮음</option><option value="high">높음</option><option value="urgent">긴급</option></select></label><label>처리 기한<input type="datetime-local" name="dueAt" defaultValue={typeof item.dueAt === "string" ? localDateTime(item.dueAt) : ""} /></label></div><label>다음에 할 작업<textarea name="nextAction" maxLength={2000} defaultValue={typeof item.nextAction === "string" ? item.nextAction : ""} /></label><button disabled={busy} type="submit">업무 정보 저장</button></form>
    </article>)}
    {jobs.length ? <section><h3>발행·알림 작업과 복구</h3>{jobs.map((job, index) => <article className={styles.card} key={String(job.id ?? index)}><h4>{named(job.kind)} · {named(job.status)}</h4><p>시도 횟수 {typeof job.attempts === "number" ? job.attempts : "미확인"} · 오류 코드 {typeof job.errorCode === "string" ? job.errorCode : "없음"}</p><p>다음 처리 {typeof job.nextAt === "string" ? job.nextAt : "미확인"}</p>{job.kind === "notification" ? <p>작업 접수나 공급자의 수신 응답은 실제 전달 확인과 구분합니다. 전달 상태: {named(job.deliveryStatus)}</p> : null}{job.status === "failed" ? <button disabled={busy || ["APPROVAL_STALE", "APPROVAL_REQUIRED", "RESET_EXPIRED", "INVALID_JOB", "INVALID_RECORD"].includes(String(job.errorCode))} type="button" onClick={() => void run(async () => { await apiRequest(`/jobs/${apiString(job.id, 100)}/retry`, { method: "POST" }, apiObject); await refresh(); setMessage("동일 작업의 재시도를 접수했습니다. 완료 상태를 다시 확인하세요."); })}>같은 작업 재시도</button> : null}{job.errorCode === "RESET_EXPIRED" ? <Link href="/account/">새 비밀번호 재설정 안내 요청 →</Link> : null}{["APPROVAL_STALE", "APPROVAL_REQUIRED"].includes(String(job.errorCode)) ? <p>자료의 현재 버전을 다시 검수·승인한 뒤 발행하세요.</p> : null}</article>)}</section> : null}
  </section>;
}
export function PublicationProgress({ draftId }: { draftId: string }) {
  return <PublicationProgressPanel key={draftId} draftId={draftId} />;
}
function PublicationProgressPanel({ draftId }: { draftId: string }) {
  const [item, setItem] = useState<PublicationSnapshot | null>(null); const [selectedKey, setSelectedKey] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const latestRequest = useRef(0);
  const progress = item ? publicationProgress(item) : { exportEvidence: null, releases: [] };
  const release = selectedPublicationRelease(progress.releases, selectedKey);
  function refresh() {
    const request = ++latestRequest.current;
    setBusy(true); setItem(null); setMessage("");
    void apiRequest(`/cms/drafts/${draftId}/publication`, {}, decodePublicationSnapshot).then(snapshot => {
      if (request !== latestRequest.current) return;
      const releases = publicationProgress(snapshot).releases;
      setSelectedKey(previous => selectedPublicationRelease(releases, previous)?.key ?? "");
      setItem(snapshot);
    }).catch(error => { if (request === latestRequest.current) setMessage(safeApiMessage(error)); }).finally(() => { if (request === latestRequest.current) setBusy(false); });
  }
  const stages: PublicationStage[] = ["export", "build", "deploy", "feed"];
  return <section><h3>실제 발행 단계 확인</h3><p>독립 승인 후 내보내기·빌드·공개 사이트·모바일 자료가 같은 버전인지 확인합니다. 확인 증거가 없는 단계는 완료로 표시하지 않습니다.</p><p role="status">{busy ? "현재 발행 단계 증거를 확인하고 있습니다." : message}</p><button disabled={busy} type="button" onClick={refresh}>발행 단계 증거 확인</button>{item ? <><p>자료 {item.recordId} · 현재 버전 {item.revision}</p>{release ? <div className={styles.card}><label>표시할 릴리스<select value={release.key} onChange={event => setSelectedKey(event.target.value)}>{progress.releases.map((entry, index) => <option key={entry.key} value={entry.key}>{index + 1} · SHA {entry.commitSha.slice(0, 12)} · 산출물 {entry.artifactHash.slice(0, 12)} · {entry.latestObservedAt}</option>)}</select></label><p>확인된 릴리스 {progress.releases.length}개입니다. 최근 증거부터 표시하며 선택한 SHA와 산출물 해시의 단계만 묶습니다.</p><p className={styles.mono}>선택한 배포 SHA {release.commitSha}</p><p className={styles.mono}>선택한 산출물 해시 {release.artifactHash}</p></div> : <p>현재 버전의 빌드·배포·모바일 자료 릴리스 증거가 없습니다.</p>}<ol>{stages.map(stage => { const evidence = stage === "export" ? progress.exportEvidence : release?.stages[stage]; return <li key={stage}><strong>{named(stage)}</strong> · {evidence ? stage === "export" ? "현재 버전의 공통 내보내기 확인" : "선택 릴리스의 현재 버전 확인" : stage === "export" || !release ? "현재 버전 확인 증거 없음" : "선택 릴리스 확인 증거 없음"}{evidence ? <><p className={styles.mono}>증거 {evidence.id} · 버전 {evidence.revision} · 확인 시각 {evidence.observedAt}</p><p className={styles.mono}>배포 SHA {evidence.commitSha ?? "해당 없음"} · 산출물 해시 {evidence.artifactHash}</p></> : null}</li>; })}</ol><p className={styles.mono}>현재 자료 해시 {item.contentHash}</p></> : null}</section>;
}
export function CorrectionReview({ canReview }: { canReview: boolean }) {
  const [items, setItems] = useState<Record<string, unknown>[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { setItems(await apiRequest("/corrections", {}, value => apiItems(value).map(apiObject))); }
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage(safeApiMessage(error)); } finally { setBusy(false); } }
  return <section><h2>정정 검토 큐</h2><p>수락·수정 준비·공개 반영·답변을 구분합니다. 처리 완료에는 실제 반영 버전·배포 확인 증거·종결 근거가 모두 필요합니다.</p><p role="status">{message}</p><button disabled={busy} type="button" onClick={() => void run(refresh)}>접수 목록 확인</button>{items.map((item, index) => <article className={styles.card} key={String(item.receiptId ?? index)}><h3>{typeof item.receiptId === "string" ? item.receiptId : "접수"}</h3><p>자료 {String(item.recordId)} · 상태 {String(item.status)}</p><p className="privateText">{typeof item.proposal === "string" ? item.proposal : "제안 본문 확인 권한이 필요합니다."}</p>{typeof item.evidenceUrl === "string" && item.evidenceUrl ? <p>제안 근거 주소: {item.evidenceUrl}</p> : null}{typeof item.moderationNote === "string" ? <p>검토 사유: {item.moderationNote}</p> : null}
      <form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); void run(async () => { const revision = String(fields.get("revision") ?? ""); await apiRequest(`/corrections/${apiString(item.receiptId, 120)}/status`, { method: "POST", body: { status: String(fields.get("status")), note: String(fields.get("note")), ...(revision ? { revision: Number(revision) } : {}), publicationId: String(fields.get("publicationId") ?? "").trim(), closureEvidence: String(fields.get("closureEvidence") ?? "").trim() } }, apiObject); await refresh(); setMessage("서버가 정정 처리 상태와 근거를 기록했습니다."); }); }}><label>처리 상태<select name="status"><option value="triaged">검토 분류 완료</option><option value="accepted">반영 승인</option><option value="resolved">증거를 확인한 처리 완료</option><option value="rejected">반영하지 않음</option></select></label><label>처리 사유<textarea name="note" minLength={10} maxLength={2000} required /></label><div className={styles.grid}><label>실제 반영 초안 버전<input type="number" min={1} step={1} name="revision" /></label><label>공개 확인 증거 ID<input name="publicationId" maxLength={100} /></label></div><label>변경된 문단·종결 근거<textarea name="closureEvidence" maxLength={4000} /></label><button disabled={busy || !canReview || ["resolved", "rejected"].includes(String(item.status))} type="submit">상태와 반영 근거 기록</button></form>
    </article>)}</section>;
}
