import Link from "next/link";
import type { ArchiveRecord } from "../../lib/archive-types";
import type { ResearchProject } from "../../lib/workspace-domain";
import { sitePath } from "../site-config";
export function ResearchReviewPanel({ project, records, onChange, pending, setPending }: { project: ResearchProject; records: ArchiveRecord[]; onChange: (project: ResearchProject) => void; pending: string; setPending: (value: string) => void }) {
  const evidence = project.claims.flatMap(claim => claim.evidence.map(item => ({ item, claim: claim.statement })));
  const changed = evidence.filter(({ item }) => { const record = records.find(record => record.id === item.recordId); return !record || record.updatedAt !== item.recordVersion || (item.snapshot && item.snapshot.sourceUrl && record.sources.find(source => source.id === item.sourceId)?.url !== item.snapshot.sourceUrl); });
  return <section className="expansionNotice" aria-label="연구 확인 작업"><h3>다음 확인 작업</h3><p>근거 없는 주장 {project.claims.filter(claim => !claim.evidence.length).length}개 · 변경·공개 보류 확인 대상 {changed.length}개</p><ul>{project.claims.filter(claim => !claim.evidence.length).map(claim => <li key={claim.id}>근거를 연결할 주장: {claim.statement || "작성 중"}</li>)}{(project.nextChecks ?? []).map((item, index) => <li key={`${index}-${item}`}>{item}<button type="button" onClick={() => onChange({ ...project, nextChecks: project.nextChecks?.filter((_, position) => position !== index) })}>확인 작업 마침</button></li>)}</ul><label>다음에 확인할 일<input maxLength={1000} value={pending} onChange={event => setPending(event.target.value)}/></label><button type="button" disabled={!pending.trim() || (project.nextChecks?.length ?? 0) >= 30} onClick={() => { onChange({ ...project, nextChecks: [...(project.nextChecks ?? []), pending.trim()] }); setPending(""); }}>확인 작업 추가</button>
    {evidence.map(({ item, claim }) => { const record = records.find(record => record.id === item.recordId); return <details key={item.id}><summary>{item.snapshot?.recordTitle ?? record?.title ?? item.recordId} · 추가 당시 근거와 버전</summary><p>주장: {claim}</p><p>근거 추가 {item.capturedAt} · 참조 버전 {item.recordVersion}</p><p>{record ? record.updatedAt === item.recordVersion ? "현재 공개 기록과 참조 버전이 같습니다. 사실성과 해석의 승인을 뜻하지 않습니다." : "공개 기록이 수정되었습니다. 기존 인용·메모는 변경하지 않았습니다." : "현재 공개 목록에 없습니다. 기존 근거와 저장 ID는 보존했습니다."}</p>{item.snapshot ? <><p>당시 제목: {item.snapshot.recordTitle}</p><p>당시 자료: {item.snapshot.sourceTitle || "연결 자료 미지정"} · {item.snapshot.origin === "editorial" ? "아카이브 편집 내용에서 시작" : "외부 자료 연결에서 시작"}</p><p>당시 자료 주소: {item.snapshot.sourceUrl || "미지정"}</p><p className="privateText">당시 기록 요약: {item.snapshot.summary}</p></> : <p>이전 형식의 근거에는 상세 스냅샷이 없습니다. 작성한 내용과 버전 정보는 유지했습니다.</p>}<p className="privateText">{item.text}</p>{record ? <Link href={`/archive/${record.id}/?returnTo=${encodeURIComponent(sitePath(`/workspace/?project=${project.id}`))}${item.snapshot?.sectionId && record.sections.some(section => section.id === item.snapshot!.sectionId) ? `#${item.snapshot.sectionId}` : ""}`}>현재 기록을 읽고 확인하기 →</Link> : null}</details>; })}
  </section>;
}
