"use client";
import { useState } from "react";
import { apiItems, apiObject, apiRequest, apiString, safeApiMessage } from "../../lib/api-client";
import { useApiSession } from "./expansion-common";
import styles from "./refinement-admin.module.css";

const scopes = [["content:read", "편집 자료 열람"], ["content:write", "초안 작성"], ["content:review", "독립 검수"], ["content:publish", "공개 발행"], ["rights:manage", "자료 권리 관리"], ["finance:read", "주문·환불 열람"], ["finance:manage", "환불·이행 관리"], ["operations:manage", "업무 배정·작업 복구"], ["analytics:read", "운영 지표 열람"], ["security:manage", "권한·계정 보호 관리"]] as const;
export function StaffPermissions() {
  const { session } = useApiSession(); const [users, setUsers] = useState<Record<string, unknown>[]>([]); const [user, setUser] = useState<Record<string, unknown> | null>(null); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  if (session?.user?.scopes !== undefined ? !session.user.scopes.includes("security:manage") : session?.user?.role !== "admin") return null;
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage(safeApiMessage(error)); } finally { setBusy(false); } }
  return <details className={styles.card}><summary>직원 업무 범위·인수인계·접근 종료</summary><p>콘텐츠·권리·재무·보안 업무를 필요한 범위로 분리합니다. 변경 시 해당 계정의 기존 로그인은 폐기됩니다. 역할 변경만으로 개별 업무 범위를 자동 확대하지 않습니다.</p><p role="status">{message}</p><button disabled={busy} type="button" onClick={() => void run(async () => { setUsers(await apiRequest("/admin/users", {}, value => apiItems(value).map(apiObject))); })}>활성 계정 목록 확인</button><label>관리할 계정<select value={typeof user?.id === "string" ? user.id : ""} onChange={event => { const target = users.find(item => item.id === event.target.value); if (!target) return; void run(async () => { const policy = await apiRequest(`/admin/users/${apiString(target.id, 100)}/scopes`, {}, apiObject); setUser(target); setSelected(apiItems(policy.scopes).map(value => apiString(value, 80))); setMessage(policy.explicit === true ? "명시한 업무 범위를 불러왔습니다." : "기존 역할과 호환되는 업무 범위입니다. 명시적으로 필요한 항목만 선택하세요."); }); }}><option value="">계정 선택</option>{users.map(item => <option key={String(item.id)} value={String(item.id)}>{String(item.name)} · {String(item.role)}</option>)}</select></label>
    {user ? <section><h3>{String(user.name)}의 업무 범위</h3><p>계정 ID {String(user.id)}</p><fieldset><legend>허용할 업무</legend><div className={styles.checks}>{scopes.map(([scope, label]) => <label key={scope}><input type="checkbox" checked={selected.includes(scope)} onChange={event => setSelected(event.target.checked ? [...selected, scope] : selected.filter(item => item !== scope))} />{label}</label>)}</div></fieldset><button disabled={busy} type="button" onClick={() => void run(async () => { if (!window.confirm("선택한 업무 범위로 변경하고 해당 계정의 기존 로그인을 종료할까요? 현재 본인의 권한을 바꾸면 다시 로그인해야 합니다.")) return; await apiRequest(`/admin/users/${apiString(user.id, 100)}/scopes`, { method: "PUT", body: { scopes: selected } }, apiObject); setMessage("업무 범위를 저장하고 기존 세션을 폐기했습니다. 본인 계정이면 다시 로그인하세요."); })}>선택 업무 범위 저장</button><form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const role = String(data.get("role")); void run(async () => { if (!window.confirm("계정의 역할을 바꾸고 기존 로그인을 종료할까요? 명시한 업무 범위는 함께 확인해야 합니다.")) return; await apiRequest(`/admin/users/${apiString(user.id, 100)}/role`, { method: "PUT", body: { role } }, apiObject); setMessage("계정 역할을 변경했습니다. 현재 업무 범위를 다시 확인하세요."); }); }}><label>계정 역할<select name="role" defaultValue={String(user.role)}>{[["member", "일반 회원"], ["editor", "편집자"], ["reviewer", "검수자"], ["publisher", "발행자"], ["admin", "관리자"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button disabled={busy} type="submit">계정 역할 변경</button></form><p>공동 공간 소유자는 인수인계 후 접근을 종료할 수 있습니다. 마지막 관리자와 본인 계정의 접근 종료는 서버에서 보호합니다.</p><button disabled={busy || user.id === session?.user?.id} type="button" onClick={() => void run(async () => { if (!window.confirm("이 계정의 업무 접근을 종료할까요? 로그인·재설정 코드를 폐기합니다. 소유한 공동 공간은 먼저 이전해야 합니다.")) return; await apiRequest(`/admin/users/${apiString(user.id, 100)}/offboard`, { method: "POST" }, apiObject); setUser(null); setUsers(previous => previous.filter(item => item.id !== user.id)); setMessage("직원 계정 접근과 기존 인증 수단을 종료했습니다."); })}>인수인계 후 계정 접근 종료</button></section> : null}
  </details>;
}
export function OperationsMetrics() {
  const { session } = useApiSession(); const [metrics, setMetrics] = useState<Record<string, unknown> | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  if (session?.user?.scopes !== undefined ? !session.user.scopes.includes("analytics:read") : session?.user?.role !== "admin") return null;
  return <details className={styles.card}><summary>운영 지표·서비스 목표</summary><p>실제 요청의 오류율·지연 분포·작업 적체를 확인합니다. 이 환경의 측정과 실제 운영 서비스의 달성 증거는 구분합니다.</p><p role="status">{message}</p><button disabled={busy} type="button" onClick={() => { setBusy(true); void apiRequest("/operations/metrics", {}, apiObject).then(setMetrics).catch(error => setMessage(safeApiMessage(error))).finally(() => setBusy(false)); }}>현재 지표 확인</button>{metrics ? <><dl><dt>24시간 요청 수</dt><dd>{typeof metrics.requests === "number" ? metrics.requests : "미확인"}</dd><dt>서버 오류율</dt><dd>{typeof metrics.errorRate === "number" ? `${(metrics.errorRate * 100).toFixed(2)}%` : "측정 자료 없음"}</dd><dt>공개 기록 수</dt><dd>{typeof metrics.publicRecordCount === "number" ? metrics.publicRecordCount : "미확인"}</dd></dl><details><summary>응답 시간 분포·작업 큐·AI 예산</summary><pre className="privateText">{JSON.stringify({ latency: metrics.latencyMs, jobs: metrics.jobs, aiUsage: metrics.aiDailyUsage, dailyRequestLimit: metrics.aiDailyRequestLimit }, null, 2)}</pre></details><p>응답 시간은 히스토그램 구간의 상한으로 표시합니다. 요청이 적으면 목표 달성 여부를 확정하지 않습니다. 운영 목표는 측정 기준선을 확인한 뒤 조정하세요.</p></> : null}</details>;
}
