"use client";
import { useState } from "react";
import { apiObject, apiRequest, safeApiMessage } from "../../lib/api-client";
import { useApiSession } from "./expansion-common";
import styles from "./refinement-admin.module.css";

export function StaffSecurity() {
  const { session, refresh } = useApiSession(); const [state, setState] = useState<Record<string, unknown> | null>(null); const [enrollment, setEnrollment] = useState<Record<string, unknown> | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  if (!["editor", "reviewer", "publisher", "admin"].includes(session?.user?.role ?? "")) return null;
  async function read() { setState(await apiRequest("/auth/mfa", {}, apiObject)); }
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); await read(); await refresh(); } catch (error) { setMessage(safeApiMessage(error)); } finally { setBusy(false); } }
  return <details className={styles.card}><summary>운영 계정 보호·민감 작업 재인증</summary><p>권리 승인·환불·권한 변경·공개 발행 전에 현재 계정의 인증 상태를 확인합니다. 인증 정보는 복구 초안이나 기기 저장소에 보관하지 않습니다.</p><p role="status">{message}</p><button type="button" disabled={busy} onClick={() => void run(read)}>운영 계정 보호 상태 확인</button>{state ? <p>추가 인증 설정 {state.enabled === true ? "완료" : "미설정"} · 현재 세션 추가 인증 {state.mfaVerified === true ? "확인됨" : "미확인"} · 최근 본인 확인 {state.recentAuthenticated === true ? "유효" : "확인 필요"} · 운영 정책 {state.required === true ? "추가 인증 필수" : "추가 인증 선택"}</p> : null}
    {state && state.enabled !== true ? <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password") ?? ""); event.currentTarget.reset(); void run(async () => { setEnrollment(await apiRequest("/auth/mfa/enroll", { method: "POST", body: { password } }, apiObject)); setMessage("인증 앱에 아래 설정 키를 추가하고 새 코드를 입력하여 확정하세요."); }); }}><label>현재 비밀번호<input type="password" autoComplete="current-password" name="password" required /></label><button type="submit" disabled={busy || state.enrollmentAvailable !== true}>인증 앱 추가 시작</button></form> : null}
    {enrollment ? <div><p>인증 앱 수동 설정 키 (화면을 공유하지 마세요)</p><p className={styles.mono}>{typeof enrollment.secret === "string" ? enrollment.secret : "확인할 수 없음"}</p><form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const code = String(data.get("code") ?? ""); event.currentTarget.reset(); void run(async () => { await apiRequest("/auth/mfa/confirm", { method: "POST", body: { code } }, apiObject); setEnrollment(null); setMessage("실제 인증 앱 코드를 확인하여 추가 인증 설정을 완료했습니다."); }); }}><label>인증 앱의 새 6자리 코드<input name="code" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} autoComplete="one-time-code" required /></label><button type="submit" disabled={busy}>추가 인증 설정 확정</button></form><button type="button" onClick={() => setEnrollment(null)}>화면에서 설정 키 닫기</button></div> : null}
    {state?.enabled === true && state.mfaVerified !== true ? <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const code = String(data.get("code") ?? ""); event.currentTarget.reset(); void run(async () => { await apiRequest("/auth/mfa/challenge", { method: "POST", body: { code } }, apiObject); setMessage("현재 세션에서 추가 인증을 확인했습니다."); }); }}><label>현재 세션의 인증 앱 코드<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required /></label><button type="submit" disabled={busy}>현재 세션 추가 인증</button></form> : null}
    <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password") ?? ""); const totp = String(data.get("totp") ?? ""); event.currentTarget.reset(); void run(async () => { await apiRequest("/auth/reauth", { method: "POST", body: { password, ...(totp ? { totp } : {}) } }, apiObject); setMessage("현재 계정의 최근 본인 확인을 완료했습니다. 민감 작업을 다시 실행할 수 있습니다."); }); }}><label>민감 작업 본인 확인 비밀번호<input type="password" name="password" autoComplete="current-password" required /></label>{state?.enabled === true ? <label>인증 앱의 새로운 코드<input name="totp" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required /></label> : null}<p>같은 인증 코드는 재사용할 수 없습니다. 방금 확인한 코드라면 인증 앱의 다음 코드를 기다리세요.</p><button disabled={busy} type="submit">민감 작업 본인 확인</button></form>
  </details>;
}
