import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { check } from '../domain/errors.ts';
const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function base32(bytes: Buffer): string { let bits=0,value=0,result=''; for(const byte of bytes){value=(value<<8)|byte;bits+=8;while(bits>=5){result+=alphabet[(value >>> (bits-5)) & 31];bits-=5;}} if(bits)result+=alphabet[(value<<(5-bits))&31];return result; }
export function decodeBase32(text: string): Buffer { let bits=0,value=0;const bytes:number[]=[]; for(const char of text){const index=alphabet.indexOf(char);check(index>=0,400,'INVALID_TOTP','인증 키 형식이 올바르지 않습니다.');value=(value<<5)|index;bits+=5;if(bits>=8){bytes.push((value >>> (bits-8))&255);bits-=8;}}return Buffer.from(bytes); }
/** RFC 6238/4226: 30-second HMAC-SHA1, dynamic truncation, 6 decimal digits. */
export function totp(secret: Buffer,counter: number,digits=6): string { const moving=Buffer.alloc(8);moving.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',secret).update(moving).digest();const offset=digest[digest.length-1]&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%10**digits).padStart(digits,'0'); }
export function matchedCounter(secret: Buffer,code: unknown,lastCounter: number,now=Date.now()): number {check(typeof code==='string' && /^\d{6}$/.test(code),401,'MFA_INVALID','인증 코드를 확인해 주세요.');const current=Math.floor(now/30000);for(const counter of [current,current-1,current+1]) if(counter>lastCounter && counter>=0 && timingSafeEqual(Buffer.from(totp(secret,counter)),Buffer.from(code)))return counter;check(false,401,'MFA_INVALID','인증 코드가 만료되었거나 이미 사용되었습니다.');}
export function encryptSecret(secret: Buffer,key: string,userId: string): string { const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',Buffer.from(key,'hex'),iv);cipher.setAAD(Buffer.from(userId));const ciphertext=Buffer.concat([cipher.update(secret),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),ciphertext]).toString('base64url'); }
export function decryptSecret(encrypted: string,key: string,userId: string): Buffer {const data=Buffer.from(encrypted,'base64url');const cipher=createDecipheriv('aes-256-gcm',Buffer.from(key,'hex'),data.subarray(0,12));cipher.setAuthTag(data.subarray(12,28));cipher.setAAD(Buffer.from(userId));return Buffer.concat([cipher.update(data.subarray(28)),cipher.final()]);}
