import Link from "next/link";
import { archiveEvents } from "../../lib/archive-data";
import { ArchiveFooter, ArchiveShell } from "../components/archive-shell";
import { makePageMetadata } from "../site-config";

export const metadata = makePageMetadata("소개와 이용 안내", "전쟁 역사 아카이브의 수집 범위, 공개 상태, 사료 이용 조건과 정정 방법을 안내합니다.", "/about/");

export default function AboutPage() {
  return <ArchiveShell pageClassName="routePage"><section className="routeIntro dark"><p className="routeEyebrow">ABOUT THE ARCHIVE</p><h1>기록의 출처와 맥락을<br />함께 보존합니다.</h1><p>전쟁사를 단정된 하나의 서사가 아닌, 확인 가능한 자료의 연결로 읽습니다.</p></section><section className="aboutPrinciples"><article><span>01</span><h2>출처를 남깁니다</h2><p>공개 기록에서 공급 기관의 자료와 연결 근거를 확인할 수 있습니다.</p></article><article><span>02</span><h2>한계를 설명합니다</h2><p>자료의 작성 배경과 시점, 설명의 범위와 해석을 함께 밝힙니다.</p></article><article><span>03</span><h2>다시 검토합니다</h2><p>출처 확인과 역사 전문가의 승인을 구분하고 정정 이유를 기록합니다.</p></article></section><div className="aboutGuide editorialSheet">
    <nav className="editorialContents" aria-label="이용 안내 목차"><h2>이용 안내</h2><ul><li><a href="#scope">수집 범위와 메뉴 사용법</a></li><li><a href="#review">공개 상태와 검토 기준</a></li><li><a href="#terms">기록을 읽는 데 쓰는 용어</a></li><li><a href="#rights">자료 이용과 인용</a></li><li><a href="#privacy">기기 저장과 개인정보</a></li><li><a href="#corrections">정정 방법</a></li></ul></nav>
    <section className="editorialProse" id="scope"><h2>현재 수집 범위</h2><p>현재 공개 목록은 임진왜란·정유재란과 관련 사료를 중심으로 구성한 {archiveEvents.length}건입니다. 전쟁사 전체의 완전한 목록을 의미하지 않습니다. 기존 자동 수집 기록은 자료 관련성과 원문 근거를 다시 확인하며, 공개 기준에 맞지 않는 기록은 검색과 추천에서 제외합니다.</p><dl className="menuGuide"><div><dt>아카이브</dt><dd>사건·사료를 검색하고 원문과 개별 설명을 확인합니다.</dd></div><div><dt>주제 탐색</dt><dd>질문과 관점에서 출발해 관련 기록을 읽습니다.</dd></div><div><dt>연표</dt><dd>확인된 날짜의 순서와 사건 사이의 흐름을 비교합니다.</dd></div><div><dt>컬렉션</dt><dd>선정 목적과 읽기 순서에 따라 자료를 함께 읽습니다.</dd></div><div><dt>스토리</dt><dd>독립적인 편집 해설과 학습 질문을 읽습니다.</dd></div><div><dt>소개</dt><dd>수집 범위, 공개 기준, 이용과 정정 방법을 확인합니다.</dd></div></dl><Link className="editorialTextLink" href="/collections/">추천 읽기 순서로 시작하기 →</Link></section>
    <section className="editorialProse" id="review"><h2>공개 상태와 검토 기준</h2><p><strong>출처 확인</strong>은 연결된 기관 자료와 서지 정보를 확인했다는 뜻입니다. 역사 전문가의 사실·해석 승인과 동일한 상태가 아닙니다. <strong>사람 검수 완료</strong>는 실제 검수 기록이 있을 때만 표시합니다. 검토 대기·공개 보류 기록은 공개 검색에 포함하지 않습니다.</p><p>각 기록에서 검토 상태, 근거 자료, 편집 해석, 날짜의 정밀도, 자료의 한계와 수정 이력을 확인할 수 있습니다. 기관 수나 자료 수가 많다는 이유만으로 역사적 설명의 정확성을 보장하지 않습니다.</p><p>이 사이트의 공개 내용은 편집 기록으로 관리합니다. 기관 자료를 참고하지만 해당 기관이 이 사이트의 운영이나 설명을 승인했다는 의미는 아닙니다.</p></section>
    <section className="editorialProse" id="terms"><h2>기록을 읽는 데 쓰는 용어</h2><p>아래는 이 아카이브의 화면에서 용어를 사용하는 범위입니다. 같은 자료도 어떤 질문으로 읽는지에 따라 활용 방식이 달라질 수 있습니다.</p><dl className="menuGuide"><div><dt>사료 · 사료 안내</dt><dd>사건을 살펴보는 데 쓰이는 기록과 자료를 가리킵니다. ‘사료 안내’ 페이지는 자료의 배경과 연결 근거를 소개하며, 원문 전문을 제공한다는 뜻은 아닙니다.</dd></div><div><dt>원문</dt><dd>해당 자료의 원래 글을 뜻합니다. 이 사이트가 작성한 요약이나 현대 기관의 설명과 구분합니다. 연결된 기관에서 실제 열람할 수 있는 범위는 각 자료의 ‘대조 위치’에서 확인하세요.</dd></div><div><dt>국역</dt><dd>한문 등으로 작성된 글을 한국어로 옮긴 번역문을 뜻합니다. 국역과 원문을 구분하고, 중요한 표현은 번역의 맥락도 함께 살펴보세요.</dd></div><div><dt>1차 자료</dt><dd>이 사이트에서 원자료 연결에 사용하는 자료 유형 표시입니다. 자료의 존재나 이 표시가 그 안의 모든 주장의 사실성을 보장하지는 않습니다. 작성자의 위치와 작성 배경을 함께 읽어야 합니다.</dd></div><div><dt>기관 해설 · 연구</dt><dd>원자료를 소개하거나 해석한 현대의 설명 자료에 사용하는 유형 표시입니다. 이러한 페이지를 읽는 것과 당시 기록의 원문을 직접 확인하는 것은 구분합니다.</dd></div><div><dt>편집 해석</dt><dd>연결된 자료를 바탕으로 이 아카이브가 제시하는 설명이나 읽기 관점입니다. 직접 인용한 원문이나 실제 당사자의 증언으로 제시하지 않습니다.</dd></div><div><dt>사건 시기 · 제작 시점</dt><dd>사건이 일어난 때와 글을 쓰거나 책을 만든 때를 구분하는 표현입니다. 자료가 다룬 사건의 연도를 해당 판본의 제작일로 옮겨 표시하지 않습니다. 확정하지 못한 시점은 연대 미확인으로 표시합니다.</dd></div></dl></section>
    <section className="editorialProse" id="rights"><h2>자료 이용과 인용</h2><p>각 원자료의 저작권과 이용 조건은 자료를 제공하는 기관의 안내를 따릅니다. 원문 링크를 제공하는 것과 원자료의 복제·배포를 허용하는 것은 다른 일입니다. 이미지와 원문을 내려받거나 다른 곳에 사용할 때 해당 자료의 이용 조건을 확인하세요.</p><p>기록 상세의 인용 기능은 이 사이트의 제목, 주소, 수정일과 열람일을 제공합니다. 연구·보고서에서는 연결된 원자료의 서지 정보와 실제 열람한 위치도 함께 남기는 것을 권합니다. 번역·요약·해설을 원문 인용처럼 표시하지 마세요.</p><p>전쟁·폭력·피해를 다루는 자료는 기록에 안내가 있는 경우 내용을 확인한 뒤 열람하세요. 자료 제안은 검토 후 반영하며 공개 댓글은 제공하지 않습니다. AI 보조는 실제 공급자와 평가 기준을 충족한 서비스에서만 활성화되며 근거 위치와 답변 한계를 함께 표시합니다.</p></section>
    <section className="editorialProse" id="privacy"><h2>이 기기 저장과 개인정보</h2><p>보관함, 읽기 설정과 최근 열람은 해당 브라우저의 저장 공간을 사용합니다. 브라우저 데이터를 지우면 사라질 수 있습니다. API가 연결된 배포에서는 선택형 계정으로 로그인한 뒤 보관함과 연구 작업을 직접 서버에 저장할 수 있습니다. 버전이 충돌하면 저장을 중단하고 보존할 내용을 선택합니다. 공용 기기에서는 이용 후 보관함과 최근 기록을 정리하세요.</p><p>검색은 공개 기록을 대상으로 브라우저에서 수행합니다. 검색어 원문은 자동 수집하지 않습니다. 계정 동기화를 선택하면 해당 보관함·메모·연구 자료를 서버에 전달합니다. AI를 선택하면 입력한 질문과 선택한 공개 기록을 안내된 외부 공급자에 전달하므로 개인 메모를 포함하지 마세요. 외부 자료를 열면 해당 제공 사이트의 개인정보 처리방침이 적용됩니다.</p><Link className="editorialTextLink" href="/saved/">이 기기 보관함 관리 →</Link></section>
    <section className="editorialProse" id="corrections"><h2>잘못된 기록을 발견했을 때</h2><p>기록 상세에서 정정 요청 초안을 만들고 기록 주소, 문제가 있는 문장, 수정 이유, 이를 확인할 원자료 주소를 함께 정리하세요. 추측이나 개인 식별정보를 제보 내용에 포함하지 않는 것이 좋습니다.</p><p>API가 연결된 배포에서는 정정·자료 제안을 접수하고 서버가 발급한 번호로 처리 상태를 조회할 수 있습니다. 연결되지 않은 경우 초안 파일만 저장하며 접수 완료로 표시하지 않습니다. 정정 초안의 저장·복사는 접수 완료가 아닙니다.</p><p>편집자는 근거를 확인한 뒤 공개 콘텐츠를 수정하고 수정일과 정정 이유를 남깁니다. 중요한 근거를 확인할 수 없으면 공개 보류할 수 있습니다. 이전 주소는 검토 안내로 유지해 사라진 링크의 이유를 알 수 있게 합니다.</p><Link className="editorialTextLink" href="/corrections/">정정·자료 제안과 접수 상태 →</Link></section>
  </div><ArchiveFooter /></ArchiveShell>;
}
